### ISSUE TITLE
CMakeLists versions

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt-panel#1022]
```
find_package(lxqt ${LXQT_MINIMUM_VERSION} REQUIRED)
find_package(lxqt-globalkeys ${LXQT_MINIMUM_VERSION} REQUIRED)
find_package(lxqt-globalkeys-ui ${LXQT_MINIMUM_VERSION} REQUIRED)
```
globalkeys should be LXQT_GLOBALKEYS_MINIMUM_VERSION - works fine in 0.14.0 because the versions are the same - but they can differ somewhen

**Comment by luis-pereira** [comment]
@agaida Does `LXQT_GLOBALKEYS_UI_VERSION` make any sense ? 
`LXQT_GLOBALKEYS_VERSION` is enugh, IMO.

**Comment by agaida** [comment]
right
