### ISSUE TITLE
Support i3 IPC to display window names in lxqt-panel

### ISSUE THREAD

**Issue by cdunford** [lxqt/lxqt-panel#1039]
I am trying to use lxqt with the i3 tiling window manager; previously I was using Openbox, but thought I would give i3 a try. One thing I have noticed is that window names often do not show up in the lxqt-panel. The only way I've discovered to see the windows in lxqt-panel is to restart i3 with windows open; once restarted, all of the open windows show in lxqt-panel, however no newly opened windows show up.

Perhaps I'm unaware if this is already supposed to work somehow (I could not find any info in a search), but it looks like i3 provides a socket that can be used to communicate with it and get some of this data: https://i3wm.org/docs/userguide.html#_interprocess_communication

Any guidance on if this is possible today would be great, otherwise this would be a nice enhancement.

I am running:
Linux dunford-ltop 5.0.3-arch1-1-ARCH #1 SMP PREEMPT Tue Mar 19 13:09:13 UTC 2019 x86_64 GNU/Linux

lxqt-panel: 0.14.1-1
i3: 4.16.1-1

**Comment by tsujan** [comment]
I've never used i3 (tried it only once) but, supposing that by "window names" you mean their corresponding task-bar items (and not just their texts), I can say that window managers can make some windows skip task-bar. Maybe, it's about an i3 setting...

But if you really mean *the texts* of task-bar items, it'll deserve an investigation into the panel itself.

**Comment by cdunford** [comment]
I really just mean an entry in the taskbar to represent the window (and would usually contain the window title). I don't believe these are Windows that i3 would want to skip the taskbar, and as I mentioned, they all show up when I restart i3.

**Comment by tsujan** [comment]
Here, I'm suspicious about i3 because:

(1) lxqt-panel acquires info about windows in a standard way; and
(2) It works without problem with window managers that are very different from each other (like kwin, openbox, xfwm, compiz-reloaded+emerald -- some are being developed actively, some are old).

However, I can't be 100% sure; hence leaving this report open.

**Comment by cdunford** [comment]
Yeah it could be an issue with i3. I will see if the behavior changes if I i3 updates.

**Comment by tsujan** [comment]
> I will see if the behavior changes with a new i3 release.

I doubt that updating i3 will change anything.

lxqt-panel makes use of [`KWindowSystem`](https://api.kde.org/frameworks/kwindowsystem/html/classKWindowSystem.html) (convenience access to certain properties and features of the window manager), that's made by KDE devs. `KWindowSystem` does its job correctly. I think i3wm isn't compatible with it somehow.

**Comment by tsujan** [comment]
Closing, because lxqt-panel does it generically. It can't have a special code for i3.
