### ISSUE TITLE
refactoring of some plugins

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/lxqt-panel#1048]
I want to know the likelihood of such pr's being accepted.

The goal of the refactor would be to decouple the gui/lib part of statusnotfier and probably others
(similar approach like https://github.com/CODeRUS/nemo-qml-plugin-statusnotifier)

The gui part would need to link to the library (-lqtstatusnotifier).

**Comment by tsujan** [comment]
@palinek is the expert in Panel's code.

**Comment by palinek** [comment]
Do you want to create and maintain the standalone `libqstatusnotifier` library?

**Comment by palinek** [comment]
> Yes, create and mantain

You definitely can. But now I don't get, why are you asking here? Do you want your freshly created library be a part of lxqt projects?

**Comment by agaida** [comment]
i don't get another part - i this really needed? Additional libraries (except private libs) introduce some additonal burdens for distribution packaging. If the lib is private i have nothing against.

**Comment by tsujan** [comment]
Let's be pragmatic! Is decoupling useful in this case? If yes, how? I don't mean remote future or what could be done with it but the present time.

Separating liibfm-qt from pcmanfm-qt was useful because it was needed by lximage-qt and now, it's used by lxqt-archiver. So, although it was a burden to me as a dev working in that area, I accepted it. Does a similar scenario exist in the case of Panel's widgets?

**Comment by agaida** [comment]
let's be more pragmatic - i have nothing against if the lib would find  a place in `/usr/lib/$triple/lxqt-panel` - a private dir outside the common search path. If the lib(s) can be used by other components they had to be in  `/usr/lib/$triple/` - i would hate it to take care and do extra work without  a sane reason.

**Comment by damianatorrpm** [comment]
Yes it should live in /usr/lib/libqstatusnotifier and be used by other components and projects as well as the libqnotification.

**Comment by tsujan** [comment]
This belongs to [Discussions](https://github.com/lxqt/lxqt/discussions).
