### ISSUE TITLE
[feature request] Widget for switching user-defined options

### ISSUE THREAD

**Issue by ccompletion** [lxqt/lxqt-panel#1055]
**Why?**

This would give customization power to users. For example, it would be trivial to add a CPU-governor switcher to tray and decorate the options with icons and text of your choosing.
User can make simple tray switches for any state that can be switched with a command.

**How?**

In its settings, user creates a custom list. Each list item can receive:
1. filesystem path to an icon,
2. item text,
3. command to execute.

How does widget work?
In panel area, it displays the user-defined icon.
In tooltip, it displays the item text.
When user clicks the icon, it displays an icon-text list of options.
If user selects a different option, widget executes the command and begins displaying its icon/tooltip in panel area.

Default selected item? It would be fine if widget simply chooses the first item on starting, without actually running any command. Could add extra configurability later.

Note: I noticed that this is actually very similar to quicklaunch widget. Maybe it could be implemented by adding a 'depth' mode to this widget instead, the new mode altering it to function as described above.

**Comment by tsujan** [comment]
We have the Custom Command plugin now.
