### ISSUE TITLE
World Clock text can still be cut

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#1056]
##### Expected Behavior

To see full text on world clock.
##### Current Behavior

When the system font is made bigger, the world click text will be cut until the panel is restarted.

##### Steps to Reproduce (for bugs)

1. Make the font bigger by 3 units in LXQt Appearance Configuration.
2. Apply the change.

Then, you might see cut text on world clock. If you restart panel, the text will be fixed but if you make the font smaller, it might be cut again (and have an incorrect positioning).

##### Context

I saw that on VirtualBox, while testing a completely unrelated thing.
##### System Information

Latest LXQt.

**Comment by palinek** [comment]
tried to fix this in #1057

**Comment by tsujan** [comment]
Thanks! Will test it soon.
