### ISSUE TITLE
Status Notifier cannot find icon if its path is changed

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#1061]
Very rarely, an app may change its systray icon path. Skype and Doscord both do so. In that case, Status Notifier searches in the old path and, because there's no icon in it, falls back to `application-x-executable`.

##### Expected Behavior

Status Notifier should check if the path is changed before fetching the icon.
##### Current Behavior

It doesn't.
##### Possible Solution

Get "IconThemePath" before getting the icon in `statusnotifierbutton.cpp`. I'll make a PR.
##### Steps to Reproduce (for bugs)

1. Install Discord or Skype (or don't install them and just believe me).
2. Start them.

The tray icon will be `application-x-executable` for Skype after signing it. The same happens with Discord after selecting another item in its side-pane.

The reason is that their icons are `/tmp/.org.chromium.Chromium.ABC/ICON_NAME.png` and `ABC` changes.

##### Context

See this comment https://github.com/lxqt/lxqt/issues/1468#issuecomment-489201158 (which was added to the wrong page).
##### System Information

Latest LXQt

**Comment by stefonarch** [comment]
Same goes for wire, and as said it happens only when libappindicator-gtk3
 is installed, otherwise it's using the old systray. Other thing is that with libappindicator-gtk3
 and statusnotifier I cannot activate them by left click.

**Comment by tsujan** [comment]
@stefonarch Forget about the old systray ;) https://github.com/lxqt/lxqt-panel/pull/1062 fixes the problem.

**Comment by tsujan** [comment]
> I cannot activate them by left click.

Yes, most systray icons are so but that depends on the app too. For example, left clicking desktop notification tray icon shows its menu or when the tray icon of FeatherNotes or git GoldenDict is left clicked, its window is raised. These things should be added to the app's code.

**Comment by YamashitaRen** [comment]
> I cannot activate them by left click
Indeed. Left click does nothing on LXQt and Plasma 5 while it opens menu on Cinnamon.
I am using a [patched](https://git.archlinux.org/svntogit/community.git/tree/trunk/improved-plasma.patch?h=packages/libappindicator) version of libappindicator3 though...

**Comment by tsujan** [comment]
> Indeed. Left click does nothing on...

As mentioned above, that's not LXQt's problem.

**Comment by YamashitaRen** [comment]
But why is it opening menu on Cinnamon then ? Do you think it is a special Cinnamon code that forces menu to open when I left-click while nothing should happen (as per application code) ?

**Comment by tsujan** [comment]
> But why is it opening menu on Cinnamon then ?

I don't know what's inside `libappindicator-gtk3's code but our and KDE's codes are standard. Cinnamon is a GTK-based environment and, surely, has a different code. If you try Enlightenment, you might see a different behavior.

All in all, right or left clicking isn't important. What's important is showing an icon that exists. That's what this report and its corresponding PR are about.

**Comment by stefonarch** [comment]
> All in all, right or left clicking isn't important. What's important is showing an icon that exists. That's what this report and its corresponding PR are about.

> @stefonarch Forget about the old systray ;) #1062 fixes the problem.


Well, icon is fixed when libappindicator-gtk3 is installed now, but for me opening by left click (instead by right click > open) is important for every content of the panel, so I prefer legacy systray where this works.

**Comment by tsujan** [comment]
> but for me opening by left click (instead by right click > open) is important

I don't think anything can be done for it and even otherwise, it shouldn't be done, especially because left-clicking is reserved for other actions.

**Comment by stefonarch** [comment]
Don't know, but I see most stuff opens by default on left and has a menu with the right click. Anyway I dis-installed  libappindicator-gtk3 as it was  before. 
Btw telegram is electron too  I think and sits in statusnotyfier by itself without  libappindicator-gtk3.

**Comment by tsujan** [comment]
> Btw telegram is electron too

Telegram is purely Qt-based and free from such complications ;)

**Comment by wxl** [comment]
I'm hearing a lot about libappindicator-gtk3 being problematic and also unnecessary. Perhaps LXQt packagers should make it a conflict so it doesn't get installed and create this poor experience?

**Comment by tsujan** [comment]
@wxl We shouldn't make artificial conflicts. The problem reported here was LXQt's and is fixed in the PR. The other part (left vs. right clicking) isn't a problem in itself.

Personally, I prefer my systray to remain empty and all tray icons to go inside Status Notifier -- yet another personal preference added to the list ;)

**Comment by agaida** [comment]
@wxl - not possible for debian and i guess not recommended for derivatives - it would do more harm than good. Read Policy '7.4 Conflicting binary packages - Conflicts'
> Neither Breaks nor Conflicts should be used unless two packages cannot be installed at the same time or installing them both causes one of them to be broken or unusable. Having similar functionality or performing the same tasks as another package is not sufficient reason to declare Breaks or Conflicts with that package.

And i'm not eager to work on such bugreports again, please remember connman or cmst and other network managers. :smiling_imp:

**Comment by tsujan** [comment]
That's right; there's no real conflict. Moreover, the purpose of libappindicator-gtk3 is quite the opposite: allowing GTK applications to have a menu is systrays of KDE, LXQt, Enlightenment,... Whether it does it in a consistent way or not is another question but it isn't our problem.

**Comment by wxl** [comment]
Okie dokie. Just asking!

**Comment by tsujan** [comment]
Although this problem doesn't exist in the latest git lxqt-panel anymore, I saw something similar in Enlightenment tonight. Skype, Doscord and any app that changes its tray icon path in this weird way have a very nonstandard behavior. If they were open-source, I'd recommend reporting that as a bug.

**Comment by jarrard** [comment]
Been getting this with my lxqt install. Mostly affects the Skype icon, sometimes it works, sometimes it doesn't.

**Comment by tsujan** [comment]
> Been getting this with my lxqt install

This bug was fixed in May, 2019. You may have an outdated LXQt installation. It's also possible that you use System Tray (obsolete) instead of Status Notifier.

> Am a little worried however that the lxqt panel git has depreciated code in it tho

Qt devs make Qt methods deprecated so fast that almost no Qt code can be free from such messages for a long time. KDE is full of them.
