### ISSUE TITLE
Main menu cannot launch some valid desktop files

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#1063]
A recent example of such a desktop entry:
```
[Desktop Entry]
Type=Application
Exec=LD_PRELOAD=ClazyPlugin.so:libclangTidyPlugin.so qtcreator %F
Name=Qt Creator
...
```
It can be launched in KDE; so, I think it's valid, in spite of `=` in its `Exec` value.

**Comment by tsujan** [comment]
Apparently, it wasn't valid and is corrected in AUR quickly. Hence, closing.

Still, KDE can launch it.

**Comment by palinek** [comment]
https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s07.html
