### ISSUE TITLE
Horizontal panel not changing it's length in i3-gapps

### ISSUE THREAD

**Issue by sandboiii** [lxqt/lxqt-panel#1067]
Today I tried to pair lxqt with my i3-gapps setup and encountered several issues in this way. I attached screenshots in collapsed blocks which you can see by clicking on them.

<details>
  <summary>Initial state</summary>

![2019-05-19-133201_1906x1043_scrot](https://user-images.githubusercontent.com/17468894/57980947-83d55980-7a3a-11e9-8dd2-a9dc79cb06f3.png)

</details>

##### Expected Behavior
When panel position is set to bottom or top of desktop changing it's length must resize horizontally the panel

##### Current Behavior
<details>
  <summary>Set state</summary>

![2019-05-19-133313_1919x1045_scrot](https://user-images.githubusercontent.com/17468894/57980964-abc4bd00-7a3a-11e9-9ee1-13e423bc11c4.png)

</details>

Changing length doesn't affect size of the panel in any ways

##### Possible Solution
?

##### Steps to Reproduce (for bugs)

1. Change wm to i3-gapps
2. Open panel configuration
3. Change panel length to whatever
4. Size of the panel is still 100%

##### Context
I tried to setup [polybar](https://github.com/polybar/polybar) along with the panel. And the panel displays on top the polybar, yet I still wanted to it to be visible. For some reason I can't position the panel vertically (see #1068) and I can't change it's size when it placed horizontally.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 5.1.2-arch1-1-ARCH
* Qt Version: Qt 5.12.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 8.3.0) on "xcb" 
* liblxqt Version: 0.14.1-1
* lxqt-build-tools Version: 0.6.0-1
* Package version: 0.14.1-1
* i3-gaps version: 4.16.1-1

**Comment by agaida** [comment]
Why should esp. the panel work with i3 without flaws?

**Comment by Sandmonster** [comment]
@agaida what do you mean?

**Comment by tsujan** [comment]
i3 is a tiling WM. So, I think this should be reported to its devs.

**Comment by Sandmonster** [comment]
Is it really matters to the panel what kind of windows manager I use?

**Comment by jubalh** [comment]
Hard for me to tell whether it's i3 misbehaving or lxqt-panel.

From: https://www.reddit.com/r/i3wm/comments/68h3z7/can_you_tell_i3_to_completly_ignore_a_window/

> [...] by making it an override redirect window. But that requires the application to properly deal with that.

Is it possible that we don't do this?

**Comment by palinek** [comment]
> Is it really matters to the panel what kind of windows manager I use?

No panel doesn't care about window manager. But in case of tiling WM the manager can/will ignore the panel's requests for position/size.

@jubalh 
I don't think it is a good idea do inject X11 specific code into panel.

**Comment by jubalh** [comment]
> But in case of tiling WM the manager can/will ignore the panel's requests for position/size.

I thought there must be some way of telling i3 to ignore a certain window based on window class/name or something. But not a i3 user anymore since a long time. @Sandmonster did you look that up or try it?

**Comment by Sandmonster** [comment]
@jubalh I tried making the panel [always floating](https://faq.i3wm.org/question/61/forcing-windows-as-always-floating.1.html), but it doesn't change anything. I don't think I can affect the panel any other ways

**Comment by jubalh** [comment]
Right, I think that was what I used. Then I have no idea unfortunately.

**Comment by Sandmonster** [comment]
Alright, seems like this issue is bound to interaction between Qt, Xorg and i3. I would like to close this issue, however I need some more information to open it in either i3 or Qt projects. I suppose that this issue would be related to i3 if someone would show this panel work correctly on any other tiling or dynamic wm

**Comment by b1scu1t** [comment]
Hi, I'm currently using LXQT 14.1 with BSPWM as the window manager.
I can resize the panel normally.
![image](https://user-images.githubusercontent.com/41207956/60403107-25d28080-9b67-11e9-9949-7ca513e6ef8c.png)

Currently lxqt-panel is at the bottom, aligned to the center and at 90% length.

**Comment by sandboiii** [comment]
I'm gonna close this obsolete issue since @b1scu1t provided some information on this topic and it's no longer relevant for me
