### ISSUE TITLE
Vertical panel fills full width of the screen in i3-gapps

### ISSUE THREAD

**Issue by Sandmonster** [lxqt/lxqt-panel#1068]
Today I tried to pair lxqt with my i3-gapps setup and encountered several issues in this way. I attached screenshots in collapsed blocks which you can see by clicking on them.

<details>
  <summary>Initial state</summary>

![2019-05-19-133201_1906x1043_scrot](https://user-images.githubusercontent.com/17468894/57980947-83d55980-7a3a-11e9-8dd2-a9dc79cb06f3.png)

</details>

##### Expected Behavior
When you set panel position is set to left or right of desktop it must be vertically attached to specified edge of the screen

##### Current Behavior
<details>
  <summary>Set state</summary>

![2019-05-19-135655_1919x1079_scrot](https://user-images.githubusercontent.com/17468894/57981335-b5e8ba80-7a3e-11e9-951c-8adab0deb3bb.png)

![2019-05-19-135714_1919x1046_scrot](https://user-images.githubusercontent.com/17468894/57981328-a36e8100-7a3e-11e9-84a7-4fe6dd667573.png)

</details>

Setting panel position to left or right makes it fill whole width of the screen

##### Possible Solution
?

##### Steps to Reproduce (for bugs)

1. Change wm to i3-gapps
2. Open panel configuration
3. Change panel postion to left or rigth
4. Panel fills full width of the screen

##### Context
I tried to setup [polybar](https://github.com/polybar/polybar) along with the panel. And the panel displays on top the polybar, yet I still wanted to it to be visible. For some reason I can't position the panel vertically and I can't change it's size when it placed horizontally (see #1067).

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 5.1.2-arch1-1-ARCH
* Qt Version: Qt 5.12.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 8.3.0) on "xcb" 
* liblxqt Version: 0.14.1-1
* lxqt-build-tools Version: 0.6.0-1
* Package version: 0.14.1-1
* i3-gaps version: 4.16.1-1

**Comment by agaida** [comment]
if it works with i3 please don't re-open - if not, feel free to re-open. 

Reason: (quote from a debian bug about i3-gapps)
> ...
> 2. Both upstreams said the fork is of minor code quality
> 3. Efforts are being made to fix that
> ...
