### ISSUE TITLE
systemd waits 90s to kill lxpanel after typing 'reboot' on sparkylinux-rolling

### ISSUE THREAD

**Issue by kanliot** [lxqt/lxqt-panel#1073]
Basically I want to reboot.  But systemd is trying to wait for lxpanel to finish. This started happening when I got a few new packages from sparkylinux. through system update.
```
May 23 12:40:40 maleday systemd[1]: session-1.scope: Stopping timed out. Killing.
May 23 12:40:40 maleday systemd[1]: session-1.scope: Killing process 944 (lxqt-panel) with signal SIGKILL.
May 23 12:40:40 maleday systemd[1]: session-1.scope: Failed with result 'timeout'.

```

how to reproduce:
start an app like firefox or galculator through lxpanel, then type sudo reboot in a terminal window.
It seems dependent on having an app opened by lxpanel, and not alt-f2
I am running sparkylinux rolling based on debian 10:  this is a vanilla lxqt-openbox distro
lxqt-panel 0.14.1
liblxqt   0.14.1
Qt        5.11.3

**Comment by agaida** [comment]
Can happend - should not. Maybe you should change your systemd settings a bit - more desktop oriented:
```
/etc/systemd/logind.conf: KillUserProcesses=yes
``` 
Some processes don't terminate gracefully - if you have menu-cache in the list of hanging processes, just don't care, we know it and will working on it.

**Comment by tsujan** [comment]
Not our problem. As @agaida said, `KillUserProcesses=yes` should be in `/etc/systemd/logind.conf`.

**Comment by tsujan** [comment]
> if you have menu-cache in the list of hanging processes...

It can't be there when the panel is compiled with default options.
