### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by yan12125** [lxqt/lxqt-panel#1099]
##### Expected Behavior
git-master can always be built from source

##### Current Behavior
There were 2 FTBFS accidents:

* https://github.com/lxqt/lxqt-panel/commit/a038123cbdd308a55daecff777ecf3c35f051597
* https://github.com/lxqt/lxqt-panel/pull/1074#issuecomment-497941565

##### Possible Solution
Setting up Travis CI builder. I had setup Travis CI for qtermwidget and it works fine so far: https://github.com/lxqt/qtermwidget/blob/master/.travis.yml.

Ref: https://github.com/lxqt/lxqt/issues/1644

##### Steps to Reproduce (for bugs)
1. Build git-master frequently

##### Context
Building is the first step of contributing :)

##### System Information
* Distribution & Version: Arch Linux up-to-date
* Kernel: 5.1.6.arch1-2 (my unofficial build)
* Qt Version: 5.13.0beta4-1
* liblxqt Version: git-master
* lxqt-build-tools Version: git-master
* Package version: git-master

**Comment by agaida** [comment]
Just go for it - would be great to have
