### ISSUE TITLE
Compton draws a border around elements from panel

### ISSUE THREAD

**Issue by arcolinuxz** [lxqt/lxqt-panel#1127]
It is best I show you first what happens my end.

![border](https://user-images.githubusercontent.com/36679406/61168195-b7b89100-a54a-11e9-84ad-183a81ead0da.gif)

We are developing an ArcoLinux LXQt these days  at https://arcolinux.info/.

We use openbox as backend session and compton for the window effects.

As you see in the bmp there is a transparent border around any and all widgets from LXQt.

This happens if you do **Right Mouse Click** on any of the widgets of LXQt.

Can you tell us what the name is or class role so we can add it to our compton.conf?

You can not investigate it with xprop - not even with -spy option to know its name. 
I have tried many common sense names but failed.

Can you fill us in how you named the right mouse click popup menu we see?

**Comment by tsujan** [comment]
2 weeks ago, I saw that compton's development had started again and tried its latest git version. It was better than before but still far behind KWin. And yes, I saw those artifacts around translucent widgets.

We can't do anything; compton isn't an LXQt app. You should report it to its new developer and help him find the cause (although I think it's already reported).

**Comment by tsujan** [comment]
Oh, wait a minute! This isn't about compton but about your settings.

See Kvantum source → INSTALL or, in short, add lines like these to`~/.config/compton.conf`:

```
shadow-exclude = [ "argb && (_NET_WM_WINDOW_TYPE@:a *= 'MENU' || _NET_WM_WINDOW_TYPE@:a *= 'COMBO')" ];
blur-background-exclude = [ "(_NET_WM_WINDOW_TYPE@:a *= 'MENU' || _NET_WM_WINDOW_TYPE@:a *= 'COMBO')" ];
```
 and restart compton.

**Comment by arcolinuxz** [comment]
![better](https://user-images.githubusercontent.com/36679406/61169385-dcb5ff80-a55c-11e9-9aa5-8aa3cf0de725.gif)

We needed to know the names of these windows and with these lines we do not see the transparent background anymore.

LXQt will get all the merits it deserves.

Great desktop you have developed here.
An enthousiast ;-)

Thanks

**Comment by tsujan** [comment]
> We needed to know the names of these windows

They are `_NET_WM_WINDOW_TYPE@:a *= 'MENU'` and `_NET_WM_WINDOW_TYPE@:a *= 'COMBO'` (as written above). If you've added them correctly to `~/.config/compton.conf`, the above-mentioned lines don't remove translucency but just remove compton's menu shadows and blurring.

Long story made short, you use Kvantum and Kvantum draws its own menu shadows. Some compositors (like Compton and Compiz-reloaded) add their menu shadows on the top of them. Fortunately, those compositors also have options for disabling menu shadows.

The latest Kvantum Manager also has an option for such compositors: `Kvantum Manager → Configure active Theme → Compositing & General Look → Shadowless menus and tooltips`. Then, a logout and login will be needed.

Other widget styles (Breeze, Fusion,...) don't provide their own menu shadow (Breeze depends on KWin for it).

**Comment by arcolinuxz** [comment]
Yes this is indeed much better.
Got rid of the two lines in compton and changed the kvantum compositing to your settings

With all the trials to set it right, I saw there was still a line in there for pcmanfm-qt in compton.conf.

With that gone and our settings we have a super great look now.

![2019-07-13-185008_1920x1080_scrot](https://user-images.githubusercontent.com/36679406/61174374-65ee2600-a59f-11e9-91db-7b4091e37b07.png)

Transparent right mouse clickmenu's with shadow .... great

Thanks for the help

**Comment by tsujan** [comment]
You're welcome.

Your last screenshot shows an appropriate Compton setting. If you use the latest release of Kvantum, there should be no issue.

You could also try Compton's blurring if your graphic card supports it. Here, with a decent graphic card and the older Compton, it used a considerable amount of resources. The new Compton's blurring is still experimental and has some problems but it's good that Compton started to be actively developed again.
