### ISSUE TITLE
Incorrect Quick Launcher icons when adding .desktop files

### ISSUE THREAD

**Issue by voycey** [lxqt/lxqt-panel#1139]
##### Expected Behavior
When I drag a .desktop file to the quick launcher widget it should add a shortcut with the correct icon

##### Current Behavior
The first icon adds successfully but then every icon after that is incorrect.
I have also tried editing the .config/lxqt/panel.conf file manually but same result.

![image](https://user-images.githubusercontent.com/1065098/62091075-92e64c80-b2b2-11e9-8901-3287ae9f1455.png)

Entry in .config/lxqt/panel.conf:

```
[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/home/dan/Desktop/mate-terminal.desktop
apps\3\desktop=/home/dan/Desktop/code.desktop
apps\4\desktop=/home/dan/Desktop/jetbrains-phpstorm.desktop
apps\5\desktop=/home/dan/Desktop/jetbrains-webstorm.desktop
apps\6\desktop=/home/dan/Desktop/jetbrains-datagrip.desktop
apps\7\desktop=/home/dan/Desktop/jetbrains-idea.desktop
apps\8\desktop=/home/dan/Desktop/google-chrome.desktop
apps\size=8
type=quicklaunch
```

Two distinct .desktop files:

```
[Desktop Entry]
Categories=Development;IDE;
Comment=Lightning-smart PHP IDE
Exec="/home/dan/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/191.7479.51/bin/phpstorm.sh" %f
Icon=/home/dan/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/.icon.svg
Name=PhpStorm
StartupWMClass=jetbrains-phpstorm
Terminal=false
Type=Application
Version=1.0
```

```
[Desktop Entry]
Categories=Development;IDE;
Comment=The smartest JavaScript IDE
Exec="/home/dan/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/191.7479.14/bin/webstorm.sh" %f
Icon=/home/dan/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/.icon.svg
Name=WebStorm
StartupWMClass=jetbrains-webstorm
Terminal=false
Type=Application
Version=1.0
```

##### Possible Solution
Perhaps this is because the icon names are the same but in different folders? There should be some context added against each icon .

##### Steps to Reproduce (for bugs)

1. Create the two .desktop files as above
2. Create a quick launcher widget and try and drag both into the quick launcher
3. Icons will all be the same.

##### Context
I would like my quick launchers to have the correct icons.

##### System Information

* Distribution & Version: Lubuntu
* Kernel: Linux dan-VirtualBox 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: ?
* liblxqt Version: 
liblxqt0/disco,now 0.14.1-0ubuntu1 amd64 [installed,automatic], liblxqt0-dev/disco 0.14.1-0ubuntu1 amd64
* lxqt-build-tools Version: 
lxqt-build-tools/disco,disco 0.6.0-2ubuntu1 all
* Package version:

**Comment by tsujan** [comment]
Confirming with the latest git lxqt-panel.

**Comment by tsujan** [comment]
I think @voycey's theory is correct: our icon cache only "sees" icon names, ignoring their paths.
