### ISSUE TITLE
add font setting in worldclock widget

### ISSUE THREAD

**Issue by bjlockie** [lxqt/lxqt-panel#1165]
Add ability fort user to set the font size of the worldclock widget without having to use HTML.
The following works but I should have been able to change the font size without resorting to HTML.
<fon't size='13'><b>'HH:mm'</b> 'ddd MMM d yyyy'</fon't>

* Distribution & Version: lubuntu-19.04
* Kernel: 5.0.0
* Qt Version: 5.12.2
* liblxqt Version: 0.14.1

**Comment by agaida** [comment]
no - and the ability is already there - in the advanced settings.

**Comment by agaida** [comment]
and please file downstream bugs about ancient versions into upstream - i would react different if you would file a bug against latest git.

**Comment by bjlockie** [comment]
Are you saying the ability is there in a later version?

**Comment by agaida** [comment]
no - in the advanced settings - should be sufficient

**Comment by tsujan** [comment]
> I should have been able to change the font size without resorting to HTML

There's no reason you "should" when there's already a flexible setting for that. A duplicate setting is not an option.
