### ISSUE TITLE
Volume notification settings not always respected

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1171]
Notifications of volume changes are inconsistent, depending if done by mouse/touchpad or by keyboard shortcuts/dedicated buttons.

##### Expected Behavior

Disabling notification in volume control settings should always be respected.
##### Current Behavior

The setting works only if using mouse, mousewheel or opening volume slider and using arrow keys.

##### Steps to Reproduce (for bugs)

1. Right click on volume icon, uncheck "always notify volume changes"
2. Assign a shortcut to raise or lower volume or use the dedicated buttons (laptop)
3. The notification window will pop-up always
4. using mousewheel or trackpad or arrow keys on slider the setting is respected.

##### System Information

* Distribution & Version: Latest git, arch; released version, arch.

**Comment by tsujan** [comment]
I took a look at the code. It's by design: the notification is forced when shortcuts are used (lxqtvolume.cpp → LXQtVolume::showNotification).

IMO, the coder's design is OK: If the volume is changed by other means, the user could see its value. Only shortcuts need a way of showing the value; hence forcing notifications.

To keep backward compatibility, we can add the check box "Notify about volume changes with shortcuts" below "Always notify about volume changes" so that if the latter is checked, the former becomes disabled+checked. The user can uncheck it after unchecking the first box. In this way, the purpose of notifications will be clearer too.

**Comment by stefonarch** [comment]
Well, I don't see any need to distinguish how the user change the volume, I don't think anybody would use different settings. Is not possibile  to have just one setting that fits all?

**Comment by stefonarch** [comment]
ps: and it's not only keyboard shortcuts but also dedicated buttons on laptops, some have extra volume and mute buttons, mine has those [cool ones on top of the keyboard](http://ksassets.timeincuk.net/wp/uploads/sites/54/2006/09/3486-6977-1.jpg).

**Comment by tsujan** [comment]
> I don't see any need to distinguish how the user change the volume

There *is* a need, as mentioned above (the lack of value feedback).

**Comment by tsujan** [comment]
P.S. I usually avoid mind-reading (it's ridiculous most of the time) but not when reading codes ;) I guess the coder had the lack of feedback in mind when he added a "forcing" variable to `LXQtVolume::showNotification` -- and I agree with him.

**Comment by stefonarch** [comment]
> > I don't see any need to distinguish how the user change the volume
> 
> There _is_ a need, as mentioned above (the lack of value feedback).

Not so sure about the need, usually the value feedback one gets directly in the ears, changing volume during playing audio/video files.

The most stupid value notification existing (once on KDE) is the one about brightness...

**Comment by tsujan** [comment]
I'm just trying not to disappoint users that don't want notifications with mouse wheel but want them with keyboard (I'm not one of them) -- the code was written so intentionally. And adding a checkbox is a piece of cake.

**Comment by stefonarch** [comment]
My point is that I doubt they even exist and having an hardly or never used setting.

**Comment by tsujan** [comment]
Simple, backward-compatible, and feature-rich: https://github.com/lxqt/lxqt-panel/pull/1175

**Comment by stefonarch** [comment]
Works fine.

**Comment by tsujan** [comment]
Thanks for testing!

I also tested it by manually editing the config file before starting Panel, setting `allwaysShowNotifications` to `true` and `showKeyboardNotifications` to `false`. The code correctly interpreted the second value as `true` because the first one was so.

**Comment by ozky** [comment]
Sounds good can't test it locally as Mageia have only stable lxqt in repos. 
Second thing is they only provide security fixes to packages,no new versions so lxqt get upgraded only next Mageia release.
Maybe need to start thinking change to other distro.

**Comment by tsujan** [comment]
> Maybe need to start thinking change to other distro.

Or you could learn how to make packages for Mageia (I know nothing about it). If it's difficult, there are nice options like Debian Testing (or even Unstable), Arch, Manjaro (Arch made user friendly) and OpenSUSE Tumbleweed. There are more, of course.
