### ISSUE TITLE
Inconsistent handling of mouse wheel events to switch tabs/desktops/windows

### ISSUE THREAD

**Issue by nacktmull** [lxqt/lxqt-panel#1194]
Qt's default handling of mouse wheel events to switch tabs in a tab widget works fine (on my desktops) out of the box.
Plugin-desktopswitch also works for me, but plugin-taskbar requires me to scroll the wheel (one that "clicks" after every move, no "clickless" wheel or however that's called) three times to switch to the next/previous desktop.

##### Expected Behavior
Tab/desktop/window switching via mouse wheel should be consistent across Qt itself and LXQt applications.

##### Current Behavior
Tab/desktop/window switching via mouse wheel is not consistent across Qt itself and LXQt applications. Especially plugin-taskbar shows unexpected behaviour: It is required to scroll the mouse wheel three times to switch to the next/previous window instead of just scrolling once.

##### Possible Solution
I had a look at the sources and noticed the different thresholds in desktopswitch and taskbar (100 vs. 300). I then saw there's a workaround in the master branch of plugin-taskbar that adds a "wheelDeltaThreshold" option to manually override the fixed 300 threshold from tag 0.14.1.
That's a great improvement and will probably solve the problem for me, although I would prefer a consistent handling, e.g. by adding a global threshold setting that's also respected by plugin-desktopswitch.
But I cannot remember that I ever had a need to configure such a threshold. Firefox, Qt, every application supporting tab switching per mouse wheel just seemed to work out of the box. Qt seems to use a different approach than LXQt. They evaluate QWheelEvent->angleDelta() in QTabBar, while plugin-desktopswitch and plugin-taskbar rely on QWheelEvent->delta(), which seems to be deprecated since Qt 5.0.
The code for tab switching in qtabbar.cpp is:

#if QT_CONFIG(wheelevent)
void QTabBar::wheelEvent(QWheelEvent *event)
{
#ifndef Q_OS_MAC
    Q_D(QTabBar);
    int delta = (qAbs(event->angleDelta().x()) > qAbs(event->angleDelta().y()) ?
                     event->angleDelta().x() : event->angleDelta().y());
    int offset = delta > 0 ? -1 : 1;
    d->setCurrentNextEnabledIndex(offset);
    QWidget::wheelEvent(event);
#else
    Q_UNUSED(event)
#endif
}
#endif // QT_CONFIG(wheelevent)

It seems there's no threshold required at all.
Would it be possible to use the same code in LXQt to get consistent mouse wheel switching in Qt and LXQt, no matter if switching tabs, desktops, active windows or whatever?

##### Steps to Reproduce (for bugs)
1. scroll wheel once on a Qt tab => widget switches to next/previous tab.
2. scroll wheel once on plugin-desktopswitch => LXQt switches to next/previous desktop.
3. scroll wheel once on plugin-taskbar => LXQt doesn't switch to next/previous window.

##### Context
It doesn't make sense to scroll three times to switch the active window.
It makes sense to scroll once to switch the active window.

##### System Information
* Distribution & Version: Debian Buster 10.1
* Kernel: 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
* Qt Version: 5.11.3
* liblxqt Version: 0.14.1-1
* lxqt-build-tools Version: 0.6.0-2
* Package version: lxqt/stable,now 29 amd64

PS: "code" markup is not working. The preview shows all code on one line, so I decided to post as plain text.

PPS: I've never seen such a fucked up attitude against new users trying to support a project.

**Comment by tsujan** [comment]
What you're saying here (expect for the long comment after "Possible Solution", which I didn't read) amounts to: "I don't want a configuration; make it a fixed value."

You could guess that others wanted a configuration because, maybe, they didn't want a desktop switch by an unintentional wheel turn over the task bar -- or for any other reason. The fixed value you want is covered by the config dialog too.

**Comment by palinek** [comment]
@nacktmull based on your post you seem to be oriented well and are familiar with C++/Qt... Would you mind to implement those changes and submit PR(s)?
Of course, if there is an existing configuration for the behavior, please, don't drop it.
