### ISSUE TITLE
Taskbar buttons remain depressed after dragging them

### ISSUE THREAD

**Issue by jlindgren90** [lxqt/lxqt-panel#1204]
##### Expected Behavior
Only the taskbar button for the active window should be depressed.

##### Current Behavior
Taskbar buttons remain depressed after dragging them, even for inactive windows.  This makes it difficult to tell which window is active.

##### Possible Solution
I've looked at the code a little without finding a simple solution.  I think that the mouseReleaseEvent(), which would normally un-press the taskbar button, is not called after a drag-and-drop operation.  QToolButton itself doesn't appear to respond to any drag events; maybe it needs to do so to support this type of usage.

##### Steps to Reproduce (for bugs)
1. Click and hold the taskbar button for an inactive window
2. Drag the button to a different position and let go of the mouse button
3. See that the taskbar button appears pressed even though the window is not active

##### Context
This occurs by accident sometimes, if the mouse pointer moves slightly while trying to activate a window by clicking on its taskbar button.  Then the taskbar buttons looks like the window was activated, even though it actually wasn't.

##### System Information
* Distribution & Version: I've seen this on both Ubuntu and Arch Linux
* Kernel: Multiple versions, doesn't matter
* Qt Version: 5.12.4, 5.13.1
* liblxqt Version: 0.14.1
* lxqt-build-tools Version: not sure
* Package version: 0.14.1

**Comment by tsujan** [comment]
Confirming. It happens with Qt stylesheet and QStyle alike: the pressed state of the task button (`QStyle::State_Sunken`) persists after drop.

**Comment by tsujan** [comment]
This can be fixed by sending `mouseReleaseEvent` appropriately. Here,"appropriately" is a little hard to explain but easy to code (most importantly, the event position shouldn't be inside the button rectangle); I tested by adding a few lines and it worked fine.

However, I'd prefer a more elegant solution if possible (although the lack of `mouseReleaseEvent` is the real cause); hence, not making a PR yet...

**Comment by tsujan** [comment]
OK, couldn't find a solution better than https://github.com/lxqt/lxqt-panel/pull/1205
