### ISSUE TITLE
Remove QDesktopWidget from Panel's code

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#1260]
`QDesktopWidget` is "obsolete" (as Qt doc says) and can cause serious problems. It should be removed and `QScreen` methods should be used instead.

**Comment by tsujan** [comment]
I'll do it in a few steps. First the panel itself…

**Comment by agaida** [comment]
you really know how to have fun :smile:

**Comment by tsujan** [comment]
I'm 101% sure that `QDesktopWidget` was the cause of https://github.com/lxqt/lxqt/issues/1704 and https://github.com/lxqt/lxqt/issues/1703. Of course, I may be wrong ;) But I know first hand that `QDesktopWidget` is buggy (that doesn't mean `QScreen` isn't but it's more reliable and has worked like a charm with pcmanfm-qt's desktop).

**Comment by tsujan** [comment]
Note to myself:

I think most problems in `QDesktopWidget` are caused by `QDesktopWidget::availableGeometry` and `QDesktopWidget::screenNumber(const QWidget *w)`. pcmanfm-qt got rid of them.

**Comment by tsujan** [comment]
The first and biggest step is done in https://github.com/lxqt/lxqt-panel/pull/1261
