### ISSUE TITLE
Worldclock: add a tooltip to display the date when mouse is over the clock

### ISSUE THREAD

**Issue by pols12** [lxqt/lxqt-panel#1313]
##### Expected Behavior
When the mouse enters over the panel clock button, it would be nice to display the full date as a tooltip, in the same manner the volume percentage is displayed when mouse is over volume button.

##### Current Behavior
Currently, there is no tooltip.

##### Possible Solution
Add a QWidget::setToolTip() call in LXQtWorldClock::updateTimeText(), in lxqtworldclock.cpp file.

##### Context
I think displaying the full date as a tooltip is a common behavior in other desktop environments (maybe in LXDE too?).
While working, planning organizing, it would be really useful to see the current date keeping the focus (do not need to click). 

##### System Information
* Distribution & Version: Debian 10
* Kernel: 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
* Qt Version: 5.11.3
* liblxqt Version: 0.14.1-1
* Package version: 0.14.1-1

**Comment by tsujan** [comment]
Only those widgets that can't show an info need tooltip. Worldclock doesn't.

**Comment by pols12** [comment]
Sorry, I’m not sure to understand: each widget could display any information permanently or with a tooltip. E.g. volume percentage is currently displayed as a tooltip, but it could be directly written just next to volume icon. It’s only a design choice, an ergonomics question.

According to me, it is not useful to display permanently the date because it changes only once a day.

There is no tooltip currently, you don’t need to choose between two useful info. I don’t see any advantage to don’t set any tooltip.

Finally, for external consistency (an ergonomics criterion) the behavior should be similar to other desktop environments.

Ideally, the tooltip content would be customizable of course, [as in LXDE](https://help.ubuntu.com/community/Lubuntu/Documentation/CustomizingTheClock).

**Comment by tsujan** [comment]
Closed in https://github.com/lxqt/lxqt-panel/commit/7dc55d868ef21c27ac582d294e5f64ee732226d8
