### ISSUE TITLE
"Do not disturb" mode for notifications

### ISSUE THREAD

**Issue by glpzzz** [lxqt/lxqt-panel#1320]
Notifications can be annoying. By default, the popups for lxqt notifications use the same font size than the rest of the environment and a lot of padding in the box. But this is graphic and perhaps can be themed.

But a "do not disturb" mode would be nice. When clicking on the tray icon, besides the clear all and options, have this options. Xfce launched something like this some years ago. 

The goal is to avoid notifications to appear. But still be registered on the notifications list.

**Comment by tsujan** [comment]
This was reported and rejected before because a "don't-disturb" notification doesn't make much sense (a notification should "notify", by definition), regardless of what other DEs may do. Moreover, notifications can be easily turned off in LXQt (→ Configuration Center).

I won't start yet another tedious discussion here. Clean patches are welcome.

**Comment by tsujan** [comment]
BTW, technically, notifications have nothing to do with Panel (this place is Panel's bug tracker). They're managed by `lxqt-notificationd`. But it's OK...

**Comment by glpzzz** [comment]
> Moreover, notifications can be easily turned off in LXQt (→ Configuration Center).

Mi suggestion is to have a easier access to this on the notifications icon on lxqt-panel. So, with is shortcut, there is no need to go to Configuration -> Notifications ...

PS. Forget about "do not disturb" mode. Turn on and off...

**Comment by tsujan** [comment]
Closing because lxqt-panel doesn't handle notifications.

**Comment by stefonarch** [comment]
Just to leave my 2 cents here:

> The goal is to avoid notifications to appear. But still be registered on the notifications list.

It would be enough toggle settings for ½ hour, 1 hour, 2hours  to 
* Duration: 0sec
* save last 10
This could be done by something similar to https://github.com/stefonarch/toggle-idleness-watcher and is related somehow also to https://github.com/lxqt/lxqt-powermanagement/pull/260

Only thing is that atm 0 sec isn't allowed, minimum is 1 sec.

**Comment by tsujan** [comment]
I closed it only because lxqt-panel had nothing to do with it. Feel free to make a feature request under https://github.com/lxqt/lxqt-notificationd/issues.
