### ISSUE TITLE
kb-indicator, layout country flag artefacts

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1321]
Testing the [basic implementation](https://github.com/lxqt/lxqt-panel/commit/86c2068052807820dfe3d6e529a1da742d050658) of the flags I can see 3 issues:

- on a vertical panel it's aligned to left, also if only text.
- the size is not defined, should be x% of width e/o height  I think, here I used just .png files of the desired size.
- using the mouse to change layout it makes "jump all the others, this doesn't happen with keyboard shortcut",  see the [screenrecord](https://contadinoste.ocloud.de/index.php/s/lqi1S4p90TBk8rS).

EDIT: looks like the second and third issue is only due to my .png files, so it's only the alignment left.

But the default size on a vertical panel looks to big, being this panel usually quite large the flag looks  huge among the other icons.

svg:
![schermata-08-18-59-15](https://user-images.githubusercontent.com/10681413/72003110-02d90580-3249-11ea-9be3-85a8c5c1c802.png)

png resized:
![schermata-08-19-01-09](https://user-images.githubusercontent.com/10681413/72003287-52b7cc80-3249-11ea-8066-c65f78303cef.png)

##### System Information

* Distribution & Version: git checkout; arch linux.

**Comment by palinek** [comment]
Please, test with #1322

**Comment by stefonarch** [comment]
The alignment works. 
But I encounter some weird behavior I have to investigate more:

- sometimes the "jumping" as in the screenrecord happens too with .svg files, but only if set to "application" or "window", not with "global".
- The switch using keyboard doesn't work if "global" is set, it always works using mouse on flag.
- Testing horizontal and vertical position it ended up with notswitch  working at all anymore, neither mouse nor keyboard, restarting panel didn't help.

**Comment by stefonarch** [comment]
Well, the expansion of the icon with mouse click on the  flag  is still an issue, but it's better to wait for full implementation I guess.

**Comment by stefonarch** [comment]
> Well, the expansion of the icon with mouse click on the flag is still an issue, but it's better to wait for full implementation I guess.

Just noticed that the "jumping" occurs also without any flag.
