### ISSUE TITLE
[Feature Request] Mouse scroll actions in taskbar

### ISSUE THREAD

**Issue by snailfart** [lxqt/lxqt-panel#1355]
I love the very comfortable ToggleIconify action in tint2 which allows you to iconify/restore windows through a mouse scroll and would love to see this feature implemented in the LxQt panel, too.
Some might as well find it convenient to mousebind scrolling to the "show desktop" button and workplace switcher.

Openbox itself offers contextual mousebinding and an iconify action, which can however productively only be usable in the titlebar and nothing to toggle the state.

**Comment by tsujan** [comment]
Already implemented. You might want to use the latest git.
