### ISSUE TITLE
Sign out button in main menu doesn't work

### ISSUE THREAD

**Issue by sirredbeard** [lxqt/lxqt-panel#1382]
![Annotation 2020-03-27 202436](https://user-images.githubusercontent.com/33820650/77810087-05d5dc00-7069-11ea-99e1-6a59f89f64fd.png)

##### Expected Behavior

Sign out button should exit LXQt and return to gdm3, lightdm, sddm, etc.

##### Current Behavior

Nothing happens.

##### Possible Solution

I am not sure how to debug this or where to check for logs, if you could point me in right direction I can gather those.

##### Steps to Reproduce (for bugs)

1. Install lubuntu-desktop on an Ubuntu 20.04 server image
2. Log in via gdm3
3. Click main menu button, power button, and then sign out button

##### Context

Sign out button should work.

##### System Information

Ubuntu 20.04 focal and focal-proposed

lxqt-panel:
  Installed: 0.14.1-1ubuntu3

**Comment by yan12125** [comment]
LXQt does not have a button "Sign out". It is called "Logout" here [1]. Most likely you are not running LXQt.

[1] https://github.com/lxqt/lxqt-session/blob/0.14.1/lxqt-leave/resources/lxqt-logout.desktop.in#L3
