### ISSUE TITLE
lxqt-panel 0.15.0 - regression - panel "Position" at "Bottom" of Desktop with multiple monitors

### ISSUE THREAD

**Issue by thx1111** [lxqt/lxqt-panel#1390]
Arch Linux
linux 5.6.8.arch1-1
qt5-base 5.14.2-1
liblxqt 0.15.0-2
lxqt-build-tools 0.7.0-1
lxqt-panel 0.15.0-1

"Configure Panel" - "Alignment & position" - "Position"

Regression - with three monitors, the drop-down list of position choices no longer includes "Bottom of Desktop 2" or "Bottom of Desktop 3".  As a consequence, it is no longer possible to place the panel in the desired position.  This is *very* annoying, of course.

I notice that it is also not possible to choose "Right of Desktop 2" or "Left of Desktop 3", though those might be unusual choices.  Still, removing configuration options is not doing anyone any favors.

The current work-around requires down-grading to lxqt-panel 0.14.1-2.

**Comment by tsujan** [comment]
The Panel isn't positioned inside the virtual screen anymore but only at its sides. This isn't a bug but the fix of a bug.

"Right of Desktop 2" and "Left of Desktop 3" are both inside the virtual screen. As for other positions, you need to be more specific. If the bottom of Desktop 1 is below the bottoms of 2 and 3 (even by only 1 px), the panel should not be positioned at the bottom of 2 and 3 but only 1.

**Comment by thx1111** [comment]
> As for other positions, you need to be more specific. If the bottom of Desktop 1 is below the bottoms of 2 and 3 (even by only 1 px), the panel should not be positioned at the bottom of 2 and 3 but only 1.

Then, to be more specific, first note that a "Desktop" corresponds to a "Monitor" or "Screen".  When the resolution of each screen is different, for instance, where one screen has a vertical resolution of 1024, and another screen has a vertical resolution of 1080, and supposing that that the screens are arranged "horizontally", and supposing that the "top" of each screen is at the *same* level, then, we note that 1080 is greater than 1024, and so, the *bottom* of the screen with vertical resolution 1080 is "below" the screen with a vertical resolution of 1024, and represents the "bottom" of the virtual display.

The problem is, the *user* does *not* want the panel to be located at the "bottom" of the virtual display, but instead, at the "bottom" of the screen with the lower vertical resolution - despite the rude "policy" being imposed upon the user by the developer.

The previous version of the application *did* provide the functionality desired by the user.  The more recent version of the application *fails* to provide the functionality desired by the user, and, by that definition, the new "policy" is a regression and a bug.

This idea of referencing the "virtual screen", instead of each screen in a multi-monitor configuration, is *not* appreciated - no matter that it may "work for you".  The multiple monitors do *not* simply "go away" when someone imagines a "virtual screen" composed of multiple monitors.  The several monitors are still there, with bezels around them, representing a "gap", dividing this fanciful "virtual screen".  The monitors are "right of" and "left of", and they are *not* "one big monitor".

The "virtual screen" concept does *not* solve "the problem", and instead, creates its own problems.

**Comment by tsujan** [comment]
> despite the rude "policy" being imposed upon the user by the developer

Read https://github.com/lxqt/lxqt/issues/1787#issuecomment-622035610 for the reason for "rudeness".

Sorry, I don't read long comments that don't seem to contain useful info. You could also search for reports of problems that were caused by the previous behavior.

**Comment by tsujan** [comment]
For reference:

https://github.com/lxqt/lxqt/issues/1703

https://github.com/lxqt/lxqt/issues/1704
