### ISSUE TITLE
Indicator for multiple of the same application open

### ISSUE THREAD

**Issue by drum445** [lxqt/lxqt-panel#1401]
**Expected Behavior**
When using icons only on the taskbar, there should be a visual indicator of how many of each application are running.

**Current Behavior**
There is no way to differentiate between applications with 1 instance and those with more.

**Possible Solution**
In Windows10 it stacks X amount of icons together, but a better solution for LXQt would be something similar to Cinnamon, where they show a small count when the applications open is > 1.

In the below example, pcmanfm has 2 instances open, but there is no way of knowing without hovering over the icon.

I've checked the CSS selectors and the only reference to groups is `LXQtGroupPopup` which isn't really what we want.

LXQt example:
![example](https://user-images.githubusercontent.com/37041178/81441391-983dc500-9169-11ea-89c2-94e45bdd58e3.jpg)

Cinnamon example:
![cin](https://user-images.githubusercontent.com/37041178/81441606-f8346b80-9169-11ea-9183-5307761685d7.png)

**Context**
This makes it more difficult to keep track of open apps than other panels.

**System Information**
Latest version of Lubuntu (LXQt: 0.14.1)

Thanks

**Comment by tsujan** [comment]
> but there is no way of knowing without hovering over the icon.

There's no value to knowing it before that. If it's vital to you to count windows, disable grouping.

**Comment by drum445** [comment]
@tsujan you seem to be speaking with authority on something that every other implementation would disagree with. I believe there is a value to knowing how many instances are open and I'm sure many others would also, seems a shame to push this feature aside.

Is there possibly a CSS selector I can use to change the colour or add a border perhaps?
