### ISSUE TITLE
plugin-colorpicker nothing to translate

### ISSUE THREAD

**Issue by milotype** [lxqt/lxqt-panel#1411]
It seems to me, that **colorpicker.ts** has nothing to translate.

Also, the Weblate-site for translations does not work **(this is true for other parts of lxqt)**.

**Comment by tsujan** [comment]
> It seems to me, that colorpicker.ts has nothing to translate.

Then, what's the problem?

> Also, the Weblate-site for translations does not work

Forget about Weblate (→ https://github.com/lxqt/lxqt.github.io/issues/41). You could use Qt Linguist and make PRs.

**Comment by milotype** [comment]
Thanks for the answer … I'm not a programmer, but i found it unusual, that thare is nothing to translate …
I know about Qt Linguist and PRs (I'm working on Croatian translations) … but I was hoping you'd actually use Webplate as a translation system :-( For translators, it's easier, than making PR's for each plugin/file …

**Comment by tsujan** [comment]
> I'm not a programmer, but i found it unusual, that thare is nothing to translate

Yes, rarely, some plug-ins may lack translatable strings.

> but I was hoping you'd actually use Webplate as a translation system

Unfortunately, because of what's mentioned in the above-mentioned link, Weblate is down indefinitely. We hope that translators remain active by making PR.
