### ISSUE TITLE
Quicklaunch: nonfunctional quicklauncher when there's a space in the filename/path

### ISSUE THREAD

**Issue by Thomas-N** [lxqt/lxqt-panel#1420]
Adding a quicklaunch button for a file with a space in the filename (or anywhere in the path), either by using drag-and-drop from pcmanfm-qt or by directly editing panel.conf results in a nonfunctional quicklaunch button.

##### Expected Behavior
Clicking the quicklaunch button should open the file (using the default program for that file), like it does for any quicklaunch application/file.

##### Current Behavior
Clicking the new quicklaunch button doesn't do anything at all.

##### Steps to Reproduce (for bugs)
1. Create a file (for example, any image or text file) with a space in the filename.
2. Drag-and-drop the file from pcmanfm-qt to the quicklauncher on the panel.
3. Observe that a quicklaunch button is created, as expected.
4. Click the new button -> nothing happens.

##### Context
This issue was originally posted on the [Lubuntu forums](https://discourse.lubuntu.me/t/20-04-some-fast-launchers-doesnt-work-or-launch-anything/1281).

##### System Information
Lubuntu 20.04 (lxqt 0.14). Reading through the changes to lxqt-panel since then seems to indicate that the issue hasn't already been fixed (or reported), so it is most likely still present in the most recent version.

**Comment by tsujan** [comment]
Not reproducible with the latest LXQt; tested with spaces in both file name and file path.
