### ISSUE TITLE
Questions about Status Notifier's auto-hiding

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#1426]
The new (auto-)hiding feature of the Status Notifier plugin of LXQt panel (in git) has a button for showing all items. Let's call it "the show button."

 1. The show button is positioned at the start of the layout and takes a space as small as other items but that may be too much. I couldn't find a good way of making it smaller and, at the same time, well-aligned and easily clickable.  To me, the problem is that, with only one hidden item, the show button doesn't save space.
 
 2. I chose `dialog-information` as the show button icon but you may have a better suggestion. IMO, an arrow icon may have a problem because the panel may be at the left/right too and, if we use different arrow icons for those positions, we'll invite the extra hassle of changing it every time the panel position is changed by the user.

If you have suggestions about 1 or 2, please tell us. It isn't important how hard their implementation might be but, IMHO, their frugality and resource-friendliness is important.

**Comment by stefonarch** [comment]
Cool!
While testing I got confused: to scroll down the item list I used the mousewheel but this toggles the setting of the item under the cursor. Maybe better using only the dropdown  button?

For 2) not sure if this exist but a show more + or less - sign? I was first thinking about the notifier when seeing the information symbol.
Or the  three-point or lines symbolused  for settings? View-more.svg is that.

**Comment by tsujan** [comment]
> View-more.svg is that, other option could be expand or expand-all

`view-more` icons are rather in GTK icon sets (Breeze has `view-more-symbolic` and its horizontal counterpart for use with GTK apps). `expand` icons are specific to KDE.

> For 2) not sure if this exist but a show more + or less - sign?

`+` looks like a good idea to me. With it, we can use text instead of icon.

Actually, before I start the code, I was thinking about unicode characters `⋮` and `…` (yes, orientation should be considered with them) but I wasn't sure that all fonts included them.

The advantage of characters is that they're visible on light and dark panels alike. `+` is a good option.

**Comment by tsujan** [comment]
Also, it's better to hide the show button when it's clicked (because it has no job then) and show it again when items are made hidden again (2 seconds after the mouse cursor leaves the widget).

With the above property and `+` as the text (if everyone agrees with `+`), the plugin will look better, IMO.

The only problem that remains is the size of the show button. The size is OK when more than 1 row is chosen in Panel's settings but it seems too big to me with one row (the default).

**Comment by tsujan** [comment]
Used the plus sign in https://github.com/lxqt/lxqt-panel/pull/1427 and made some enhancements (like hiding the button after clicking it):

![show_btn](https://user-images.githubusercontent.com/981076/85245868-322da880-b45e-11ea-9f59-3a4e857e7d71.gif)

I think the plus sign is much better.
