### ISSUE TITLE
 plugin-statusnotifier in ubuntu2004

### ISSUE THREAD

**Issue by hepuyao** [lxqt/lxqt-panel#1433]
why i can't use lxqt-panel  in ubuntu2004
tray apps can't show in plugin-statusnotifier  area 

Switch desktop environment  to lxqt  ,it 's normal

**Comment by tsujan** [comment]
Please ask Ubuntu questions from Ubuntu. We aren't responsible for Ubuntu.

**Comment by hepuyao** [comment]
I want to ask that run plugin-statusnotifier need other&nbsp;background program such as&nbsp;lxqt-notificationd？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tsujan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 晚上7:37
收件人:&nbsp;"lxqt/lxqt-panel"<lxqt-panel@noreply.github.com&gt;;
抄送:&nbsp;"何朴尧"<2410474020@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lxqt/lxqt-panel]  plugin-statusnotifier in ubuntu2004 (#1433)





 
Please ask Ubuntu questions from Ubuntu. We aren't responsible for Ubuntu.

**Comment by tsujan** [comment]
No. The Status Notifier plugin is the new system tray protocol; the old one is deprecated but can be added besides it.

You need all `libappindicator` packages. I don't know their names in Ubuntu; that's one reason -- among other things -- that you may need to ask these question in Ubuntu forums.

**Comment by hepuyao** [comment]
thankyou！  I will tray to ask in Ubuntu forums.

**Comment by hepuyao** [comment]
thankyou! I will ask in&nbsp; Ubuntu forums.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lxqt/lxqt-panel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 晚上8:15
收件人:&nbsp;"lxqt/lxqt-panel"<lxqt-panel@noreply.github.com&gt;;
抄送:&nbsp;"何朴尧"<2410474020@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lxqt/lxqt-panel]  plugin-statusnotifier in ubuntu2004 (#1433)





 
No. The Status Notifier plugin is the new system tray protocol; the old one is deprecated but can be added besides it.
 
You need all libappindicator packages. I don't know their names in Ubuntu; that's one reason -- among other things -- that you may need to ask these question in Ubuntu forums.
