### ISSUE TITLE
Menu not dropping icon to quickstarter in panel.

### ISSUE THREAD

**Issue by ringo32** [lxqt/lxqt-panel#1434]
Lxqt 0.15 i cannot take a icon of application to the quickstart in the lxqt-panel.

if i do  the computer icon on desktop it goes not from menu. 

##### Expected Behavior

i can drop example chromium to the quickstart applet in lxqt-panel, but it wont let me.

##### Current Behavior

only does from desktop not from menu anymore

cannot from menu tried to use another theme but wont happend.

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* lxqt-build-tools Version: 
* Package version: 

local/liblxqt 0.15.1-1
    Common base library for LXQt components
same as the lxqt-panel

endeavouros based on arch-linux.

local/qt5-base 5.15.0-4 (qt qt5)

hope its enough :)

**Comment by tsujan** [comment]
It's a bug in Qt 5.15. We have a workaround but prefer to wait until it's fixed in Qt. See https://github.com/lxqt/lxqt/issues/1821#issuecomment-653643685
