### ISSUE TITLE
plugin-tray

### ISSUE THREAD

**Issue by hepuyao** [lxqt/lxqt-panel#1437]
Excuse me, for some reason, I want to use plugin-tray on lxqt-panel, but if trayIcon is not set in the tray app, how can I change the plugin-tray to use the default icon replacement?     In  TrayIcon::draw(QPaintEvent* )?

**Comment by tsujan** [comment]
Pragmatically? Yes, `TrayIcon::draw` is the method. As a user? The tray plugin doesn't have any setting for that.

As you may know. the tray plugin is obsolete.
