### ISSUE TITLE
World clock HTML

### ISSUE THREAD

**Issue by Bydo-Spore** [lxqt/lxqt-panel#1438]
In World Clock manual formatting, if there are no text formatting tags such as bold or underline, no other HTML tags work and the text is interpreted as plain text. For example, if there are formatting tags, a double space requires HTML code, but if there are no formatting tags a double space is directly interpreted. Is this intentional behaviour, because it seems inconsistent?

It means, for example, that it is not possible to remove the 'bold' tags while varying the text colour or size.

**Comment by tsujan** [comment]
> Is this intentional behaviour, because it seems inconsistent?

→ https://doc.qt.io/qt-5/qlabel.html#text-prop

**Comment by Bydo-Spore** [comment]
Ok, thanks. But how is it possible to have coloured text without enclosing the whole string with bold or italic, etc.? When bold tags are removed all of the text is interpreted literally, including text colour, font, etc.

**Comment by tsujan** [comment]
> When bold tags are removed all of the text is interpreted literally, including text colour, font, etc.

Not true. Example:
```html
'<font color=red>'hh:'<font color=blue>'mm:'<font color=green>'ss '<font color=yellow>'a
```
Read "Supported HTML Subset" in the link I added.
