### ISSUE TITLE
World Clock: Remove the incorrect explanation about `z` and `zzz`.

### ISSUE THREAD

**Issue by Bydo-Spore** [lxqt/lxqt-panel#1439]
'z' and 'zzz' show the number of milliseconds in 1 second intervals, but the update interval is always 1 second.

If I add 'z' or 'zzz' to the string, the result is that either '003' or '004' is displayed constantly. What use is this?

What I really don't understand is that you evidently know this because you've written it on the bottom of the window.

An additional problem: 'z' is meant to show the number of milliseconds without leading zeroes. Actually it has exactly the same effect as 'zzz' (i.e. it does have leading zeroes).

**Comment by tsujan** [comment]
An update interval of one millisecond would be CPU-intensive and isn't supported.

 > An additional problem: 'z' is meant to show the number of milliseconds without leading zeroes

Wrong. Read the `QTime` doc with more attention to details.

Anyway, even if `z` meant the number of milliseconds without *leading* zeroes -- which isn't the case -- it would be useless with the World Clock for the above-mentioned reason. It's there just because Qt supports it.

**Comment by tsujan** [comment]
Reopening because the explanation inside the World Clock widget is wrong.

> What I really don't understand is that you evidently know this because you've written it on the bottom of the window.

No LXQt component has a single developer. One developer may make a mistake and another obe may correct it.

**Comment by tsujan** [comment]
Will be fixed by https://github.com/lxqt/lxqt-panel/pull/1440 (which removes the milliseconds part of the explanation).

**Comment by Bydo-Spore** [comment]
> It's there just because Qt supports it.
What!? You include something that doesn't work in the guide just because Qt supports it, rather than simply omit it from the guide?

> Wrong. Read the QTime doc with more attention to details.
Wrong. In the guide written in the configuration window, it says that 'z' shows the number of milliseconds without any leading zeroes, but in practice, it does have leading zeroes. I wasn't refering to the QTime doc, and there's no reason to assume I was.

**Comment by tsujan** [comment]
> What!? You include something.... Wrong. In the guide written in the configuration window, it says...

You seem to have a habit of not reading things...

**Comment by luis-pereira** [comment]
> An update interval of one millisecond would be CPU-intensive and isn't supported.

Even if it wasn't... It's too intensive for the user.
