### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by QuImUfu** [lxqt/lxqt-panel#1449]
##### Expected Behavior
lxqt-panels memory usage should not increase a lot.

##### Current Behavior
After 2 weeks, 3 days it currently is 758M RES, 230 SHR in htop. The PC idled for ~a week, before the memory usage was AFAIK normal (max 40M). Not sure if slowly growing or it grew quickly at some point during this week.

##### Reproducing
No idea. This does not seem to happen every time and i have no idea what triggers it.  
If this is not debugable/fixable with the provided information, feel free to close this issue. :D

##### Additional Data
A core dump recorded with gcore:  
https://dl.dropbox.com/s/donhfslg9i6460f/lxqt-panel.core.tar.xz

##### System Information
* Distribution & Version: Ubuntu 20.04.1 LTS
* Kernel: Linux 5.6.15-050615-generic
* Qt Version: libqt5core5a package - version is 5.12.8+dfsg-0ubuntu1
* liblxqt Version: liblxqt0 package - version is 0.14.1-0ubuntu2
* lxqt-build-tools Version: none - not installed
* Package version: lxqt-panel package - version is 0.14.1-1ubuntu3

**Comment by tsujan** [comment]
Memory leak is an important problem and your report is appreciated but:

 * 0.14 is outdated.
 * A memory leak is different from a crash. It doesn't have a coredump.
 * Consult your distro documentation on how to find a backtrace. The coredump is useless by itself.

Please add a comment here if the same thing happens with the latest release; then this issue will be reopened.

**Comment by QuImUfu** [comment]
i know that a memory leak isn't a crash, but there seem to be tools to analyze coredumps on memory usage (e.g. https://github.com/yanqi27/core_analyzer (i could not get that program to run, otherwise I'd have tried to investigate further myself)).  
That is why i generated one with gcore on the running program. :D  
I do not think a backtrace would show anything interesting, as the program is running just fine.  
I understand that you can't support outdated versions, i apologize for the noise and thanks for the quick response. :D

**Comment by tsujan** [comment]
valgrind is the best tool for finding memory leaks but lxqt-panel 0.14 is very old. I used valgrind with lxqt-panel months ago and didn't find a leak. Will do it again if I find the time.

**Comment by tsujan** [comment]
I did a short test with valgrind and couldn't find a memory leak in lxqt-panel. It doesn't prove 100% that there is no leak but is a good indication.
