### ISSUE TITLE
[Feature request] Highlight icon In task manager when for example receiving a new steam massage

### ISSUE THREAD

**Issue by funghetto** [lxqt/lxqt-panel#1469]
On windows or KDE when I receive a massage on steam or something happens in an app, the space in the task manager for that application changes color so I know that something new happened, this doesn't happen in LxQt.

Would it be possible to have this behavior here too?

**Comment by tsujan** [comment]
LXQt Panel (task button) already supports `NET::DemandsAttention` and all LXQt themes cover it: when a window needs attention but the WM's "focus stealing prevention" doesn't let it get attention, its task button will change color, depending on the theme.

**Comment by funghetto** [comment]
So you are suggesting this is a openbox issue?

**Comment by tsujan** [comment]
That's possible, in case Openbox can't handle it. Here, with KWin, I rely on the property in question and it always works fine.

**Comment by tsujan** [comment]
I found some time to compare 3 WMs in addition to KWin, namely, compiz-reloaded, xfwm4 and openbox. Only openbox didn't respect `NET::DemandsAttention` (xfwm4 worked well as soon as I disabled changing of virtual desktop on needing attention — don't remember the exact words).

So, yes, the problem should be in Openbox.
