### ISSUE TITLE
shortcut for main menu: wrong position of main menu when panel is in auto-hide

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-panel#1483]
when the panel is in auto-hide,  using the shortcut for the main menu will let appear the main menu and the panel;
the problem: main menu is not above the panel, like it should be, but over the panel, so a part of the panel is not visible

##### Expected Behavior
main menu should be above the panel

##### Current Behavior
main menu is over the panel, so a part of the panel is not visible

##### Possible Solution
I think the issue is because of the orders of fire; I think that at the moment it is like this:
first the main menu is fired, then the panel is fired;
so a possible solution could be:
IF-request BEFORE the fire of the main menu, so something like this:
if panel is hidden then fire the panel; afterwards fire the main menu

##### Steps to Reproduce (for bugs)
1: put the panel in auto-hide
2: press the windows-key to let appear the main menu

##### System Information
* Distribution & Version: Lubuntu 20.10
* Qt Version: 0.15.0

**Comment by stefonarch** [comment]
Confirming:
![schermata-22-22-13-07](https://user-images.githubusercontent.com/10681413/99917385-26e1f000-2d10-11eb-94ee-ea396a6c84a0.png)

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lxqt-panel/pull/1484
