### ISSUE TITLE
LXQt-settings should be in the main menu, and not in a sub-folder of the main menu

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-panel#1485]
LXQt-settings are at the moment in a sub-folder of settings;
it would be better to put them in the main menu to offer a better user experience

##### Expected Behavior
LXQt-settings should be in the main menu, so below or above the settings

##### Current Behavior
LXQt-settings are in a sub-folder of settings

##### Possible Solution
put LXQt-settings in the main menu, below or above the settings; best solution:
replace "About LXQt-settings" by "LXQt-settings";
if "About LXQt-settings" is really necessary, then put it in the sub-folder of "LXQt-settings" (maybe at the end of the list, so it is falling apart; one could use a kind of line before, so it is not ordered in the alphabetical list), because
a) that is where it belongs, and
b) users don't use this information often

one more point:
instead of the name "LXQt-system-settings" (or something like this; I don't use the English version), I suggest as name only "LXQt-settings"; it is shorter, smarter and better

##### Steps to Reproduce (for bugs)
let appear the main menu

##### Context
sub-sub-folder are making things complicated and I don't see any reason to use a sub-sub-folder in the main menu

if LXQt-settings are in the main menu,
1) there is a faster access to the LXQt-settings,
2) there would be no sub-sub-folder at all, and
3) the main menu would offer a better user experience

one more point:
when the symbol for the main menu is placed on the right side of the panel, just right after the taskbar, then there is enough place on the right side for showing main menu and the sub-folder, but not enough place for the sub-sub-folder

##### System Information
* Distribution & Version: Lubuntu 20.10
* LXQt Version: 0.15.0

**Comment by tsujan** [comment]
Simply wrong.

@ralf3u, please read https://github.com/lxqt/pcmanfm-qt/issues/1250#issuecomment-732788866 and don't open a report about everything that comes to your mind!
