### ISSUE TITLE
Separator in menus is invisible with "Dark" theme

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1493]
As title, noticed only  today but it's like that since 0.14.1 or older.

##### Expected Behavior

![schermata-30-19-21-17](https://user-images.githubusercontent.com/10681413/100648452-3df09580-3341-11eb-9915-4341340215f2.png)

##### Current Behavior

![schermata-30-19-11-04](https://user-images.githubusercontent.com/10681413/100648360-20bbc700-3341-11eb-913e-bcfb52aa0ed7.png)

##### Possible Solution
Make a PR.
 
Edit: this is true also for "Leech" theme, but only in the main menu, with dark background.

**Comment by tsujan** [comment]
It's quite valid not to draw menu separators and just give them a small vertical space. For example, although Kvantum supports them, I haven't included any in most Kvantum themes — to me, they're ugly. Or many GTK themes don't draw them.

However, I have no problem with adding them to this LXQt theme.

**Comment by stefonarch** [comment]
I noticed it in the main menu (which I use very rarely, using always the runner or shortkeys), there it's nice to have separators visible IMHO. But will make the line a  bit darker.

**Comment by tsujan** [comment]
Tastes can differ amazingly. I've seen many examples of someone loving something and another one hating it.

I suggest making it withe and giving it a high degree of translucency, like rgba(255, 255, 255, 20%), or even lower.

**Comment by stefonarch** [comment]
> Tastes can differ amazingly

well, your proposal and my PR now doesn't differ a lot ;)

![schermata-30-22-03-20](https://user-images.githubusercontent.com/10681413/100664489-f75a6580-3357-11eb-9dc2-9625e4e525d3.png)
![schermata-30-22-01-06](https://user-images.githubusercontent.com/10681413/100664494-fa555600-3357-11eb-854b-3e016bf34e4a.png)

**Comment by tsujan** [comment]
OK. I think it should be acceptable to all tastes, more or less. I suggested translucency because the menu itself was translucent.

You have my "GTM".

**Comment by stefonarch** [comment]
For commits like this "rebase and merge" is the choice?

**Comment by tsujan** [comment]
"Squash and merge" works everywhere, for single-commit PRs too.
