### ISSUE TITLE
"Un/Decorate" should be part of the context menu of an opened window in the panel

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-panel#1495]
in the window menu there is the possibility to choose "Un/Decorate";
this does not exit in the context menu of an opened window in the panel

##### Expected Behavior
"Un/Decorate" as part of the context menu of an opened window in the panel

##### Current Behavior
"Un/Decorate" does not exist in the context menu of a opened window in the panel

##### Possible Solution
the content of the context menu of an opened window in the panel should be <b>exactly</b> like the content of the window menu

##### Steps to Reproduce (for bugs)
in the panel: right-click on an opened window

##### Context
example why "Un/Decorate" should be part of the context menu of an opened window in the panel:
a user goes in the window menu and chooses "Un/Decorate" to hide the title-bar;
then the user wants again to see the title-bar;
if the user don't know the shortcut Alt+space (for the window menu), there is at the moment no possibility to bring back the title-bar as long as the window is opened

##### System Information
* Distribution & Version: Lubuntu 20.10
* Qt Version: 0.15.0

**Comment by tsujan** [comment]
"an opened window in the panel" doesn't make sense in any language.

The title-bar is created by WM, not by LXQt.

**Comment by ralf3u** [comment]
my reaction to the last comment:
I changed the title and the content of this issue from 'opened window' to 'open window'
(this is the best proof why one should not use only one translation-software, like I did, but different translation-software, before uploading content)

**Comment by ralf3u** [comment]
@tsujan

>The title-bar is created by WM, not by LXQt.

sorry, but I don't understand your argumentation; "Maximize" is also created by WM,  nethertheless "Maximize" stands in the context menu of the taskbar, but not "Un/Decorate"

**Comment by tsujan** [comment]
> sorry, but I don't understand your argumentation

Things to study: DE, WM, KWindowSystem.
