### ISSUE TITLE
minor translation issue desktopswitching config menu

### ISSUE THREAD

**Issue by mkkDr2010** [lxqt/lxqt-panel#1498]
Desktop label in the field of configuration menu of desktopswitching is not trasnslated.
See image
![screen-3](https://user-images.githubusercontent.com/75447241/101276034-68f84080-37aa-11eb-860e-41ad548a10de.jpg)
Not of big concerns, but perhaps missing  translation function in desktopswitchconfiguration.cpp.

**Comment by palinek** [comment]
Fix in #1500
