### ISSUE TITLE
problem building panel

### ISSUE THREAD

**Issue by mkkDr2010** [lxqt/lxqt-panel#1501]
I have just installed new archlinux system with lxqt desktop. Then I successfully build the libfm-qt and now I am trying to build the panel. But here came a problem with configure. Cmake ends with error for all panel widget:

CMake Error at /usr/share/cmake/lxqt-build-tools/modules/LXQtTranslateDesktop.cmake:62 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  cmake/BuildPlugin.cmake:24 (lxqt_translate_desktop)
  plugin-backlight/CMakeLists.txt:17 (BUILD_LXQT_PLUGIN)

What am I doing wrong, which dependencies are not met?

**Comment by tsujan** [comment]
You need the latest git lxqt-build-tools.

In general, when you upgrade to a git package, you first need to upgrade all its dependencies

**Comment by mkkDr2010** [comment]
Fixed. Thank you!

**Comment by stefonarch** [comment]
https://github.com/lxqt/lxqt/wiki/Building-from-source#generalbuild-order
