### ISSUE TITLE
[Feature Request] Task Manager - Open new windows on middle-click

### ISSUE THREAD

**Issue by waenhill** [lxqt/lxqt-panel#1510]
Hello,
I would like to summit an idea for the Task Manager widget.
Could it be possible to add an option to open a new window on the middle-click?

The option to close on middle-click is available; but coming form Windows, I am used to use that shortcut to open a new one instead :)

Please let me know your comment.
Thanks you in advance!

**Comment by tsujan** [comment]
LXQt]has a ["Discussions" section](https://github.com/lxqt/lxqt/discussions), which you could use for questions or ideas. But the answer is no. Opening a new window doesn't make sense for all apps, while closing a window does.

**Comment by ito32bit** [comment]
@tsujan Can you click `Convert to discussion`?
Ref: https://docs.github.com/en/free-pro-team@latest/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion

**Comment by tsujan** [comment]
> @tsujan Can you click Convert to discussion?

Sorry, I was busy but @waenhill opened a discussion for it.

@ito32bit, thanks for telling about "Convert to discussion". It'll be useful in future.
