### ISSUE TITLE
[Feature Request] World Clock - Display time zones in tooltip

### ISSUE THREAD

**Issue by waenhill** [lxqt/lxqt-panel#1511]
Hello,
I would like to summit an idea for the World clock widget.
I have added several time zones in the tab "Time zones" of that widget, but to be honest I don't understant how it is used...
I can only see my default time zone.

There is an option to display a tooltip on the widget, but it is giving only my default date and time.
So could it be feasable to display all time zones (Custom names if available otherwise IANA id) in the tooltip of the widget?

For instance with two Time zones:
```
India: 11/12/2020 14:30
France: 11/12/2020 10:00
```

Please let me know your comment.
Thanks you in advance!

**Comment by tsujan** [comment]
If you have a question or an idea → https://github.com/lxqt/lxqt/discussions
