### ISSUE TITLE
Auto-hiding: an option to show panel when there is no window overlap

### ISSUE THREAD

**Issue by MarKre72** [lxqt/lxqt-panel#1515]
### **Panel Show/Hide Function**

There is a possibility in LXQT to hide the Panel automatically. This is a great feature if you want to surf the web with the browser or edit a photo in Gimp, for example. 

When all windows are closed and you look at the desktop, it would be an advantage to have the Panel automatically visible again. This would have a visual effect, but you could also access your favorite programs quickly this way.

In short, when windows are open in full screen mode (Firefox, Gimp, etc.), the Panel is automatically hidden. When all fullscreen windows are closed, the Panel is automatically (always) visible.

[<a href="https://ibb.co/RBc43xk"><img src="https://i.ibb.co/RBc43xk/screenshot-ffc5b18b.jpg" alt="screenshot-ffc5b18b" border="0"></a>] Show bottom Panel when no window is open. Hide when windows are open in full screen

##### System Information

* Distribution & Version: Lubuntu 20.10
* Kernel: 5.8.0-33-generic
* Qt Version: 5
* liblxqt Version: 0.15.0ubuntu1
* lxqt-build-tools Version: 0.7.0-0ubuntu1
* Package version: 0.15

**Comment by tsujan** [comment]
Which bar?! I don't get what you're talking about.

**Comment by MarKre72** [comment]
Sorry, I meant the panel ...

**Comment by tsujan** [comment]
This is a special case of a more general idea (I think we had a report about it somewhere): an option to show an auto-hiding panel whenever it doesn't overlap any window.

I like the above-mentioned idea but I'm not sure it's worth an implementation because, although it seems simple, it may require lots of code. That being said, I'll think about it if I find the time (which may not happen soon).

**Comment by tsujan** [comment]
I succeeded in implementing it by using 4 `KWindowSystem` signals. The auto-hiding panel hides when there's a window overlap and shows up when there's none — the overlap or lack of it may happen because the desktop is changed, a window is added/removed or a window is resized/moved.

The amount of extra code is acceptable to me but other devs might have a different opinion when I make the PR.

Since I wrote the code only for testing (didn't add an option for it and there may be bugs), it might take a while before I clean it up and make a PR.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/lxqt-panel/pull/1518

The new option:

![hide_on_overlap](https://user-images.githubusercontent.com/981076/102687248-ebe5b600-4202-11eb-95eb-55d067db11e5.png)

**Comment by stefonarch** [comment]
Works fine and cool feature on small displays!
 But it doesn't make sense check both "hide on overlapping" and "reserve space", the latter could   be disabled if the first is selected no? Otherwise you can move a window over the panel and it hides but it doesn't  hide maximizing the window.

**Comment by MarKre72** [comment]
Great work!!! Is it possible to get the customized file to test?

**Comment by stefonarch** [comment]
You'd have to compile and install at least the base group and then compile the lxqt-panel/autohide-overlap  branch.
https://github.com/lxqt/lxqt/wiki/Building-from-source

**Comment by MarKre72** [comment]
Oh dear, I think that's too complicated for me. I look forward to the option hopefully in the upcoming version. Did you do really great !!!

**Comment by tsujan** [comment]
> But it doesn't make sense check both "hide on overlapping" and "reserve space"

It isn't related to the PR and, yes, I also think it's weird. But it isn't a bug.

**Comment by tsujan** [comment]
@stefonarch 
With which WM did you test it? I have KWin here and it works fine. Does it work OK with Openbox too? Theoretically it should but I ask because Openbox is very old.

**Comment by MarKre72** [comment]
I would also like to know if openbox is suitable for this patch. Lubuntu runs by default with openbox. and it runs very well!

**Comment by stefonarch** [comment]
Openbox here, no issue. But maybe test it with xfwm4 too as it's used as default in some distros.

**Comment by tsujan** [comment]
@stefonarch, thanks!

We use KWindowSystem in lxqt-panel. The patch is also made by using it. So, all WMs should be covered. I asked about  Openbox only because it isn't developed anymore. xfwm4 is more active.

**Comment by stefonarch** [comment]
Just tested with xfwm4, working too.

**Comment by tsujan** [comment]
BTW, I checked "reserve space". It has no effect on auto-hiding panels, as it shouldn't. So, it doesn't affect hiding on overlapping either.

Later and in another PR, I'll change its place and make it disabled when auto-hiding is enabled.

**Comment by MarKre72** [comment]
Hello tsujan,
with which version will your change to the panel be published to users. Currently LXQT 0.15 is the latest version. I ask because Debian/Ubuntu always take "a few minutes" longer than Arch, for example...

**Comment by tsujan** [comment]
> with which version will your change to the panel be published to users

0.17, which will be released in April, 2021 if everything goes well.

> Currently LXQT 0.15 is the latest version

The latest version is 0.16.

**Comment by MarKre72** [comment]
Oh sure, the last version is V. 016... So version 0.17 will be released with Lubuntu 21.04?

**Comment by tsujan** [comment]
LXQt has no special relation with Lubuntu or any other distro but yes, our releases happen in April and November.

I guess Ubuntu will be in the sate of "freeze" before 0.17; so, 0,17 might not be in Lubuntu 21.04. You may want to ask Lubuntu about that.

**Comment by MarKre72** [comment]
In the Lubuntu forum it was announced that the Debian maintainer for LXQT has practically disappeared and it is not possible to say what will happen next. Also not a single updated LXQT package has been released in the last months...

**Comment by tsujan** [comment]
LXQt isn't responsible for any distro. What happens downstream is distro maintainers' job -- or no job, in the case of Debian.

**Comment by MarKre72** [comment]
What kind of substructure are you using? Although I like to call the desktop of Lubuntu of all (Manjaro, ArcoLinux, openSUSE, Mageia) as if from a single mold.

**Comment by tsujan** [comment]
It makes no difference for me because I make the LXQt packages that I use.

To have the latest LXQt, you need a rolling distro (other than Debian, of course). I prefer not to recommend any here because this is an issue page, not a place to discuss about distros.
