### ISSUE TITLE
2 mistakes in Qlipper

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-panel#1522]
there are two mistakes in Qlipper

mistake 1:
when panel is in auto-hide the list of Qlipper has the wrong position:
instead of being above the panel, it is behind the panel;
by the way: the context menu of Qlipper is above the panel, so this works fine

because Qlipper is part of the widget "Status Notifier Plugin", nearly the same issue exists for notifications and connections: instead of being above the panel, it is in front of the panel; this mistake has some similarity with issue #1483

------

mistake 2:
if no entry of the list will be selected, the list of Qlipper does not want to go away as long as Qlipper will be clicked again

example that other tools work different: you can see it better when the desktop is visible:
click on the panel on the connections or on the notifications: the list will appear; then click somewhere else, like for example on the desktop: the list will disappear; you will find the same behavior for the clock on the panel

example that mistake number 2 creates confusion:
open LibreOffice and maximize the window, then click on Qlipper: the list of Qlipper appears; now click in LibreOffice: the list of Qlipper seems to have disappeared; but in fact the list is still there, behind LibreOffice; so now, if I click on Qlipper to see the list, the list will not appear (because it will disappear), so I have to click Qlipper again to let appear the list

if it is the intention that the list of Qlipper should stay, as long as Qlipper is not clicked again or until an entry is selected, then maybe it would be good to offer an option in its settings, maybe a checkbox with this kind of text:
"the list of Qlipper stays until Qlipper will be clicked again or until an entry is selected"
I suggest the checkbox should be unchecked by default

##### System Information
* Distribution & Version: Lubuntu 20.10
* Qt Version: 0.15.0

**Comment by stefonarch** [comment]
1) the menu appears where the cursor is, better invoke qlipper by its shortcut
2) qlipper is not part of LXQt. And if you don't select an item don't open it.

**Comment by ralf3u** [comment]
But there are still some issues when panel is in auto-hide in Lubuntu 21.04:
- in the panel: left click on notifications: list is not above the panel like it should be, but in front of the panel AND the panel will disappear although the list is still there
- in the panel: left click on network: list is not above the panel like it should be, but in front of the panel AND the panel will disappear although the list is still there
- when the widget "System Statistics" is in the panel: when panel is in auto-hide and not visible, the record will stop and the curve will be deleted; maybe it would be good to offer in the "System Statistics Settings" a checkbox, with a text with something like: "record even when panel is invisible in auto-hide"
- in "Configure Panel", in "Panel" there is the possibility to activate or deactivate "Visible thin margin for hidden panel", but I don't see any difference between activating or deactivating; in both cases there is a thin margin

my LXQt 0.16.0 is old, but I still don’t know how to install the latest version;
if the issues do not appear in 0.17.1 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
Only the 3rd one is reproducible and it needs a separate report (mixed reports aren't accepted). The widget is updated only when it's shown and that's correct. Whether a workaround could be added or not, I'm not sure.

For the 4th one, compositing is needed.

**Comment by ralf3u** [comment]
> The widget is updated only when it's shown and that's correct.

somehow that's not true, because when panel is not in auto-hide, so always visible, and when I open Firefox in full screen, then the widget is not shown any more, but it still continues to record

>  ... it needs a separate report ...

I will open a new report tomorrow

> For the 4th one, compositing is needed.

I'm sorry, I don't understand what you mean. Do you want I make two screenshots, one activated and one deactivated?

**Comment by tsujan** [comment]
> when I open Firefox in full screen, then the widget is not shown any more

Not to *you*. Widget's visibility is a programmatic concept; a visible widget may be "hidden" behind a window and yet it's considered as "shown".

> I don't understand what you mean

Compositing = a working compositor.

> Do you want I make two screenshots

Not needed.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lxqt-panel/issues/1614

**Comment by ralf3u** [comment]
I have a big problem with the speaker-symbol in the panel.
I use now a bare-bone-PC with external speakers connected with USB and audio jack.
After every reboot there is no sound. For having sound, this is what I have to do after every reboot:

click on the speaker-symbol in the panel; click on “Mixer”; click in the tabs on “Configuration”;
click 2 times (to deactivate and to activate) the checkbox in the “Built-in Audio” “Profile” (Analog Stereo Output)

Is there a bug in the mixer?

**Comment by ralf3u** [comment]
I’m sorry, I don’t understand.
If I uncheck "Visible thin margin for hidden panel" there is still a thin margin what you can see in the picture down below.
Your answer was: "compositing is needed" and "Compositing = a working compositor." I googled it but I still don’t know what you mean.
![2021-05-04_deepl com](https://user-images.githubusercontent.com/68117017/117021481-ae884d80-acf7-11eb-8566-bd3fd02886bf.jpg)

**Comment by tsujan** [comment]
https://en.wikipedia.org/wiki/Compositing_window_manager
