### ISSUE TITLE
Icons of apps discontinue being displayed after teams/skype launched

### ISSUE THREAD

**Issue by nickson99** [lxqt/lxqt-panel#1547]
After Team/Skype starts, I have noticed apps i open are not shown on task manager which causes confusion.

##### Expected Behavior

Open Apps' Icon is displayed on task manager so long the app remains opened and ceases to be displayed when app is closed.

##### Current Behavior

App Icon is not displayed when the app is opened.

##### Possible Solution

I found that performing the following resolves the issue temporarily
1) Right Click on task manager of panel.Go to _Configure "Task Manager"_. Task Manager Settings window opens.
2)Uncheck and Check "Show only windows from <desktop>"
3)Icons that were not displayed appear.

##### Steps to Reproduce (for bugs)

1. Set teams/skype to auto start on startup
2. On Start up let the skype and Teams render.Close them on render i.e, minimize to tray.
3. Open an App (E.g Geany,Dolphin,PCMan)

##### Context

This bugs results in opening an app multiple times.Resulting in productivity degradation.

##### System Information

* Distribution & Version: Ubuntu 18.04 with lxqt
 -------------- 
OS: Ubuntu 18.04.5 LTS x86_64 
Host: TECRA R840 PT42FG-005005 
Kernel: 5.10.0-5.1-liquorix-amd64 
Uptime: 39 mins 
Packages: 3842 
Shell: bash 4.4.20 
Resolution: 1366x768 
DE: LXQt 
WM: Sawfish 
WM Theme: winter 
Theme: Ambiance [GTK2/3] 
Icons: McMojave-circle [GTK2/3] 
Terminal: qterminal 
CPU: Intel i3-2310M (4) @ 2.100GHz 
GPU: Intel HD Graphics 3000 
Memory: 2696MiB / 3839MiB 

* Qt Version: 
$qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu

* liblxqt Version: 

* lxqt-build-tools Version: 

* Package version:

**Comment by stefonarch** [comment]
If I'm not mistaken this refers to LXQt 0.12 which is far outdated. Old versions are not supported.

**Comment by nickson99** [comment]
Correct.
