### ISSUE TITLE
Focus is taken away from the application menu search bar when a menu/button is hovered over with the mouse

### ISSUE THREAD

**Issue by binex-dsk** [lxqt/lxqt-panel#1553]
##### Expected Behavior
The search bar should keep its focus

##### Current Behavior
Focus is lost on the search bar, and it must be clicked again to search

##### Possible Solution
Focus is probably being set to the selected menu. Probably should provide an option to toggle this behavior

##### Steps to Reproduce (for bugs)
1. Open the application (start) menu (or hit Meta)
2. Hover over an application category or other menu, or any button

##### Context
When I open it up by clicking the icon, I move my mouse up a bit (from instinct from some older application menus on Plasma), but usually move it too far and it hovers over the "lock screen" button, which removes focus from the search bar so I have to go back to click it.

When I open it from hitting Meta, I usually move my mouse over there (once again, from instinct) and it loses focus

##### System Information

* Distribution & Version: Artix Linux
* Kernel: 5.10.8.artix1-1
* Qt Version: 5.15.2-3
* liblxqt Version: 0.16.0-1
* lxqt-build-tools Version: not installed, lxqt was downloaded from the repositories (actually, I just installed Artix with the LXQt graphical installer)
* Package version: 0.16.1-1

**Comment by tsujan** [comment]
Everywhere and in all toolkits, only one widget can have the keyboard focus.

When a menu-item is selected, it' also focused and grabs the keyboard. If it has a menu, that menu can be opened by the right arrow key and if a key is pressed while that menu is focused, the menu-item that starts with the corresponding letter will be selected.
