### ISSUE TITLE
Issue when hovering over apps in the panel

### ISSUE THREAD

**Issue by arlesontonnera** [lxqt/lxqt-panel#1555]
Some themes highlight the app rectangle when you hover the mouse over them. However if you do that, right click and then leave the rectangle, the rectangle will remain highlighted. You can keep doing that until all of apps in the panel are highlighted.

**Comment by tsujan** [comment]
The problem doesn't belong to lxqt-panel.

Since Kvantum doesn't have that problem, the bug should be in the themes, whose names you didn't mention (Breeze is known to have it with translucent menus).

**Comment by tsujan** [comment]
Oh, sorry, I thought you meant the main menu, while you meant the panel itself.

That's the infamous "hover bug" of Qt. It was reported to Qt bug tracker and fixed only in some widgets but it's still there -- even in Qt6.
