### ISSUE TITLE
MainMenu and Numpad

### ISSUE THREAD

**Issue by TrueCat17** [lxqt/lxqt-panel#1558]
MainMenu closes on using Numpad [arrows or Enter]

##### Expected Behavior

Numpad [arrows and Enter] must be equal to usual [arrows and Enter]

##### Current Behavior

Unexpected closing

##### Steps to Reproduce (for bugs)

1. Open MainMenu
2. Make sure, that usual arrays and Enter work fine
3. Make sure, that using analog keys on Numpad closes MainMenu

##### Context
I really use Numpad part of keyboard on everyday life in other programs

##### System Information

* Distribution & Version: Debian Unstable
* Kernel: 5.10
* Qt Version: 5.15.2
* liblxqt Version: 0.16
* lxqt-build-tools Version: 
* Package version:

**Comment by stefonarch** [comment]
Confirmed here, when NumLock is off up/down arrows (here on 2/8 and pgDw/Up on  3/9) closes menu.
In panel's right click menus are no issue with those arrows.

**Comment by tsujan** [comment]
Sorry for the long delay for a fix as simple as https://github.com/lxqt/lxqt-panel/pull/1615
