### ISSUE TITLE
"Reset" button in plugin configurations does nothing

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1581]
When a plugin is removed settings are lost and it starts with default settings again when added again.
There is a reset button in most (?) plugins, which doesn't do anything.

##### Expected Behavior

Reset button should reset.
##### Current Behavior

It is inactive.
##### Possible Solution

Make it work or just remove it, as there is no real need  to reset anything, just  remove and readd a plugin will do.
There is also a reset button for the panel itself with the same behavior, it looks as it reloads the panel.

##### Context

https://github.com/lxqt/lxqt-panel/pull/1576
##### System Information

* Distribution & Version: All

**Comment by palinek** [comment]
AFAIK the reset button is there to bring you back to state from time when the config dialog was created -> so just discard changes currently made, not reset to default values.

Isn't this working somewhere?

**Comment by stefonarch** [comment]
I actually never used it, but yes, this works apparently. So maybe we can close this.

**Comment by slidinghotdog** [comment]
> AFAIK the reset button is there to bring you back to state from time when the config dialog was created -> so just discard changes currently made, not reset to default values.
> 
> Isn't this working somewhere?

from some quick tests:
- panel works except override icon theme option.
- worldclock resets the dialog to values from plugin creation (when panel is executed, not when config dialog is opened), and doesn't apply changes to the plugin until something else is changed again.
- volume, mount and menu plugin does nothing.
