### ISSUE TITLE
Misleading week number

### ISSUE THREAD

**Issue by quasart** [lxqt/lxqt-panel#1595]
Hello there !

##### Context

Week numbers in first column of worldclock calendar look like day numbers, it's very misleading when I'm quickly looking for first day of week.

![lxqt-calendar](https://user-images.githubusercontent.com/3080387/112873765-5dff4e00-90c2-11eb-9aa3-c45bb4b7108d.png)

##### Possible solutions

Could you change the week number text format ? Maybe a gray or a smaller font ? It would make clear first column is not first day of week.

I tryed to look at the [source code](https://github.com/lxqt/lxqt-panel/blob/5aebf5ae73c7fde9800bffcc91a2fa4f65a22a4f/plugin-worldclock/lxqtworldclock.cpp#L404), 
maybe adding a `QCalendarWidget::setHeaderTextFormat` call ? What do you think ?

##### System Information

* Distribution & Version: Lubuntu 20.04
* Kernel: 
* Qt Version: 5.12.8
* liblxqt Version: 0.14.1
* lxqt-build-tools Version: 
* Package version: lxqt-panel (0.14.1-1ubuntu3) focal

**Comment by stefonarch** [comment]
That depends on the theme and after week 31 it's hard to misread, I checked and found that only "dark" has a different background, so this could be done in the theme's `panel.qss` probably also font ecc.
![schermata-13-33-48](https://user-images.githubusercontent.com/10681413/112982472-d4e92500-915c-11eb-91bb-cfc9b6c25a39.png)

**Comment by tsujan** [comment]
Nothing should be enforced by the code because the widget can be left to the Qt widget style.

**Comment by stefonarch** [comment]
I'd propose to add something like

```
QCalendarWidget QWidget {
    alternate-background-color: #dadada;
}
```
to the "white"  themes, example "frost":

![schermata-14-56-45](https://user-images.githubusercontent.com/10681413/112992411-6f9b3100-9168-11eb-954e-f47525538edd.png)

I never noticed it because I'don't use any of them, but in fact it's hard to tell the difference.

**Comment by tsujan** [comment]
@stefonarch
Please make a PR! I should also make a small PR for lxqt themes for another reason.

**Comment by quasart** [comment]
I understand, I will use another lxqt theme for now
Thank you :+1:

**Comment by tsujan** [comment]
Qt uses `QPalette::AlternateBase` for that area. Translated into stylesheet color names, it's exactly "alternate-background-color", as you mentioned above.

`QPalette::AlternateBase`/`alternate-background-color` can be different from `QPalette::Base`/`background-color` but they shouldn't have a high contrast with each other.

**Comment by stefonarch** [comment]
Now on my main PC I see why: "window" is set lightly darker than "view" and that exstincts in some themes the small differences.

BTW let me know a day before you make the release files, to commit and push all recent changes fromweblate.

**Comment by tsujan** [comment]
> BTW let me know a day before you make the release files

Sure. I'll open a Discussion page and ask all members whether they have any objection to a release date.

All marges should be stopped in the day of releasing, especially translation merges.
