### ISSUE TITLE
LXQt panel: grouped window popup disappears on mouseover with patched versions of Qt5 (in Arch)

### ISSUE THREAD

**Issue by DanielPrjct** [lxqt/lxqt-panel#1600]
Description:

Arch Linux (up-to-date) with LXQt.

I've updated my system at 2021/04/08 and 2021/04/09 and since qt5-... packages versions are qt5-....version+kde+version, LXQt panel doesn't allow to select and maximize/resize any grouped minimized window.
As example: two or more Qterminal instances in the same desktop, or Thunderbird main window and its Write window in other desktop.

Grouped windows are showed (pop up menu appears with left click) by LXQt Panel, but when I try to select one minimized window, the pop up menu dissapear.

Once all windows in the same desktop are minimized and showed in LXQt Panel, neither of them can be maximized nor resized from LXQt taskbar (Task Manager).

The only updated packages that I can see perhaps related to this bug are:
qt5-base 5.15.2+kde+r171-2
qt5-declarative 5.15.2+kde+r24-1
qt5-svg 5.15.2+kde+r5-1
qt5-wayland 5.15.2+kde+r11-1 ? (I'm not using Wayland at all).
All are now "mainversion+kde+version"... 

Downgrading to previous "non-kde" versions seems solve the issue...

Additional info:
* package version(s)

liblxqt 0.16.0-1
lximage-qt 0.16.0-1 (lxqt)
lxqt-about 0.16.0-1 (lxqt)
lxqt-admin 0.16.0-1 (lxqt)
lxqt-archiver 0.3.0-1 (lxqt)
lxqt-config 0.16.1-1 (lxqt)
lxqt-globalkeys 0.16.0-1 (lxqt)
lxqt-notificationd 0.16.0-1 (lxqt)
lxqt-openssh-askpass 0.16.0-1 (lxqt)
lxqt-panel 0.16.1-1 (lxqt)
lxqt-policykit 0.16.0-1 (lxqt)
lxqt-powermanagement 0.16.0-1 (lxqt)
lxqt-qtplugin 0.16.0-1 (lxqt)
lxqt-runner 0.16.0-1 (lxqt)
lxqt-session 0.16.0-1 (lxqt)
lxqt-sudo 0.16.0-1 (lxqt)
lxqt-themes 0.16.0-1 (lxqt)
obconf-qt 0.16.0-1 (lxqt)
openbox 3.6.1-7 (lxde lxde-gtk3 lxqt)
pcmanfm-qt 0.16.0-1 (lxqt)
qterminal 0.16.1-1 (lxqt)
qt5-base (5.15.2-5 -> 5.15.2+kde+r171-1)
qt5-svg (5.15.2-2 -> 5.15.2+kde+r5-1)
qt5-declarative (5.15.2-1 -> 5.15.2+kde+r24-1)
qt5-wayland (5.15.2-1 -> 5.15.2+kde+r11-1)

##### Expected Behavior

Open two or more instances of an application in different windows at the same desktop, or open a dialog window of an application, and then minimize one or more windows. They will be grouped at task manager. Left click in each group must show its minimized windows and allow select what window must be maximized or resized.

##### Current Behavior

Left click in a group in Task Manager pop up a lit of minimized windows, but they dissapear immediatly, or when user try to select one of them hovering the cursor.

##### Possible Solution

@arojas, KDE and qt5 maintainer at Arch Linux team, says that this issue is caused by this Qt change;
[url]
https://code.qt.io/cgit/qt/qtbase.git/commit/?h=5.15&id=62f86b9b7ab3421c7a74c4c05a186847c76bfb28
[/url]

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version:  Arch Linux
* Kernel: 5.11.12-arch1-1
* Qt Version: 5.15.2-5
* liblxqt Version: liblxqt 0.16.0-1
* Package version: qt5-base 5.15.2-5

**Comment by antonio-rojas** [comment]
this is not "a patched version of Qt5". As mentioned above, this is caused by an actual upstream Qt commit, https://code.qt.io/cgit/qt/qtbase.git/commit/?h=5.15&id=62f86b9b7ab3421c7a74c4c05a186847c76bfb28

**Comment by tsujan** [comment]
It's patched by using upstream patches (and "...+kde+r..." shows that). The official releases are here: https://download.qt.io/official_releases/qt/5.15/

**Comment by tsujan** [comment]
@stefonarch 
Could you test if the following change makes a difference?
```diff
diff -ruNp lxqt-panel-orig/plugin-taskbar/lxqttaskgroup.cpp lxqt-panel/plugin-taskbar/lxqttaskgroup.cpp
--- lxqt-panel-orig/plugin-taskbar/lxqttaskgroup.cpp
+++ lxqt-panel/plugin-taskbar/lxqttaskgroup.cpp
@@ -576,7 +576,8 @@ void LXQtTaskGroup::dragLeaveEvent(QDrag
 void LXQtTaskGroup::mouseMoveEvent(QMouseEvent* event)
 {
     // if dragging the taskgroup, do not show the popup
-    setPopupVisible(false, true);
+    if (event->buttons() & Qt::LeftButton)
+        setPopupVisible(false, true);
     LXQtTaskButton::mouseMoveEvent(event);
 }

```

**Comment by antonio-rojas** [comment]
Tha patch fixes the problem for me.

**Comment by tsujan** [comment]
@antonio-rojas 
Thanks a lot! Two questions:

 1. If you start to drag the task button of grouped windows while the popup is shown, the popup should disappear. Does that happen?
 2. On right clicking the task button of grouped windows, another popup appears; it says, "Close group". Does it work with the above change?

**Comment by antonio-rojas** [comment]
> @antonio-rojas
> Thanks a lot! Two questions:
> 
> 1. If you start to drag the task button of grouped windows while the popup is shown, the popup should disappear. Does that happen?
> 2. On right clicking the task button of grouped windows, another popup appears; it says, "Close group". Does it work with the above change?

Yes to both.

**Comment by tsujan** [comment]
> Yes to both.

Good :) I'll make a PR today.

**Comment by stefonarch** [comment]
Tested the PR, looks fine.
