### ISSUE TITLE
panel is missing after an update

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-panel#1610]
on an MSI Computer I tested Lubuntu 20.10 as live-version;
the panel was there right away;
then I installed Lubuntu 20.10;
after restarting the computer the panel was there right away;
I restarted again the computer, and the panel was there right away;

but then I made an update, and after a restart I have a problem with the panel: after every boot:
- after 30 seconds the icons on the desktop are moving a little bit (compare picture 1 and 2)
- and then after again 30 seconds the panel appears with a red exclamation-mark-symbol in the panel
- and then I have to wait again at least one minute till the red exclamation-mark-symbol will disappear that will be replaced by the speaker-symbol

if I wait one minute at the login-screen, then the red exclamation-mark-symbol will not appear, but nevertheless I have to wait one minute till the panel will appear

picture 1:
![1](https://user-images.githubusercontent.com/68117017/115125352-dbcebf00-9fc7-11eb-8756-d1ddf1745f24.jpeg)

picture 2 when the symbols on the desktop are moving a little bit:
![2](https://user-images.githubusercontent.com/68117017/115125362-e721ea80-9fc7-11eb-849b-0d0425a9f926.jpeg)

picture 3 with the red exclamation-mark-symbol in the panel:
![3](https://user-images.githubusercontent.com/68117017/115125372-f9038d80-9fc7-11eb-9496-6c732dac8e0c.jpeg)

picture 4 when the red exclamation-mark-symbol will be replaced by the speaker-symbol:
![4](https://user-images.githubusercontent.com/68117017/115125397-18021f80-9fc8-11eb-900f-e3ef782a9247.jpeg)

the problem has to do something with one package or some packages during the update:

![screen](https://user-images.githubusercontent.com/68117017/115125313-914d4280-9fc7-11eb-891c-1017054e209d.jpg)

maybe the problem could be because the computer has no speaker; it is just a bare-bone-PC

##### System Information
* Distribution & Version:  Lubuntu 20.10
* Qt Version: 0.15.0

**Comment by tsujan** [comment]
Should be reported to Lubuntu, not here.

**Comment by stefonarch** [comment]
> maybe the problem could be because the computer has no speaker; it is just a bare-bone-PC

So why do you have this plugin in the panel? Remove it...

**Comment by ralf3u** [comment]
@stefonarch
> So why do you have this plugin in the panel? Remove it...

true; if I delete it in the panel, then the panel will appear always right away after every reboot;
but then there is a disadvantage: suspend does not work at all any more

**Comment by ralf3u** [comment]
maybe this could be an interesting information:
in Lubuntu 20.04 it is even worst: already in the live-version the panel is not there right away
