### ISSUE TITLE
System Statistics graph resets on auto-hiding panels

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#1614]
##### Expected Behavior

It would be better if the graph of System Statistics was also drawn when the panel was hidden.
##### Current Behavior

When a hidden panel is shown, the graph of System Statistics starts anew.
##### Possible Solution

Since a widget is updated only when it's shown, I have no idea yet.
##### System Information
Lates git LXQt.

**Comment by palinek** [comment]
Please, test with #1720
