### ISSUE TITLE
Pystray icon is not displayed

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt-panel#1630]
I try to develop a small application in Python with pystray to display an icon and pass some commands.
However, the icon I have set is not displayed, but instead, I got a exclamation mark in a box.
I don't know from where the problem is (pystray or LXQt). Have pystray somthing special to do to have the icon displayed ?
For what I see, pystray detect a backend and apply specific behaviour according to this backend. Some of them are Xlib, GTK, libappindicator. I think that libappindicator is used.

##### Expected Behavior
Display the icon I sent to pystray

##### Current Behavior
Display an icon as a box with ! inside

##### Steps to Reproduce (for bugs)
Apply the example from https://pystray.readthedocs.io/en/latest/usage.html

##### System Information
Mageia 8
lxqt-panel-0.16.1-2.mga8
Kernel: Linux VMm8 5.10.43-desktop-1.mga8
* Qt Version: 5.15.2
* liblxqt Version: liblxqt-0.16.0-3.mga8

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lxqt-panel/pull/1625 and https://github.com/lxqt/libqtxdg/pull/261
