### ISSUE TITLE
How can I show lxqt-panel when I am viewing Firefox in full screen mode?

### ISSUE THREAD

**Issue by Raytle** [lxqt/lxqt-panel#1631]
Normally when I press my hotkey (which is the super key) lxqt-panel pops properly for me. However, when I am viewing Firefox (or Google Chrome) in full screen mode I am unable to cause the lxqt-panel to popup.

**Comment by stefonarch** [comment]
You mean the "menu" shortcut is set to super key? 
Which version of LXQt are you using? 
With git version and 0.17  the menu (but not the panel) pops up using ALT+F1 with Browsers in fullscreen.

**Comment by Raytle** [comment]
> You mean the "menu" shortcut is set to super key?

This –> https://i.imgur.com/w51yj2n.png is what I mean. That is a screenshot from my [Shortcut Keys](https://manual.lubuntu.me/stable/3/3.2/3.2.14/shortcut_keys.html#chapter-3-2-14-shortcut-keys). In case it matters, I am running `Lubuntu 20.04 LTS`.

> Which version of LXQt are you using?

I'm running...

```
lxqt-panel 0.14.1
liblxqt   0.14.1
Qt        5.12.5
```

Nevertheless, on my version when I press the super key (which is shown in the above screenshot as `Super_L`), the menu pops up (but not the panel). In other words, although I have an older version ( `lxqt-panel 0.14.1` instead of `lxqt-panel 0.17` the menu pops up (but not the panel).

I want the panel to popup. Now that I think about it, I would like the ability to only popup the panel instead of popping up both the menu and the panel.

What's my use case? I often use Firefox in full screen mode. When doing so, I often like to glance at the time, day, and date. https://i.imgur.com/Etfa8X4.png. Yeah. Sure. I know. I could install a clock application or find a Python script someone wrote to create a clock. But. See. Here's the thing: glancing at the time, day, and date in the task bar works fine for me... except when I am in Firefox in full screen mode.

**Comment by stefonarch** [comment]
There's no shortcut to show the panel, this could be a feature request, actually you'd need to use ESC and/or F11 which IMHO covers the need, there is now also an option to show panel only when windows doesn't overlap.

**Comment by Raytle** [comment]
> There's no shortcut to show the panel, this could be a feature request, actually you'd need to use ESC and/or F11 which IMHO covers the need, there is now also an option to show panel only when windows doesn't overlap.

Thanks for taking the time to explain that with me.


> This said 0.14 is far outdated.

Thanks for letting me know. I appreciate that. If I were to upgrade to  0.17 would I be able to show lxqt-panel when I am viewing Firefox in full screen mode?

**Comment by tsujan** [comment]
Please don't use the bug tracker for asking questions.
