### ISSUE TITLE
missing some icons in the task switcher and also in open windows on the panel

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-panel#1632]
icons in the quicklaunch and in the Application menu are shown correctly, but many icons are not shown in the Task Manager, so in the open windows in the panel, and also not shown in the task switcher (Alt+Tab)

these are the open windows on the panel from the left to the right (I decided that only the symbols are shown with a width of 50px instead of 200px): Firefox, FeatherPad, KCalc, LXImage, Power Management Settings, VLC, Meld, Geany, LibreOffice Writer, FileZilla, Audacity and Inkscape
![panel_task_manager_open_windows](https://user-images.githubusercontent.com/68117017/124354387-02d27f80-dc0c-11eb-8466-63476351404b.jpg)

as you can see, the icons of FeatherPad, KCalc, LXImage, Power Management Settings and VLC are missing

##### System Information
* Distribution & Version: Lubuntu 21.04
* LXQt: 0.16.0

**Comment by tsujan** [comment]
Not reproducible. 0.16.0 is outdated too.

**Comment by stefonarch** [comment]
![screen](https://user-images.githubusercontent.com/10681413/124356780-3f0bdd00-dc18-11eb-868b-0716c6dc28bc.png)
Same.
