### ISSUE TITLE
My kludge for only popping up lxqt-panel only when I press a hotkey works, but I'd prefer a more elegant solution.

### ISSUE THREAD

**Issue by Raytle** [lxqt/lxqt-panel#1633]
Instead of the kludge below I'd like an option to popup (to show) `lxqt-panel`**only** when I press a hotkey. If you are concerned that users might inadvertently check a button with such functionality yet not have a hotkey bound to `lxqt-panel` then perhaps it might be reasonable to require users to login as root and edit a file. Such file might include the following lines...

**Uncomment the following line to only popup `lxqt-panel` with a hotkey (never when mousing over).**
** Code to uncomment .**
**If you run into a problem launching `lxqt-panel` with your hotkey then launch `lxqt-panel` from a terminal which is indicated here... https://manual.lubuntu.me/stable/5/5.1/lxqt-panel.html#how-to-launch.**

I copied and pasted the following from... https://discourse.lubuntu.me/t/can-the-lxqt-panel-be-configured-to-only-popup-when-a-hotkey-is-pressed/2601/4

I came up with a pretty good solution for my needs. I opened the following as root…

`/etc/xdg/autostart/lxqt-panel.desktop`

Then I changed the following line from

`Exec=lxqt-panel`

to

`Exec=lxqt-panel-OFF`

so that `lxqt-panel` is no longer loaded on startup.

To run `lxqt-panel` I can launch it from a terminal.

If anyone has a better solution I’d be glad to learn of it.

**Comment by tsujan** [comment]
Please use [Discussions](https://github.com/lxqt/lxqt/discussions) for this.

**Comment by Yekutiel** [comment]
This...https://github.com/lxqt/lxqt/discussions/2023#discussioncomment-925536 

should be in https://manual.lubuntu.me/stable/5/5.1/lxqt-panel.html#how-to-launch.

This.... 
> BTW, please don't use the issues section for questions. We have [Discussions](https://github.com/lxqt/lxqt/discussions) for that."

should be at the top of https://github.com/lxqt/lxqt-panel/issues

**Comment by stefonarch** [comment]
> This....
> 
> > BTW, please don't use the issues section for questions. We have [Discussions](https://github.com/lxqt/lxqt/discussions) for that."
> 
> should be at the top of https://github.com/lxqt/lxqt-panel/issues

It's not an issue, but we could/should add it in the template:

```
<!-- Please don't use the issues section for questions and similar - use  https://github.com/lxqt/lxqt/discussions instead.-->

<!--- Provide a general summary of the issue in the title above. You       --->
<!--- should not delete relevant sections and/or questions in your report  --->

<!--- BEFORE FILLING OUT THIS REPORT FORM:                                 --->
<!--- Dear users of stable and LTS (long term service) distributions:      --->
<!--- Please do NOT file bugs against old (dead) versions but use your     --->
<!--- distribution bugtracker instead. This is esp. true for Ubuntu LTS.   --->

```

**Comment by tsujan** [comment]
The template is self-explanatory. What doesn't fit doesn't belong.

**Comment by tsujan** [comment]
> This...lxqt/lxqt#2023 (comment) should be in https://manual.lubuntu.me/stable/5/5.1/lxqt-panel.html#how-to-launch.

LXQt isn't responsible for Lubuntu or any other distro.
