### ISSUE TITLE
[Feature request] Include country flags

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1645]
plugin-kbindicator provides already the possibility to display flags instead of ISO country-code.
Shipping them together with the panel in `/usr/share/lxqt/graphics/country-flags` would be easier  for users than setup them manually.

Icons can be found here:
https://github.com/hampusborgos/country-flags - the  svg folder contains suitable lightweight icons.

The pattern  `/usr/share/lxqt/graphics/country-flags/svg/%1.svg` could be included by default and substituted by a checkbox "show flag".

**Comment by tsujan** [comment]
I'm not sure. There are lots of files and each user only needs a few of them. I think users can easily find them — and some can make them for themselves.

An explanation in a wiki will be enough, IMO.

**Comment by stefonarch** [comment]
I doubt the average user not  even knows about the diffs between .svg and .png
As for the files, it is not even 5MiB.

**Comment by stefonarch** [comment]
Well I searched too far:
```
$ apt show iso-flags-svg 
Package: iso-flags-svg
Version: 1.0.2-1.1
Priority: optional
Section: misc
Maintainer: Debian Cinnamon Team <debian-cinnamon@lists.debian.org>
Installed-Size: 10,0 MB
Homepage: https://github.com/joielechong/iso-country-flags-svg-collection
Download-Size: 1.147 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian bullseye/main amd64 Packages
Description: ISO country flags in SVG format
 High quality vector graphics country flag icons.
 .
 It contains more than 240 country flag icons in a squared and in a 4x3 aspect
 ratio.

```
Will write a wiki page about that. Still to see how this package is called in some other distros.

**Comment by stefonarch** [comment]
Done https://github.com/lxqt/lxqt/wiki/ConfigMiscellaneous#plugin-keyboard-indicator
