### ISSUE TITLE
Panel reserve space is broken in i3

### ISSUE THREAD

**Issue by iamthesenate1** [lxqt/lxqt-panel#1663]
##### Expected Behavior

The panel should free up screen space when the according option is enabled.
##### Current Behavior

It doesn't.

##### Steps to Reproduce (for bugs)

1.Use i3
2.Enable reserve space for the panel.
3. It doesn't work.

##### System Information

* LXQt Version: git; archlinuxcn repo
* Distribution & Version: Manjaro unstable repos
* Qt Version:5.15.2
* liblxqt Version: git
* Compositor: picom-git

**Comment by tsujan** [comment]
lxqt-panel is hidden in a standard way. The bug is in i3. For a similar bug, see https://github.com/i3/i3/issues/4153

**Comment by tsujan** [comment]
Oh, you changed the title and description. But still there's nothing in lxqt-panel that can cause it.

**Comment by iamthesenate1** [comment]
> Oh, you changed the title and description. But still there's nothing in lxqt-panel that can cause it.

Yes. I realised the prior issue was due to the lack of a compositor.

**Comment by tsujan** [comment]
Lack of compositor couldn't prevent the panel from auto-hiding if i3 didn't have a bug.

**Comment by iamthesenate1** [comment]
> Lack of compositor couldn't prevent the panel from auto-hiding if i3 didn't have a bug.

You are right. There are several other minor bugs that I encontered that were clearly i3 bugs.

**Comment by tsujan** [comment]
I vaguely remember that we received other reports about it too but I'm not sure.

What I know is twofold: (1) We use Qt's and KWindowSystem's methods in lxqt-panel — nowhere we have DE specific codes — and (2) rarely, some WMs may not have a standard behavior — for example, Enlightenment's WM has weird flaws, which its developers have always ignored.

**Comment by stefonarch** [comment]
I tested it out, never used i3, and I see when stopping/starting the panel module from session settings i3 moves his bar from screen border to panel border and back, expected would be an overlapping of both.

**Comment by iamthesenate1** [comment]
> I tested it out, never used i3, and I see when stopping/starting the panel module from session settings i3 moves his bar from screen border to panel border and back, expected would be an overlapping of both.

This is almost certainly not the issue. i3status (the bar that you mention) can be deactivated in the config. The problem is that the panel disappears as it should but it still "reserves" space. Here is a screenshot that should make things clearer:
![screen](https://user-images.githubusercontent.com/77978836/133939090-9c3cdf77-bffb-4634-82ed-e6c95ba9ef74.png)

**Comment by iamthesenate1** [comment]
The only way to reclaim the space is to kill lxqt-panel and then relaunch it when needed. But that is both brutal and resource consuming.

**Comment by tsujan** [comment]
@iamthesenate1
i3's devs may need to know about the problem. Why don't you open an issue at their bug tracker? You could quote this:

"We use Qt's and KWindowSystem's methods in lxqt-panel — nowhere we have WM specific codes."

**Comment by iamthesenate1** [comment]
Thanks for the quick replay. I was just in the process of doing this.

**Comment by iamthesenate1** [comment]
I understand, but what the i3 developer wanted to know is exactly what Qt method(s) is used for hiding the panel.

**Comment by tsujan** [comment]
[QWidget::setGeometry()](https://doc.qt.io/qt-5/qwidget.html#geometry-prop).

Also, see

https://github.com/lxqt/lxqt-panel/blob/04e493dc0596a19103d576b1175a27abc11b15d5/panel/lxqtpanel.cpp#L581-L606

**Comment by psychon** [comment]
<details>
<summary>I think this comment is not too helpful currently, but still it's partly relevant.</summary>

>  For one, a geometry with height = 0 would be invalid, 

I'm not quite sure where this `height = 0` comes from, but Qt automatically ensures that the values are valid. If I read this code correctly, it will translate `height = 0` to `height = 1`:

https://github.com/qt/qtbase/blob/2b6500cd15c0a41cf3e5eea8178e2044012dbd97/src/plugins/platforms/xcb/qxcbwindow.cpp#L575-L582

I did not look at the i3 logs, but since no resize to `height = 1` appears in there, I guess this comment is not really helpful.
</details>
