### ISSUE TITLE
Context menu in taskbar shows only generic desktop names

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1665]
Desktop 1, Desktop 2 and so on

##### Expected Behavior

As plugin-desktopswitch shows names also taskbar menu should show them.
##### Current Behavior

Only "Desktop X" is shown with numbers

##### Steps to Reproduce (for bugs)

1. Right click on window button
2. Select "To Desktop"
3. List is numbered only

##### System Information

* LXQt Version: git, all

**Comment by palinek** [comment]
Was this fixed by #1691?

**Comment by stefonarch** [comment]
Yes, for openbox and kwin, for xfwm4 there is no way to  have persistent names.
https://github.com/lxqt/lxqt-panel/issues/1693
