### ISSUE TITLE
Smaller config dialog

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#1680]
With its current min. size, it may not fit into small screens or VMs.

See how the same problem was fixed in QTerminal's settings dialog.

**Comment by tsujan** [comment]
I'll work on it (having experience in how to avoid scrollbars when possible).

**Comment by stefonarch** [comment]
It's ok  and working. 
I was thinking to split in 3 the settings:
* appearance
* Behavior (actually only autohide section)
* Widgets/Elements

**Comment by tsujan** [comment]
> I was thinking to split in 3 the settings:

That's also possible. I think it's a good idea to split the settings somehow. Maybe, we can put size and alignment inside a page with the title "Size and Position" and the rest inside another page with the title "Custom Styling". Then, the dialog will be small enough for all screens.

If so, https://github.com/lxqt/lxqt-panel/pull/1681 will be redundant and a more complex patch will be needed.
