### ISSUE TITLE
Translations broken  in panel settings

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1703]
After https://github.com/lxqt/lxqt-panel/pull/1692 was merged translations in panel settings are present but not applied anymore.

##### Possible Solution

Running` lxqt-transupdate` fixes that, the downside is that about 50 items get marked as "unfinished". 
Merging https://github.com/lxqt/lxqt-panel/pull/1702 and writing an announcement in weblate about it is one solution. The easiest way is:download the *.ts file,  use  qt-translator, translate the 4 untranslated and hit cltr+enter all over the rest

![schermata-01-19-22-09](https://user-images.githubusercontent.com/10681413/150214427-c09de9db-f661-4c8a-89e3-e08085756439.png)

A script which removes `type=unfinished` only where a translations follows would be better.

                        

##### System Information

* LXQt Version: Latest git
*

**Comment by tsujan** [comment]
I'm not sure if I understand the problem but Qt may mark a translation as "unfinished" when its context is changed radiacally, which was the case in https://github.com/lxqt/lxqt-panel/pull/1692. This behavior is expected.

**Comment by stefonarch** [comment]
Yes, it shows translations "wrongly" as unfinished, in weblate they are marked as "needs editing".

**Comment by tsujan** [comment]
I think this behavior of Qt can be justified when we consider that the meaning of a word might change if the context in which it appears changes. The good thing is that the translations aren't lost; they're just marked as unfinished.

**Comment by stefonarch** [comment]
A command line:
`sed -i '/></! s/tion\ type=\"unfinished\"/tion/g' lxqt-panel_*.ts ` 
looks like working. 

It excludes `><` (lines with `<translation></translation> `)

There could be some cases where a translation is marked "needs editing" because unsure, those would be removed too. But needs more testing.

**Comment by palinek** [comment]
`sed --in-place -re '/<translation .*type="unfinished"[^>]*>[^<]/ s/ ?type="unfinished"//' *_*.ts`

**Comment by stefonarch** [comment]
> *_*.ts

I didn't check yet but I think only `lxqt-panel_*.ts` needs to be polished.

**Comment by tsujan** [comment]
Just for the record, and because I've encountered it:

Consider this translatable string: "Always show tabs". If it appears in the context of main window, it'll be about GUI tabs. But if it appears in a text-editing context, it'll be about showing *text* tabs as a kind of whitespace.
