### ISSUE TITLE
Main menu fails to handle string literals (single quotes) in desktop files

### ISSUE THREAD

**Issue by jas-per** [lxqt/lxqt-panel#1705]
.desktop files that use single quotes for string literals pass these quotes to the application when opened from the main menu
example:

```
[Desktop Entry]
Name=Unlock data files
Exec=/usr/bin/luckyluks -c '/media/backup/data container.bin' -n 'data files'
Icon=dialog-password
NoDisplay=false
StartupNotify=false
Terminal=0
Type=Application
```

##### Expected Behavior
`/media/backup/data container.bin` should get passed as string literal (with spaces) to the application

##### Current Behavior
`'/media/backup/data container.bin'` gets passed (with surrounding single quotes)
(results in path not found within the application)

##### Context
The [luckyluks](https://github.com/jas-per/luckyLUKS) application creates desktop files as shortcuts to encrypted containers, all paths and names could include spaces etc so these parameters get surrounded by single quotes

Last time I thoroughly tested the application was 5 years ago, so I decided to replace LXDE with LXQt in my tests now. Tested most bigger non-tiling DEs (Gnome, KDE, Xfce, Cinnamon, Mate) and all of them handle the single quotes fine. LXDE did so as well

When using the .desktop file as a shortcut (`add to desktop`) the single quotes are also working fine in LXQt so there is probably just a check missing in the Main menu

##### System Information
* LXQt Version: 0.14, 0.16, 0.17
* Distribution & Version: Ubuntu 20.04 LTS, Ubuntu 21.10 and Debian sid
* Qt Version: 5.12.8, 5.15.2

**Comment by tsujan** [comment]
Confirming, with LXQt 1.0.0.

PCManFM-Qt (actually, `libfm-qt)` has no problem with single quotes but Panel's main menu does.

**Comment by palinek** [comment]
The [spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html) is clear about quoting:
> Quoting must be done by enclosing the argument between double quotes and escaping the double quote character, backtick character ("`"), dollar sign ("$") and backslash character ("\") by preceding it with an additional backslash character.

Then I would say panel/libqt5xdg behaves correctly.

If any other implementation does honor also single quote, it can be seen either as a specification violation or specification enhancement.

**Comment by tsujan** [comment]
@palinek 
I haven't looked into it yet but, apparently, other DEs allow it. Also, as mentioned above, it's allowed by `libfm-qt`. So, IMHO, we might need to go beyond the spec here.

**Comment by tsujan** [comment]
I think I've succeeded in duplicating GLib's behavior regarding string literals in Exec values. Will make a PR after more tests.
