### ISSUE TITLE
No transparent background for volume popup and calendar popup

### ISSUE THREAD

**Issue by Nudnikde** [lxqt/lxqt-panel#1707]
##### Expected Behavior
Setting background color with transparency in lxqt-panel.qss should apply a transparent background for Mixer plugin and calendar plugin

##### Current Behavior
Even with background color transparency defined mixer plugin and calendar plugin only show solid background colors

##### Steps to Reproduce (for bugs)
1. select a lxqt theme with lxqt-panel.qss that includes transaparent backround settings for mixer and calendar, see attached 
2. only solid colors appear
3.
4.

##### Context
trying compensate lack of transparency by setting a fixed color that matches as close as possible to the semitransparent panel. Unfortunately not practicable when changing backgrounds

##### System Information
* LXQt Version: 1.0.0
* Distribution & Version: Manjaro 21.2.2
* Qt Version: 5.15.2
* liblxqt Version: 1.0.0

[Black Beauty by Nudnik v0.2.tar.gz](https://github.com/lxqt/lxqt-panel/files/7959497/Black.Beauty.by.Nudnik.v0.2.tar.gz)

**Comment by tsujan** [comment]
Calendar is drawn by Qt but it's possible to make the mixer or any other popup translucent in the code, by putting a `QFrame` inside it and adding widgets to that frame.

I don't know why that wasn't done from start but, if we do it now, all existing themes will be broken — it isn't backward compatible and the style sheets will need to change accordingly. So, I'm not sure that it'll be worth the result.

**Comment by Nudnik-de** [comment]
If the calendar is drawn by QT is there a setting somewhere else to activate transparency?
The tooltip popups are already transparent but for the widgets like mixer there is no way to make it transparent, right?

**Comment by tsujan** [comment]
> If the calendar is drawn by QT is there a setting somewhere else to activate transparency?

No (please read below).

> but for the widgets like mixer there is no way to make it transparent, right?

As I said, there *is* a way to make it translucent — and that's a good idea, IMO — but the required code changes won't be backward compatible. That's why I left this report open.

For a widget to have translucency, it should have some properties in its code. If it does, then a style sheet could give it translucency. The volume popup doesn't have those properties but we could give them to it in the code. However, if we do so, the CSS names will change and the current themes will be broken. Perhaps not a big deal because we could edit all themes afterward.

@stefonarch, what do you think?

**Comment by stefonarch** [comment]
We could fix our themes, but there are also [third party and distro themes around](https://github.com/lxqt/lxqt/wiki/Theming#community-created-themes). 
I think it's not worth it.

**Comment by tsujan** [comment]
> I think it's not worth it.

I agree. However, I don't think a very bad thing will happen; the popup will just be styled by the active widget style until its stylesheet is edited. The editing should be easy — adding a name and removing `>` — but I'm not sure yet.

On the other hand, if we do it for volume popup, we should do it for other popups too. More theme breaking...
