### ISSUE TITLE
[Bug] Ctrl + a closes application menu

### ISSUE THREAD

**Issue by libalis** [lxqt/lxqt-panel#1717]
Instead of ctrl + a marking the text in the search field of the application menu, it simply closes it.

##### System Information
* LXQt Version: 1.0.0
* Distribution & Version: openSUSE Tumbleweed
* Qt Version: 5.15
* liblxqt Version: 1.0.0

**Comment by tsujan** [comment]
Yes, a small issue, whose fix may not be trivial.

**Comment by libalis** [comment]
I agree, very small mistake but a bit annoying

**Comment by palinek** [comment]
This seems to be the problematic place -> https://github.com/lxqt/lxqt-panel/blob/master/plugin-mainmenu/lxqtmainmenu.cpp#L641-L643 ... which is originally based on this commit -> https://github.com/lxqt/lxqt-panel/commit/0c99c220ac1559e4321a1dc12cefc56ae98d806b#diff-f7ab3ac13c3dc2cdd714dacdd5fa2ecddd7b51c5540eab6f00f73b1509ebede4R327

Logic in the referenced commit correctly checks for the shortcut, but now this is somehow lost...

**Comment by palinek** [comment]
... seems it was me, who introduced this bug :-) -> https://github.com/lxqt/lxqt-panel/commit/acc90ef308a4e15a0ab72cb7a7403e41a9988b36

**Comment by palinek** [comment]
Yes, the Esc wiill work as previously.

**Comment by libalis** [comment]
Amazing.

**Comment by palinek** [comment]
Yes, thanks to recent changes in lxqt-globalkeys.

**Comment by palinek** [comment]
I didn't touch the mainmenu configuration anyhow.

**Comment by stefonarch** [comment]
I know, I just noticed that only now, it's the same in 0.17

**Comment by stefonarch** [comment]
I noticed no misbehaviour while testing with modifier keys, but cannot tell about the code changes.

**Comment by libalis** [comment]
Sounds really great, thank you so much.
