### ISSUE TITLE
[Feature request] Add a command line option to show hidden panel or just show hidden panel on windows key down

### ISSUE THREAD

**Issue by QiangF** [lxqt/lxqt-panel#1726]
**Is your feature request related to a problem? Please describe.**

I have two hot keys to switch to left  and right application on the panel, the hot keys have windows key as a modifier, I want to see the panel on windows key down so I can decide which way to move (left or right).
I used to use i3wm and the status bar is shown on windows key down.

**Describe the solution you'd like**

Either give a command option like "lxqt-panel --show", so I can use a hotkey deamon https://github.com/k0kubun/xremap/issues/72
Or better just implement the feature in lxqt-panel.

**Comment by palinek** [comment]
Same as #1725
