### ISSUE TITLE
[Feature request] Hide panel completely like the old lxpanel

### ISSUE THREAD

**Issue by QiangF** [lxqt/lxqt-panel#1727]
**Is your feature request related to a problem? Please describe.**

When lxpanel is set to autohide, there is not any left over, I can see all part of a maximized window.
lxqt-panel left a thin bar and blocks part of screen area.

**Describe the solution you'd like**

Maybe get the behavior like lxpanel.

**Comment by stefonarch** [comment]
Check panel settings:

![schermata-02-24-13-13](https://user-images.githubusercontent.com/10681413/155522022-5f61dc4d-03f5-4973-82bc-d2aaf3250f1e.png)

**Comment by QiangF** [comment]
> Check panel settings:
> 
> ![schermata-02-24-13-13](https://user-images.githubusercontent.com/10681413/155522022-5f61dc4d-03f5-4973-82bc-d2aaf3250f1e.png)

I have autohide checked, but there is still a little bar about 2 pixels in height.
I would not mind if it's transparent, but it blocks part of the underlying window.

**Comment by stefonarch** [comment]
Did you uncheck "visible thin margin"?

**Comment by QiangF** [comment]
Yes I do. There aren't many options. I have tried them all.

**Comment by tsujan** [comment]
Transparency needs compositing. You probably don't have a compositor.

**Comment by QiangF** [comment]
@tsujan But how does the old lxpanel become invisible after hiding? I only have openbox.

**Comment by jeremywh7** [comment]
@QiangF  https://github.com/lxqt/lxqt/issues/723#issuecomment-117340529

**Comment by sapienfrom2000s** [comment]
Is there a way to trigger autohide by keyboard shortcut?

**Comment by QiangF** [comment]
there is a feature request https://github.com/lxqt/lxqt-panel/issues/1842
