### ISSUE TITLE
Directory Menu: Option to show text, icon or both

### ISSUE THREAD

**Issue by ianfarrell47** [lxqt/lxqt-panel#1730]
As of LXQt 1.0.0, there is no easy way to access directories from the panel.
To create a directory list, the panel takes a plugin Directory Menu. There is only an icon to click.
The sub-menu to open the directory or open it in the terminal is clunky.

In GNOME 2 and MATE, there is a main menu of Applications, Places, System. I find it a good launching solution.
To replicate this, text could be added to the Directory Menu plugin and the icon could be toggled.
Or it could be a clone of GNOME 2's widget.

**Comment by tsujan** [comment]
Your report isn't a feature request. You want LXQt to copy GNOME2. It won't.

**Comment by ianfarrell47** [comment]
Sorry for my brazen reference to gnome 2. What the specific feature that would enable this look-and-feel through customization is  adding text to the Directory Menu plugin and a toggle for the icon with text. Then the "Places" portion of the standard gnome 2 could be created in LXQt.

**Comment by tsujan** [comment]
Directory Menu has room for enhancements. For example:

 1. Limiting its icon to PNG, JPEG and XPM isn't acceptable.
 2. It could have an option for showing text, icon or both.

I wouldn't close the report if you followed the template and said something like I above. Developers use reports to add features or fix bugs.

Anyway, reopened...

**Comment by stefonarch** [comment]
It could also have an option button to show also bookmarks, with a separator?

**Comment by tsujan** [comment]
I made it so:

![options](https://user-images.githubusercontent.com/981076/156983993-9abc2c86-372c-4dc2-a1ed-16805cf361e4.png)

It also had two bugs, that I fixed. Will make a PR soon.

Other features could be added in separate PRs.

**Comment by stefonarch** [comment]
> Other features could be added in separate PRs.

Like here above "open in terminal" for ebooks probably is useless for  most. A checkbox "Show 'Open in terminal' " and use default terminal instead?

**Comment by ianfarrell47** [comment]
My thought for the Show in terminal being half of the options, it could be moved to a right click option on a label, that label just saying the directory name and opening in the file manager on left click.

**Comment by tsujan** [comment]
> Like here above "open in terminal" for ebooks probably is useless for most.

I'm not sure. Moreover, IMHO, it's good to have it. It doesn't clutter the menu.

**Comment by tsujan** [comment]
> Like here above "open in terminal" for ebooks probably is useless for most.

I'm not sure. Moreover, IMHO, it's good to have it. It doesn't clutter the menu.

**Comment by tsujan** [comment]
Showing bookmarks is somehow problematic. pcmanfm-qt reads bookmarks from the GTK file and writes to it; other file managers may not do that. Since Panel can be used anywhere and because we can't know how the default file manager (which can be different from pcmanfm-qt) saves bookmarks, we have nothing solid to start with.

**Comment by stefonarch** [comment]
I see, thought this was kind of standard, similar to `~/.local/share/filemanager/actions`.

**Comment by tsujan** [comment]
I'm not sure that `~/.local/share/filemanager/actions` is a standard anymore. Its detailed documentation (for Nautilus) has been removed from the Internet. I think GNOME devs may remove this feature from their FM (or have they already done so?), like they've remove other useful features from their DE. However, we use it and have our own doc (→ https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions).

**Comment by stefonarch** [comment]
I see thunar using both bookmarks and actions, dolphin I've no idea.

**Comment by tsujan** [comment]
BTW, and in case you're worried, we don't depend on an external implementation for custom actions. So, whatever GNOME devs do (or has done), it won't affect us.
