### ISSUE TITLE
[Feature request] Scalable buttons in a proportionally equal manner

### ISSUE THREAD

**Issue by GreenLunar** [lxqt/lxqt-panel#1732]
Please observe the following setup:

Single row
![single_row](https://user-images.githubusercontent.com/2053884/157389443-0428edf8-2c0c-490c-a750-b4b64400ba80.png)
![single_row_config](https://user-images.githubusercontent.com/2053884/157389459-f67a7a71-17da-4aae-9ec8-d780b4cbfdad.png)

Double row
![double_row](https://user-images.githubusercontent.com/2053884/157389505-fe989dba-95a2-43c0-8c6a-4860c559bfba.png)
![double_row_config](https://user-images.githubusercontent.com/2053884/157389510-6353f509-6f14-48bd-a790-cb83235ef2e6.png)

I want the icon of the application button (one the left) to be scalable (currently, all I can do to keep it a square, is add text or spaces to it, but I don't want to, because I want to see the icon alone.

I want the show desktop icon on the right to expand on two rows and also be scalable.
I know it's possible to place another panel plugin  at the same column of the show desktop, but I want only a single button on the right.

Trying to get the old feelngs of the good old KDE3 days (now Trinity or TDE).

**Comment by stefonarch** [comment]
You could use just 2 panel, a short one with one row with only  mainmenu and a second one with double rows, should work fine.

**Comment by GreenLunar** [comment]
Sweet! Looks good.

But it's too much of an effort.  Why can't this be modified in a flexible way?
I want the Applications Menu button to be 25x4, and I don't want to "maneuver" my way into the beautiful (I must say) setup that you've just presented above @stefonarch 

Here's a screenshot from KDE3. It's nice
![image](https://user-images.githubusercontent.com/2053884/157405211-0120ca61-5ad4-4367-9ab0-c74e7f959d40.png)
