### ISSUE TITLE
[Feature request] Quick Launch occupies all column or row even when it has an uneven number of entries

### ISSUE THREAD

**Issue by GreenLunar** [lxqt/lxqt-panel#1733]
Please see screenshots below:
![image](https://user-images.githubusercontent.com/2053884/157392014-94ae53a7-d12e-41f9-8de3-f66018d9777d.png)
![image](https://user-images.githubusercontent.com/2053884/157392042-85dd0b7e-9c7c-43ef-8d81-564e1a829640.png)

Thank you

It's like buying a meal and then seperately charge me on a drink, after you realize that it's not included xD
Got extra space left? Buy more to fill that gap xD

**Comment by palinek** [comment]
The panel is split into horizontal sections (in case of horizontal panel). The rows configuration is then used by the sections/plugins.
