### ISSUE TITLE
Icon size in nsi proxy doesn't follow settings

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1735]
Changing icon size has no effect anymore: 54px, pidgin, nm-applet:
![schermata-03-09-19-07](https://user-images.githubusercontent.com/10681413/157504141-8da7e3fa-9d9c-40b5-8b8e-da110b53a846.png)
Old tray plugin:
![schermata-03-09-19-03](https://user-images.githubusercontent.com/10681413/157504493-4b26df80-f5a0-446a-820e-f71b2a92fdc7.png)

##### Steps to Reproduce (for bugs)

1. add tray plugin
2. open pidgin, nm-applet
3. try big icon sizes in panel settings

##### System Information

* LXQt Version: latest git

**Comment by slidinghotdog** [comment]
It happens with the KDE version too.
