### ISSUE TITLE
statusnotifier: italian translation not displayed anymore

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1737]
Real weird, other languages (en, de, es) are working fine.
* Compiled .desktop file is ok
* .yaml file is ok
```
Desktop Entry/Name: "Area di notifiche"
Desktop Entry/Comment: "Fornisce l'area di notifica (vassoio)"
```
* in Manjaro LXQt 1.0 it's ok
* on my family desktop  still with the old 2-pane settings window the same, also after updating to latest git
* doesn't depend on locale settings (eg in german session all fine)

English:

![schermata-03-10-12-26](https://user-images.githubusercontent.com/10681413/157653211-c6ffaac7-3a8b-4449-9319-84b09fed9576.png)

Italian:

![schermata-03-10-12-27](https://user-images.githubusercontent.com/10681413/157653214-080c45e4-88b6-4156-9387-a30083e890f3.png)

                                          --->
* LXQt Version: latest git

**Comment by tsujan** [comment]
Did you update translations after after recent commits?

**Comment by stefonarch** [comment]
The .yaml files sources changes  are handled by weblate, and there were also none.
It just doesn't make sense. Have to test a clean user, but cannot think of any settings issue.

**Comment by tsujan** [comment]
You test almost every PR. Something may have happened between tests.

I don't install translations (except for lximage-qt, qterminal and libfm-qt) but I'll recompile lxqt-panel with them and report back.

**Comment by tsujan** [comment]
I don't see any difference between it, de and es. Italian:

Italian:

![italian](https://user-images.githubusercontent.com/981076/157701438-9d6e55b3-8a68-4bb4-84a4-41a832ee69e8.png)

German:

![german](https://user-images.githubusercontent.com/981076/157701505-93fcf39c-5f3d-47f9-97cb-f35e2e792812.png)

Spanish:

![spanish](https://user-images.githubusercontent.com/981076/157701570-a25ad12c-d2c2-44b1-8c05-44760e310c29.png)

The widget names aren't translated in any of them, while other parts are. Perhaps translation need update.

**Comment by stefonarch** [comment]
In the list of present panel's widgets  the description is never displayed, it's in the "add widget dialog" where it is not displayed. 

But you don't have any translation of the .yaml files here in those windows, no idea why.
![schermata-03-10-18-29](https://user-images.githubusercontent.com/10681413/157721137-56e7a1f6-627e-46fc-90cc-a087195f1af8.png)

**Comment by tsujan** [comment]
>  .... it's in the "add widget dialog" where it is not displayed.

My previous comment had a screenshot of that dialog. The descriptions weren't translated.

**Comment by stefonarch** [comment]
Nothing is translated between name and description there. Customcommand in italian: the first is displayed in the list of present widget
```
Desktop Entry/Name: "Comando personalizzato"
Desktop Entry/Comment: "Mostra il risultato di un comando da terminale"

```

**Comment by stefonarch** [comment]
Oops, I found it:
" ' " is not allowed here.
```
Name[it]=Area di notifiche
Comment[it]=Fornisce l'area di notifica (vassoio)
```
This works:
```
Name[it]=Area di notifiche
Comment[it]=Fornisce un area di notifica (vassoio)
```

**Comment by tsujan** [comment]
> " ' " is not allowed here.

Why? Apostrophe is allowed in the value of keys in desktop files.

**Comment by stefonarch** [comment]
I've no idea. Looked again in manjaro LXQt 1.0.0

![schermata-03-10-19-48](https://user-images.githubusercontent.com/10681413/157733816-89981f5c-0df1-4c7a-ac3f-ef242f30a12e.png)

**Comment by tsujan** [comment]
Actually, apostrophe is also valid in values of Yaml files.

A bug caused by an update outside LXQt?

**Comment by stefonarch** [comment]
You can test it: insert in any of the name or description an apostrophe and it will stop being displayed, tested with customcommand.desktop

**Comment by tsujan** [comment]
`python-yaml` was upgraded here in 2022-02-25 (5.4.1.1-4 → 6.0-1). Does that have any relevance? Sorry if my question is weird; I don't know about these things.

**Comment by stefonarch** [comment]
I don't think as modifying directly the .desktop file triggers this. 
And: it looks like valid for all .desktop files; example tooltip in mainmenu:
featherpad.desktop: `GenericName[it]=Editor di' testo`  in english, `GenericName[it]=Editor di testo` 
Panel restart is needed.

**Comment by tsujan** [comment]
Confirming. I changed `GenericName=Text Editor` to `GenericName=Text 'Editor` in FeatherPad's desktop file and the tooltip was changed to the value of `comment`, namely, `Lightweight Qt text editor`. I also changed it to `Comment=Lightweight Qt' text editor` and the tooltip disappeared.

**Comment by stefonarch** [comment]
So we need probably a new generic issue, closing this here.

**Comment by tsujan** [comment]
I logged out and logged into KDE. The problem didn't exist there.

We should find the cause. It isn't in lxqt-panel.

**Comment by slidinghotdog** [comment]
Wasn't there a recent change in desktop file parsing to allow Exec arguments to be passed inside single quotes? Is this related?

**Comment by tsujan** [comment]
@stefonarch 
Could you reverse https://github.com/lxqt/libqtxdg/pull/271 and see if it is the cause?

**Comment by tsujan** [comment]
> Wasn't there a recent change in desktop file parsing to allow Exec arguments to be passed inside single quotes?

Yes, it was https://github.com/lxqt/libqtxdg/pull/271. But, *apparently*, it was only about Exec.

**Comment by stefonarch** [comment]
This sounds like bingo!  Just tested in runner, same issue, and reverting this commit all is fine again.

**Comment by tsujan** [comment]
Thanks! I'll look into it soon.

**Comment by tsujan** [comment]
I reversed it and saw that the problem disappeared. Searching for the needle in the haystack....

**Comment by tsujan** [comment]
Fixed :) The problem was that a part of Exec handling leaked into other keys. I made them separate from each other and the problem disappeared.

I'm making a PR....

**Comment by tsujan** [comment]
> My part is done ;)

Not yet. You have to test https://github.com/lxqt/libqtxdg/pull/276.

**Comment by stefonarch** [comment]
Done also that, good night :)

**Comment by tsujan** [comment]
Thanks! Tomorrow, I'll merge it.

Good night!
