### ISSUE TITLE
Missing "clear" button in "add widgets" search field

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1747]
Small issue.

![schermata-03-14-19-10](https://user-images.githubusercontent.com/10681413/158252395-035a4d22-16fa-43bf-8580-f7e0338a6e67.png)

##### Context

Reconfiguring from scratch my panel I had to use backspace always.
##### System Information

* LXQt Version: git, all

**Comment by tsujan** [comment]
This was closed by https://github.com/lxqt/lxqt-panel/commit/0e7fed09d2930d62121f2456d75c3d0d307bdf38, but all Qt line-edits can be cleared by `Ctrl+u`.

**Comment by tsujan** [comment]
Interestingly enough, GTK line-edits have the same shortcut — although GNOME devs might remove it if they know that users like it.

**Comment by stefonarch** [comment]
Talking about adding plugins: it happens still often that after having chosen the plugin I hit "enter" to add it - only that "cancel" is selected by default and not "add". Opinions?

**Comment by tsujan** [comment]
If hitting Enter inside the line-edit closes the dialog, I agree that it isn't good. But it should be fixable without changing the default button (the Close button is the most reasonable choice for the default button).

For it not to be forgotten, please open a feature request. If I'm not busy, I'll check the code.

**Comment by stefonarch** [comment]
Done https://github.com/lxqt/lxqt-panel/issues/1910
