### ISSUE TITLE
[Feature request] autohide: hide with delay

### ISSUE THREAD

**Issue by QiangF** [lxqt/lxqt-panel#1752]
**Is your feature request related to a problem? Please describe.**

I know the old system tray is deprecated, but some apps need it, like udiskie.
Currently when the point is on udiskie icon, it hide too quickly before I can click on it.

**Describe the solution you'd like**

add a delay before autohide again.

**Comment by stefonarch** [comment]
Did you test with latest git?
 https://github.com/lxqt/lxqt-panel/pull/1721

**Comment by QiangF** [comment]
@stefonarch Works like a charm!
