### ISSUE TITLE
[ Bug ] On small screens it is difficult to use the lxqt-panel settings

### ISSUE THREAD

**Issue by Yisus7u7** [lxqt/lxqt-panel#1762]
##### Expected Behavior

It should be comfortably visible and usable lxqt-panel settings. 

##### Current Behavior

On small screens lxqt-panel settings do not display well

Some settings are simply impossible to use.

##### Possible Solution

Make the configuration interface a bit more compact

##### Steps to Reproduce (for bugs)

![Screenshot_20220329-235855](https://user-images.githubusercontent.com/64093255/160754870-812ae9e3-df0f-46fd-80b1-9f7fe345266f.png)

##### System Information

* LXQt Version: 1.0.0
* Distribution & Version: Termux 0.118.0+b94dc7e / Android 8.0
* Qt Version: 5.15.3
* liblxqt Version: 1.0.0

**Comment by tsujan** [comment]
Already fixed. Either use git or wait for LXQt 1.1.0.

**Comment by Yisus7u7** [comment]
> Already fixed. Either use git or wait for LXQt 1.1.0.

If I compile lxqt-panel directly from this repository will already be fixed?

**Comment by tsujan** [comment]
I'm afraid you couldn't compile git lxqt-panel without compiling its git dependencies first. You need git LXQt.

LXQt 1.1.0 will be released in April.

**Comment by Yisus7u7** [comment]
> I'm afraid you couldn't compile git lxqt-panel without compiling its git dependencies first. You need git LXQt.
> 
> LXQt 1.1.0 will be released in April.

Oh ok, I'll wait patiently.

**Comment by tsujan** [comment]
In general, if you like to have the latest changes and fixes as soon as they appear, you'll need git LXQt. Otherwise, LXQt has a new release every ~6 months.

**Comment by Yisus7u7** [comment]
> In general, if you like to have the latest changes and fixes as soon as they appear, you'll need git LXQt. Otherwise, LXQt has a new release every ~6 months.

How do I get the git from lxqt?, or can't you?

**Comment by tsujan** [comment]
If your distro has reliable git LXQt packages, you could use them. Otherwise, staying with the latest release and waiting for the next one is the best approach.

**Comment by stefonarch** [comment]
FYI: new panel config and else https://lxqt-project.org/blog/2022/02/14/lxqt-1.1.0-preview/
