### ISSUE TITLE
Desktop switch: first desktop has allways bold font

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1766]
Doesn'ìt respect theme settings.

##### Expected Behavior

Styling should support bold font for active desktop
##### Current Behavior

Nevertheless what's int the theme specificied, first desktop font is displayed bold always.

##### Steps to Reproduce (for bugs)

1.  Create some desktop, add names
2. Switch between them
 It's true also for numbers but less visible.

##### Context

Testing active desktop highlighting with system theme I stumpled upon that. 
![schermata-3 apr 14:16](https://user-images.githubusercontent.com/10681413/161427644-53665457-1e27-432b-9b0f-f3b040729496.png)

* Distribution & Version: all & every

**Comment by stefonarch** [comment]
Too much theme switching. Restarted panel, reappeared previously  removed empty quicklaunch and issue disappeared...

**Comment by tsujan** [comment]
I was going to investigate it but you saved me ;)

Yes, on-the-fly style/theme/icon-set change isn't always reliable; app restarting is recommended.
