### ISSUE TITLE
Switching Qt styles can cause Application Menu entries to appear extended/stretched, especially when using the Fusion style

### ISSUE THREAD

**Issue by ArrayBolt3** [lxqt/lxqt-panel#1789]
##### Expected Behavior
The entries in the Application Menu should be sized such that there is not too much blank space after the text on the right side of the menu. This should be kept correct regardless of Qt style changes.

##### Current Behavior
If you change the Qt style, the Application Menu items appear to become a bit stretched until you log out and log back in. If the style you select is Breeze or Windows, the Application Menu goes back to normal after logging out and logging back in. However, if the selected style is Fusion, the Application Menu items become stretched even further than they were before logging out and logging back in.

##### Steps to Reproduce
1. Open the Application Menu, hover over Preferences, then LXQt Settings, then click Appearance.
2. Click the Qt style dropdown, then select "Windows".
3. Apply, close, then open the Application Menu. The entries will appear a little bit stretched.
4. Log out and log back in, then open the Application Menu. The entries will have returned to a normal size.
5. Repeat steps 1-4, but select "Fusion" in step 2.
6. After logging out and logging back in, open the Application Menu. The items in the Application Menu will appear quite stretched.

##### System Information
* LXQt Version: 1.1.0
* Distribution & Version: Lubuntu Kinetic Kudu 22.10 Alpha
* Qt Version: 5.15.4
* liblxqt Version: 1.1.0-0ubuntu2

**Comment by tsujan** [comment]
Yes, that's a general problem in Qt: an on-the-fly style change may cause visual issues. And it's not limited Qt stylesheet or sizes of menu-items. What you saw was only a "harmless" issue; there can be serious ones.

Although LXQt might be able to circumvent this specific issue by adding codes to lxqt-panel (and I'm not about that at all), it can't prevent similar problems elsewhere. So, a partial workaround won't be worth the effort.

After you change the Qt style, restart Qt apps to see their *real* appearances with the new style. A logout and login will do that for all apps.

> ... until you log out and log back in

You don't need to log out and log in for that; restarting lxqt-panel from LXQt Session Settings is enough. But logging out and in is good for all Qt apps.

**Comment by tsujan** [comment]
> if the selected style is Fusion, the Application Menu items become stretched even further than they were before logging out and logging back in.

Qt Stylesheet is affected by Qt widget style, and vice versa. That's out of LXQt's control.

Long story short, Qt Stylesheet is a mess. Qt devs are aware of that; see https://bugreports.qt.io/browse/QTBUG-68671

**Comment by ArrayBolt3** [comment]
OK. Just to be clear, the extra stretching occurs *after* logging out and logging back in, and it *only* occurs with the Fusion Qt widget style, not in the other two styles. Just in case that was missed, I wanted to bring it up. But if this is just Qt being Qt, then I guess that's as far as this can go. Thanks for your help!
