### ISSUE TITLE
[Feature request]Exclude applications from taskbar

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1790]
**Is your feature request related to a problem? Please describe.**

Qterminal's drop down window  is always shown in taskbar, from where it's basically never used. 

**Describe the solution you'd like**

An option to exclude some applications from being shown in taskbar could be nice.

**Comment by tsujan** [comment]
It can be done by adding an editable exception list.

But is it so desirable to be worth the extra code and GUI complication? Isn't it the job of WM? KWin can do it (although maybe not for drop-down QTerminal — I haven't tried).

**Comment by stefonarch** [comment]
Kwin can do it, but only for the Plasma panel afaik, I tested it once.
But yes, I don't know how desirable this feature really is.

**Comment by slidinghotdog** [comment]
If the problem is only with qterminal, it can be changed there, i tried here and adding `setAttribute(Qt::WA_X11NetWmWindowTypeUtility);`
 [here](https://github.com/lxqt/qterminal/blob/master/src/mainwindow.cpp#L169) when setting up the window seems to do what u need.

**Comment by stefonarch** [comment]
Hm, doesn't work here (with Kwin)... but would be nice to have.

```
void MainWindow::enableDropMode()
{
    setWindowFlags(Qt::Dialog | Qt::WindowStaysOnTopHint | Qt::CustomizeWindowHint);
    setAttribute(Qt::WA_X11NetWmWindowTypeUtility);

    m_dropLockButton = new QToolButton(this);
```

**Comment by slidinghotdog** [comment]
Xfwm here, you could also try Qt::WA_X11NetWmWindowTypeDock or
Qt::WA_X11NetWmWindowTypeMenu  these 2 also skipped taskbar but the terminal didn't get focused when opening... Other than these i think it would need to use with xlib or xcb and that's probably not desirable.

**Comment by tsujan** [comment]
> Other than these i think it would need to use with xlib or xcb and that's probably not desirable

I agree. Setting attributes may have unpredictable side effects too.

I think the cleanest way of doing it is adding support for an editable exception list to lxqt-panel's Task Manager.

**Comment by stefonarch** [comment]
Not focus and no input too...

**Comment by slidinghotdog** [comment]
> adding support for an editable exception list to lxqt-panel's Task Manager.

This shouldn't be too hard to add, but qterminal has to change window class/classname for the taskbar to filter only the dropdown window.

**Comment by tsujan** [comment]
> qterminal has to change window class/classname for the taskbar to filter only the dropdown window.

Right.

**Comment by stefonarch** [comment]
Well, that is closed by using layershell for the dropdown terminal ;)
