### ISSUE TITLE
world clock applet does not respect the language

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-panel#1793]
I installed Lubuntu 22.04 in French, with French keyboard, but without using a French keyboard, but a German keyboard. After the installation I wanted to let appear in the world clock applet the date with the weekday, like Sunday. Now in the panel the weekday does appear, but the language is in German. Also the month is in German. I don't where that German comes from, because the whole system is in French.
Those are my personalized settings in the world clock applet:
```
dddd d MMM '&#160;<b>'HH:mm'</b>'
```
##### System Information
Lubuntu 22.04
LXQt 0.17.0

**Comment by tsujan** [comment]
LXQt 0.17.0 is outdated.

**Comment by stefonarch** [comment]
Check in locale settings if everything is set to french. Keyboard setting shouldn't influence that at all.

**Comment by ralf3u** [comment]
>Check in locale settings if everything is set to french.

You are right. The problem was in the local settings. But I have no idea why German was active.
Thank you for your help.

**Comment by palinek** [comment]
> But I have no idea why German was active.
Ref. #1489, #1739

**Comment by ralf3u** [comment]
Today I think that I know why the world clock applet was in German: Because just before the installation of Lubuntu 22.04 started, I selected Berlin as time zone, and not Paris.

**Comment by ralf3u** [comment]
I have a suggestion for improvement, but I don't know if it is the right place to mention it here: If during the installation process one select a system language (or keyboard layout?), then it should have automatically an effect on the "LXQt Locale Confuguration" in the "Detailed Settings", so the town for the world clock applet during the installation process should not have an impact on the "LXQt Locale Confuguration" in the "Detailed Settings".
