### ISSUE TITLE
[Feature request] [panel] quicklaunch - update file as soon as it has been modified

### ISSUE THREAD

**Issue by Loader009** [lxqt/lxqt-panel#1795]
**Is your feature request related to a problem? Please describe.**

In short: modifying the .desktop file does not update the quicklaunch object in the panel.

**Describe the solution you'd like**

Either an automatic reload of the quicklaunch objects on changes (not possible for every filesystem) or
an option to manually reload (without stop/start) all quicklaunch objects.

**Describe eventual alternatives you've considered**

Manually stop/start panel via "LXQt Session Manager" - but some "Status Notifier" Icons might disappear, so this is not a wishful solution.

##### Context

I use .desktop items for quicklaunch with several "Desktop Action" profiles. e.g.:
- firefox profiles
- directory paths (file manager)
- scripts

Sometimes I need to update the .desktop files for more directories or such.

LXQt Version: 1.1.0
dist: Arch Linux
packet installed from community-repo

**Comment by tsujan** [comment]
> but some "Status Notifier" Icons might disappear

The feature request aside, this shouldn't happen, and it doesn't happen here.

**Comment by Loader009** [comment]
> The feature request aside, this shouldn't happen, and it doesn't happen here.

You're right, I just did that and nothing disappeared - the positions changed, maybe I thought it because of that.

**Comment by tsujan** [comment]
Is an implementation like this enough?

![quicklaunch](https://user-images.githubusercontent.com/981076/180039852-4fbe6e63-b7c1-446f-8db8-4275a874d16f.png)

**Comment by Loader009** [comment]
Yeah, I think it's sufficient.

**Comment by stefonarch** [comment]
A nice feature to have!

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/lxqt-panel/pull/1796

I used "Refresh" for the text because "Update" and "Reload" we ambiguous.
