### ISSUE TITLE
[Feature request] allow binding win key to open menu without interfering with other WM win+<key> binds

### ISSUE THREAD

**Issue by rkitover** [lxqt/lxqt-panel#1798]
**Describe the solution you'd like**
I would like to be able to bind the Win key by itself to open the taskbar menu, but still allow other Win key bindings with other keys to work for session and openbox/other-WM.

**Describe eventual alternatives you've considered**
I can bind some other key to do this, like Win+Q.

#### Context
Desktops like Windows and KDE support this behavior and I'm very used to it.

**Comment by rkitover** [comment]
Now that I think about this more, maybe this feature should be in lxqt-globalkeys, to allow for catching a single key press and release event with no other keys pressed.

**Comment by stefonarch** [comment]
This is already the case: menu opens when Super_L is released with no other keys pressed.
Which version are you using

**Comment by rkitover** [comment]
I have lxqt-panel 1.1.0 and lxqt-session 1.1.1 from Gentoo.

When I bound Super_L to the menu in the key binder, it worked, but it blocked all other hotkeys using Super_L.

**Comment by stefonarch** [comment]
No idea than, maybe the WM? Although the  naming for the same key is different in lxqt-globalkeys: Super_L for the menu, meta for other applications.

![screenshot-7fa32a47](https://user-images.githubusercontent.com/10681413/180597005-b316ab3d-0104-4267-865d-8b6386bac409.png)

**Comment by rkitover** [comment]
Where do you have this binding by default? What handles Super_L by itself opening the menu?

**Comment by stefonarch** [comment]
31 of the list above  is one  default, the others are created by me in lxqt-globalkeys, which shows also `Super_L  - show/hide main menu`.

**Comment by rkitover** [comment]
I did some testing. When I bind `Super_`L to show/hide main menu and other win key combinations in `lxqt-globalkeys`, such as `Meta+T` to open QTerminal, both keybinds work fine.

However, none of my win key using keybinds in Openbox work anymore, such as `Win-Right` to tile right.

When I bind only keybinds that use the win key with another key in `lxqt-globalkeys` such as `Meta+T`, it does not break my Openbox keybinds.

Which WM are you using?

**Comment by stefonarch** [comment]
That's was I suspected:

> maybe the WM?


> Which WM are you using?

Kwin

**Comment by rkitover** [comment]
Thanks for your help, I'd like to fix this regardless, especially as Openbox is the default WM for LXQT. I'll follow up in the `lxqt-globalkeys` repo.

**Comment by stefonarch** [comment]
> especially as Openbox is the default WM for LXQt

That statement is hard to estinct - there is no default one, distro will chose  one, most  need some hacking and have some ups and owns.
https://github.com/lxqt/lxqt/wiki/ConfigWindowManagers

**Comment by rkitover** [comment]
Let's just say historically and still commonly. I'm personally OK with Openbox and have little reason to switch to anything else right now.

**Comment by rkitover** [comment]
Opened: https://github.com/lxqt/lxqt-globalkeys/issues/259

**Comment by rkitover** [comment]
I'm playing with a WM called JWM right now, it seems promising but I need to spend some time configuring it properly. Of all the WMs I looked at, it is the most actively maintained. It seems to work fine with LXQT too once you change a couple of the default settings.

**Comment by rkitover** [comment]
@stefonarch I wanted to ask you, are you sure that when you have the `Super_L` binding active in `lxqt-globalkeys` that KWin keybindings that use the Win key and some other key are working properly? I'm starting to think that this can't work in any WM.

**Comment by stefonarch** [comment]
Yes, looks like none of them are working.
