### ISSUE TITLE
Cycling windows with mouse wheel isn't working (anymore?)

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1800]
I remember this setting in taskbar plugin working like that. Now it mostly toggles "urgent" styling also in apps which have no urgent messages.
I see that using xfmw4 it works.

##### Expected Behavior

Should move through open windows
##### Current Behavior

Changes one time highlighting then starts to toggle `urgent=true` styles.
##### Possible Solution

* LXQt Version: git, Kwin

**Comment by tsujan** [comment]
Window cycling just activates windows. It's up to the WM and its degree of "focus stealing prevention" to bring that window above others or not. I guess you changed your WM recently.

> Changes one time highlighting then starts to toggle urgent=true styles.

That's the correct behavior. Nothing else can be done.

**Comment by tsujan** [comment]
@stefonarch, can this be closed?

**Comment by stefonarch** [comment]
I don't think so. The text in the setting and what user expect isn't what happens when using kwin. But there's maybe no solution.

**Comment by tsujan** [comment]
> what user expect isn't what happens when using kwin

The windows *are* cycled. If the user expects that the desktop should change and the active window should come to the front, he'll need to change KWin's settings. *We can do nothing about it.*

**Comment by stefonarch** [comment]
Looks like outdated, it works fine on labwc and kwin_wayland (all desktops) and sway (changing focus), also fine with kwin_x11 in debian.

**Comment by Chiitoo** [comment]
Perhaps related?

- https://github.com/lxqt/lxqt-panel/commit/03168aa69f7b21b29ec9cb89f4b111199e4134aa

**Comment by stefonarch** [comment]
Looks like :)
