### ISSUE TITLE
no Installing-window in the panel of Startup Disk Creator

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-panel#1813]
steps to reproduce
1: Main menu, System Tools, open Startup Disk Creator
2: Click on Start Startup Disk (result: after the password, an Installing-window will appear)

problem:
no Installing-window in the panel, although an Installing-window exists

expectation:
there should be an Installing-window in the panel because an Installing-window exists

system information
Lubuntu 22.04
LXQt 0.17.0

My LXQt is old although I use Lubuntu 22.04. If the issue does not appear in LXQt 1.1.0 any more, then I’m sorry for this report.

**Comment by stefonarch** [comment]
Looks outdated, Lubuntu 22.04/LXQt 1.2

![screen_area_dom_16:50:01_](https://github.com/lxqt/lxqt-panel/assets/10681413/64f5309f-535a-4909-9469-ff943edc6f88)

**Comment by ralf3u** [comment]
>Looks outdated, Lubuntu 22.04/LXQt 1.2

That's not true. I just tested it in Lubuntu 23.04 in LXQt 1.2.0.
The image you are showing in the last comment is the wrong image. To see the issue: Click on "Make Startup Disk", then click on "Yes", then type your password. Then the Installing-window will appear (see report on top of this webpage). The title of that window is "Installing". That window has the typical three icons on the right side of the window-bar for closing the window, for minimizing the window and for maximizing the window. Inside the window there is this text:

Writing disk image ...
...%
Cancel

But there is still no Installing-window in the panel.

Could you please reopen this issue?

**Comment by ralf3u** [comment]
My personal opinion is: In the moment where I see the three icons in the window-bar for closing/minimizing/maximizing, I expect that the application also appears in the panel.
I intend to report the bug at https://bugs.launchpad.net/usb-creator.
