### ISSUE TITLE
Plugin volume opens at center under wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1815]
![screen_gio_21:45:05_](https://user-images.githubusercontent.com/10681413/190495642-578bf640-b0d3-43e8-8c0a-2b15ae20b141.png)

##### Expected Behavior

Opens at position
##### Current Behavior

Opens at center.
##### Possible Solution

Use code from backlight plugin which works?

![screen_gio_21:46:36_](https://user-images.githubusercontent.com/10681413/190495655-f5821482-b4b1-4004-9b42-07e535375dff.png)

* LXQt Version: latest git, arch
* Wayland

**Comment by tsujan** [comment]
Not LXQt's fault.

Under Wayland, no app can set its window position or activate/raise its window. The Wayland WM is the dictator ;)

Of course, if the app contains Wayland codes, it could manages its windows, but can't decide now whether we should use `wlroots` or not.

**Comment by tsujan** [comment]
> Use code from backlight plugin which works?

Yes, that might be a workaround; hence keeping this open.

**Comment by stefonarch** [comment]
The issue can be seen again, it opens at different positions, partially due to window rules, while brightness slider or calendar always open at the correct position.

https://github.com/lxqt/lxqt-panel/issues/1839

**Comment by stefonarch** [comment]
The point is that brightness slider works and volumecontrol not.

**Comment by tsujan** [comment]
I understand your point, but the code of volume popup is different, although valid. The fact that you see the issue *again* may point to a change of behavior in the Wayland compositor you use.

Anyway, there's no harm in leaving this page open.

**Comment by stefonarch** [comment]
I think it was always here after reverting it partially, because I use always keys. Will add screenshots without any window rules, as you can see it has also a title. Brightness is perfect. This code IMO can never be used under wayland.

sway:
![screen_area_lun_12:54:31_](https://user-images.githubusercontent.com/10681413/216965279-e78df01e-df2d-4812-9ff5-41120a2fc4e5.png)

**Comment by tsujan** [comment]
Your screenshot shows that the window ID of the popup is "lxqt-panel". Therefore, when you set a rule for "lxqt-panel", it affects that window too.

In other words, the problem seems to be in the Wayland compositor: it lacks a criterion for distinguishing between a panel and a popup.

**Comment by stefonarch** [comment]
As I said, those screens are without any rules, which in some cases can remove title and border. The overall issue is that the window role for the panel is "window".

**Comment by tsujan** [comment]
> As I said, those screens are without any rules

It makes no difference. The compositor doesn't acknowledge that the popup is a child of the panel. A child widget should be positioned relative to its parent — like menus, that are positioned relative to their parent widgets — but, in this case, it isn't.

**Comment by stefonarch** [comment]
I looked at the diff between volume and brightness slider -  the latter isn't seen as a window:
```

#6: workspace "3: Git"
      #5: con "stef@archlinux: ~" (xdg_shell, pid: 390860, app_id: "qterminal")
      #9: floating_con "LXQt Panel" (xdg_shell, pid: 390844, app_id: "lxqt-panel")
      #28: floating_con "lxqt-panel" (xdg_shell, pid: 390844, app_id: "lxqt-panel")
```

```
#6: workspace "3: Git"
      #5: con "stef@archlinux: ~" (xdg_shell, pid: 390860, app_id: "qterminal")
      #9: floating_con "LXQt Panel" (xdg_shell, pid: 390844, app_id: "lxqt-panel")
```

**Comment by tsujan** [comment]
I don't want to bother you with tests that might have no result, but here is an idea: what if we change https://github.com/lxqt/lxqt-panel/blob/a8580adf4ef87a42d3477cd8faed5b453f4cff12/plugin-volume/lxqtvolume.cpp#L60 to:

```c++
m_volumeButton = new VolumeButton();
```

**Comment by stefonarch** [comment]
Negative:
```

78%] Building CXX object plugin-volume/CMakeFiles/volume.dir/lxqtvolume.cpp.o
/home/stef/git/lxqt/lxqt-panel/plugin-volume/lxqtvolume.cpp: In constructor ‘LXQtVolume::LXQtVolume(const ILXQtPanelPluginStartupInfo&)’:
/home/stef/git/lxqt/lxqt-panel/plugin-volume/lxqtvolume.cpp:60:39: error: no matching function for call to ‘VolumeButton::VolumeButton()’
   60 |     m_volumeButton = new VolumeButton();
      |                                       ^
In file included from /home/stef/git/lxqt/lxqt-panel/plugin-volume/lxqtvolume.cpp:30:
/home/stef/git/lxqt/lxqt-panel/plugin-volume/volumebutton.h:43:5: note: candidate: ‘VolumeButton::VolumeButton(ILXQtPanelPlugin*, QWidget*)’
   43 |     VolumeButton(ILXQtPanelPlugin *plugin, QWidget* parent = nullptr);
      |     ^~~~~~~~~~~~
/home/stef/git/lxqt/lxqt-panel/plugin-volume/volumebutton.h:43:5: note:   candidate expects 2 arguments, 0 provided

```

**Comment by tsujan** [comment]
Yes; I didn't check the code.

`m_panel` is redundant in `VolumeButton`. It may be the cause (I sent you a patch for its removal with email but wanted to mentation it here too).
