### ISSUE TITLE
panel 1.2 volume widget loose focus.

### ISSUE THREAD

**Issue by ringo32** [lxqt/lxqt-panel#1838]
Endeavouros / Archlinux based

when click on the widget of volume, using the keyboard widget loose focus. in panel 1.1 it worked

(thhis report is for someone else.)
##### Expected Behavior

when click on the widget  using the arrows the volume should not loose focus
##### Current Behavior

click on the widget when tab the key widget loose focus.

##### Possible Solution

i dontg know ...
##### Steps to Reproduce (for bugs)

1.
2.
3.
4.

##### Context
fairly to say it is a report for someone else., but it loose here also focus. but doesnt bother me.
he downgraded the panel to 1.1 and seems to work again.

##### System Information

* LXQt Version:
* Distribution & Version:
* Qt Version:
* liblxqt Version:
further archlinux based endeavouros..

**Comment by tsujan** [comment]
The same as https://github.com/lxqt/lxqt-panel/issues/1839
