### ISSUE TITLE
[Feature request] Mute-symbol per task-button in the task-panel when playing audio

### ISSUE THREAD

**Issue by ProfP30** [lxqt/lxqt-panel#1843]
**Is your feature request related to a problem? Please describe.**
When playing audio, it would be great to have an indicator per application in the panel to see on first sight which program is currently playing.

**Describe the solution you'd like**
Clicking once should mute this application only, clicking again should un-mute the program
When it stops playing, the indicator should disappear at all.

**Describe eventual alternatives you've considered**
Alternative: right-click the task button and select "Mute" and "Un-mute" if already muted.

#### Context
Enhance usability and increase attraction of the LXQt DE.
(This functionality already possible since a long time in other Desktop Environments.)

**Comment by tsujan** [comment]
Task Manager's job has nothing to do with multimedia.

**Comment by tsujan** [comment]
Also see https://github.com/lxqt/lxqt-panel/issues/1673
