### ISSUE TITLE
Problems with styling ColorPicker, Backlight, KbIndicator, and StatusNotifier

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt-panel#1845]
While working on `KDE-Plasma/lxqt-panel.qss` I noticed some issues with a few panel plugins.

- ColorPicker and Backlight should set `setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);`.
- KbIndicator's #LayoutLabel can change size when changing locales.
- StatusNotifier does not `setObjectName` for the buttons, so they are only themeable generically.

This is an edited KDE-Plasma theme with `QLabel, QToolButton { background: rgba(0, 0, 0, 30%); }` demonstrating these issues (Icon size is increased/decreased.)

https://user-images.githubusercontent.com/96850319/207727691-3e4c10dd-1aa1-45f5-a650-7ed960b8ef2a.mp4

**Comment by ianfarrell47** [comment]
@tsujan - any ideas on how to set a constant width for KbIndicator's m_layout? Relevant source: [plugin-kbindicator/src/content.cpp](https://github.com/lxqt/lxqt-panel/blob/e6a20d3278678b3584a80df9b34afffa7f48f9cd/plugin-kbindicator/src/content.cpp)

**Comment by ianfarrell47** [comment]
For ColorPicker and Backlight, `setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding)` enables the KDE-Plasma theme to have "overbars" on those widgets for icon sizes smaller than the panel size. For StatusNotifier, `setObjectName` for the button widgets likewise enables overbars.

KbIndicator's layout button ideally would be set to a constant width, to prevent other panel widgets from shifting.

**Comment by tsujan** [comment]
A constant width for KbIndicator would be a bad bug; I explained why above.

As for the others, changing the code for just one theme isn't good. Not all widgets need to be styled.

**Comment by ianfarrell47** [comment]
A constant width for the indicator tool-button wouldn't be a bug. It would prevent widgets from being shifted, in all themes.

**Comment by tsujan** [comment]
A constant width for a tool button with a variable text is a bug everywhere, not just for an indicator.
