### ISSUE TITLE
RFC: add a border around the panel

### ISSUE THREAD

**Issue by kreijack** [lxqt/lxqt-panel#1848]
**Is your feature request related to a problem? Please describe.**
I find eye friendly (take in account that I am 50, so may be I need more contrast) a black border around the panel because it allows me to understand where the panel ends and where background start.

**Describe the solution you'd like**
With a border
![image](https://user-images.githubusercontent.com/4663983/208748710-2119ae2b-e1f2-412c-926b-baad7ba13816.png)
                                          
Without a border
![image](https://user-images.githubusercontent.com/4663983/208748637-0bfa4eb6-9a8e-4695-af75-acd2e43997b0.png)

From a code point of view it is enough the following diff to enable a border around the panel.

```
$ git diff
diff --git a/panel/lxqtpanel.cpp b/panel/lxqtpanel.cpp
index d2916b63..093751ed 100644
--- a/panel/lxqtpanel.cpp
+++ b/panel/lxqtpanel.cpp
@@ -177,6 +177,7 @@ LXQtPanel::LXQtPanel(const QString &configGroup, LXQt::Settings *settings, QWidg
 
     //LXQtPanel (inherits QFrame) -> lav (QGridLayout) -> LXQtPanelWidget (QFrame) -> LXQtPanelLayout
     LXQtPanelWidget = new QFrame(this);
+    LXQtPanelWidget->setFrameShape(QFrame::Box);
     LXQtPanelWidget->setObjectName(QStringLiteral("BackgroundWidget"));
     QGridLayout* lav = new QGridLayout();
     lav->setContentsMargins(0, 0, 0, 0);

```

If you like the idea, I can arrange a more complete patch with a setting in the `configure panel` dialog.

**Comment by stefonarch** [comment]
This could also be done by themes.  Issues are

* color of border,  it could be invisible with some themes
* Only a border on top is really needed but what about panels at the top of the screen, or vertical panels?  A bright border on every side would be ugly with dark themes.

**Comment by kreijack** [comment]
>     * color of border,  it could be invisible with some themes
I agree; the background color may be changed, the same should be for the border-> the user can select 
- if the border exist ta all
- which color (with a sane default eg: dark gray for a "light" color, and light gray for  a "dark" color)

>     * Only a border on top is really needed but what about panels at the top of the screen, or vertical panels?  A bright border on every side would be ugly with dark themes.

Yes this make sense; I add that if the panel is not "full width", the border should be also present to the left/right border (if horizontal, top/bottom for a vertical panel).

**Comment by tsujan** [comment]
Since this can already be done in the theme, I think adding code for it isn't good.

**Comment by kreijack** [comment]
Could you point me how an user can add a "border" using a theme ?

**Comment by kreijack** [comment]
Sorry ignore my request, I find where the temes are

**Comment by tsujan** [comment]
It can be done in the most flexible way by putting a theme inside `~/.local/share/lxqt/themes/` and adding border to the `LXQtPanel` block(s). Please note that the user themes override root themes with the same name.

LXQt tries not to clutter config dialogs.
