### ISSUE TITLE
Xfwm4 fullscreen programs don't obscure lxqt-panel on certain setups

### ISSUE THREAD

**Issue by isf63** [lxqt/lxqt-panel#1855]
Per discussion at the end of #1850.

@stefonarch reports this bug doesn't appear.

I checked and didn't find any relevant settings in `xfwm4-settings`, `xfwm4-tweaks-settings`, and `xfwm4-workspace-settings`.
___

xprop info for panel: [xprop-lxqt-panel.txt](https://github.com/lxqt/lxqt-panel/files/10345096/xprop-lxqt-panel.txt)

xprop info for Qterminal dropdown fullscreen: [xprop-qterminal-dropdown-fullscreen.txt](https://github.com/lxqt/lxqt-panel/files/10345132/xprop-qterminal-dropdown-fullscreen.txt)

**Comment by tsujan** [comment]
This is strange to me, from `xprop-lxqt-panel.txt`:
```
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_ABOVE, _NET_WM_STATE_FOCUSED
```
It explains why the panel is on the top but, as far as I know, we don't set it.

@yan12125, do you know where it comes from? Mine is empty with KWin:
```
_NET_WM_STATE(ATOM) =
```

**Comment by stefonarch** [comment]
I see the same line with `NET_WM_STATE_ABOVE` in my debian virtual machine, and also the bug is there with lxqtpanel 1.2.0. Will check in a lxqt-session now.

**Comment by stefonarch** [comment]
I see the same line with `NET_WM_STATE_ABOVE` in my debian virtual machine, and also the bug is there with `lxqt-panel 1.2.0`. 

On arch with` lxqt-panel 1.2.1` I get

`_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_FOCUSED
`

**Comment by tsujan** [comment]
@stefonarch 
Then it may be caused by the default settings of xfwm4 under Debian. Would you please search for a suspicious xfwm4 setting/option — anything about staying on top?

**Comment by tsujan** [comment]
Oh, you said you saw the issue with 1.2.0. Well, the whole point of 1.2.1 was circumventing it. Do you see `NET_WM_STATE_ABOVE` under Debian *with 1.2.1*?

**Comment by stefonarch** [comment]
Will compile it, don't remember if I've everything  in place still, will check on the main PC.

**Comment by tsujan** [comment]
@Will compile it

Sorry, I'm a little confused. Is Debian important in this report? @isf63 didn't say anything about Debian.

**Comment by stefonarch** [comment]
He's on arch afaik, the question would be why and how xfwm4 set those variables. Probably distros aren't important. Just saw that panel 1.2.1 is uploaded in debian unstable now - this means it will arrive soon in testing/sid.

**Comment by stefonarch** [comment]
Just had a look at Lubuntu with 1.2 with openbox as in the report here, including the `_NET_WM_STATE_ABOVE` but F11 is working normally covering the panel.

**Comment by tsujan** [comment]
> Probably distros aren't important.

Right. Perhaps a setting in xfwm4.

> Just had a look at Lubuntu with 1.2 with openbox,

Only the new version of xfwm4 has this issue, which shouldn't happen with lxqt-panel 1.2.1. So far, only @isf63 sees it with 1.2.1.

> With KWin+debian and lxqt-panel 1.2.0 I get...

Yes, but like Openbox, KWin never had this problem.

**Comment by yan12125** [comment]
No idea why `_NET_WM_STATE_ABOVE` is still there...

As a record, in https://github.com/lxqt/lxqt-panel/pull/1850, I found the relevant code in lxqt-panel by breaking at `xcb_change_property` in gdb.

**Comment by tsujan** [comment]
> No idea why _NET_WM_STATE_ABOVE is still there...

You don't mean it is there for you too; do you?

**Comment by yan12125** [comment]
No, I don't get `_NET_WM_STATE_ABOVE` from the latest lxqt-panel on my machines. I have no idea why that flag still appears in the reporter's panel.

**Comment by stefonarch** [comment]
I compiled the panel on debian, with kwin the line is now empty too as with @tsujan, with xfwm4 `_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_FOCUSED ` and fullscreen is ok as expected.

**Comment by tsujan** [comment]
So, it's reasonable to say that some piece of information is missing from this report. May guess is that it's about xfwm4's settings.

**Comment by isf63** [comment]
Oddly enough, this bug is absent when compiling lxqt-panel 1.2.1 myself.

**Comment by IS4M1RI** [comment]
i have same problem, when i set fullscreen video, is behind the taskbar
