### ISSUE TITLE
Pop-up positions on wayland only correct for top panel

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1858]
The only way to use the panel under wayland atm is with "top" position - with left|right|bottom position opens all popups at the opposite part of the screen or  mostly out of the screen.

##### Steps to Reproduce (for bugs)

1. Open a panel under wayland, it will open at center screen
2. set position to "bottom"
3. click "configure panel", or volume or brightness
4.  move the panel to the top
5. only now pop-ups can be seen and handled

##### Context

Even without the taskmanager lxqt-panel offers  much and is easier to configure than all other bars/panels. With wayfire-git, [this patch ](https://github.com/WayfireWM/wayfire/issues/1637#issuecomment-1367446334) and  3 window rules it is sticky and on topbut I'm used to a bottom panel.

![screen_area_mar_09:12:37_](https://user-images.githubusercontent.com/10681413/212843902-9ada397a-85cd-47f9-8fb5-601a73b8f1fa.png)

##### System Information

* LXQt Version, OS: git, arch

**Comment by tsujan** [comment]
The reason is that an app can't know about its position on the screen under Wayland. The code always gets (0,0) — even with the bottom panel — and it's correct only with a full-size top panel.

Wayland codes are needed for this, and each Wayland WM has its own code.

**Comment by tsujan** [comment]
A general explanation:

In the name of "security", knowing the position on the screen is the main taboo under Wayland — only the compositor itself has the "right" to know such things.

But apps may break that taboo by including compositor-specific codes. If they do, their codes might not work under another Wayland compositor.

Therefore, an app that needs to know its position, should be DE-specific. Panels are among such apps.

**Comment by tsujan** [comment]
They have `wlroots` codes.

This situation sometimes makes me use swear words. To calm myself down, I see it like a game: "Write codes without knowing about global positions."

However, the game can't be played with all apps, and you should forget about some functionalities in the apps that it can be played with — swear words come handy again.

**Comment by stefonarch** [comment]
For some unknown  reason this is mostly not the case anymore - popup are placed correctly for left panel and overlay a bottom or right panel  (starting from screen edge instead from panel edge.

**Comment by tsujan** [comment]
> For some unknown reason...

It should be due to changes in the code of the Wayland compositor you use, because lxqt-panel is still based on Qt5.

**Comment by stefonarch** [comment]
As I said,  no idea because it's with every compositor now similar, while some config windows before were out of screen or on the adiacent workspace. Maybe wlroots itself?
