### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by gen2brain** [lxqt/lxqt-panel#1866]
I can reproduce this every time I remove the docking from the laptop. I am using the Volume Control widget with plain ALSA. I believe this is related to this widget as my old laptop with identical software is working just fine.

The new ThinkPad universal docking (usb-c/thunderbolt) are not extensions of laptop devices like before, they come with new devices on them, i.e. USB audio, Realtek ethernet, etc. so when docked now you have two audio cards. I guess with sound daemons like PulseAudio you don't have to care, with ALSA, I detect this (whether Dock Audio device is present) on AC event in `acpid` and just toggle adding/removing `/etc/asound.conf` file with this content:
```
defaults.pcm.card 1
defaults.ctl.card 1
```
So in order to use the new card I would have to restart the application, e.g. the browser to take effect of asound.conf.  I don't mind clicking and changing what Volume Control controls, but every time I remove docking the panel will go crazy with 100% CPU usage of the single core and after I stop/start the panel from Session Settings it returns to normal. This happens whether or not I mess with asound.conf, it is not related.

##### System Information
* LXQt Version: 1.2.0
* LXQt Panel Version: 1.2.1
* Distribution & Version: Gentoo
* Qt Version: 5.15.8
* liblxqt Version: 1.2.0

**Comment by palinek** [comment]
Fixed in #2136
