### ISSUE TITLE
Clicking on widget (for plugin-worldclock & plugin-backlight) causes it to stop changing its highlighted appearance when hovered over by cursor until its window is closed

### ISSUE THREAD

**Issue by shai8I** [lxqt/lxqt-panel#1884]
##### Expected Behavior

After clicking on the widget (for plugin-worldclock & plugin-backlight), the widget will continue responding to the cursor movement by appearing highlighted when hovered over and and un-highlighted when un-hovered. 

E.g. plugin-volume:

https://user-images.githubusercontent.com/129856809/229798649-c8cebdd3-df6d-4137-81cd-89a32332e2e8.mp4

##### Current Behavior

After clicking on the widget (for plugin-worldclock & plugin-backlight), the widget no longer changes its highlighted appearance until the window is closed. If the cursor is not on the widget when the window is closed (e.g. clicked elsewhere on screen), then the widget remains highlighted until the cursor returns to it.

E.g. plugin-worldclock

https://user-images.githubusercontent.com/129856809/229798661-6587c27d-5883-45f2-b31a-a09a38c732fe.mp4

##### Steps to Reproduce (for bugs)

1. Click on the widget (of plugin-worldclock or plugin-backlight).
2. Click on the desktop.
3. Observe that the widget remains highlighted.
4. Move the cursor over the widget, then back onto the desktop.
5. Observe that the widget is no longer highlighted.

##### Context

Reason for submitting issue is that when I use plugin-worldclock, I usually close the window by clicking outside of it (and not on the widget itself, causing the widget to remain highlighted).

##### System Information

* LXQt Version: 1.2.0
* Qt Version: 5.15.7
* liblxqt Version: 1.2.0

(Recordings taken from LXQt version 0.16.0.)

**Comment by tsujan** [comment]
An old Qt bug, which can be seen in Qt's stylesheet style but isn't limited to it.

**Comment by tsujan** [comment]
Also see https://github.com/lxqt/lxqt-panel/issues/1688 for another kind of it, which was fixed.
