### ISSUE TITLE
Closing widget's window (for plugin-worldclock & plugin-backlight) by tapping on the touchscreen causes lxqt-panel to no longer respond to touch input

### ISSUE THREAD

**Issue by shai8I** [lxqt/lxqt-panel#1885]
##### Current Behavior

After opening a widget's window (for plugin-worldclock & plugin-backlight) either by touch (via touchscreen) or by mouse, closing it by touch causes the panel to no longer respond to any touch input until it is restarted. Closing it by mouse does not cause this. The panel still responds to mouse input after this happens.

##### Steps to Reproduce (for bugs)

1. Tap on plugin-worldclock widget (via touchscreen).
2. Tap on the desktop.
3. Try to tap on widgets or windows from the panel.
4. Observe that the panel no longer respond to touch.

##### Context

When using a touchscreen only, I must not open the window for plugin-worldclock (but it happens sometimes).

##### System Information

* LXQt Version: 1.2.0
* Qt Version: 5.15.7
* liblxqt Version: 1.2.0

**Comment by tsujan** [comment]
This can't be about a bug in lxqt-panel, because lxqt-panel doesn't treat touchscreen devices differently (as it shouldn't).

Whether the problem you see is in Qt or deeper, I don't know.

**Comment by tsujan** [comment]
BTW, if you opened a page at https://github.com/lxqt/lxqt/discussions, it might attract the attention of users with a similar device, and — who knows? — someone may have found the real cause or a workaround.
