### ISSUE TITLE
Application menu shows lots of entries for Flatpak applications

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt-panel#1913]
##### Expected Behavior
Menu contains exactly one entry for application. 

##### Current Behavior
Menu shows lots of entries for Flatpak applications.

![menu-flatpak-dups](https://github.com/lxqt/lxqt-panel/assets/440517/1ae942c9-e3ae-4fcf-8bd4-81fd3e8d76f9)

##### Steps to Reproduce (for bugs)

1. Install some Flatpak application (e.g. Olive, AlizaMS, VSCode, etc.)
2. Open Panel Menu and navigate to the category (Multimedia in the case for Olive)
3. Not sure, but I assume one entry is created when updating via `flatpak update`

##### System Information

* LXQt Version: 1.3
* Distribution & Version: Manjaro

**Comment by tsujan** [comment]
Check all your folders $XDG_DATA_DIRS/applications/. If there are several instances there, the main menu should show them.

**Comment by antis81** [comment]
Only one desktop file in

```
ls /var/lib/flatpak/exports/share/applications

mimeinfo.cache
…
org.olivevideoeditor.Olive.desktop
```

Other than *.desktop files there's this `mimeinfo.cache` file. Is it related?

**Comment by tsujan** [comment]
`/usr/share/applications`, `~/.local/share/applications`,  `/usr/local/share/applications`,  You can open them with pcmanfm-qt and check the icons.

**Comment by antis81** [comment]
Only one. However since we can copy the path from menu via right click this shows something…

```
file:///var/lib/flatpak/exports/share/applications/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/io.freetubeapp.FreeTube.desktop/org.olivevideoeditor.Olive.desktop
```

Whoops… looks like the menu actually breaks in certain situations. :lady_beetle:

**Comment by tsujan** [comment]
What about inside `menu://applications/` in pcmanfm-qt (side-pane → Applications)? It has a different code.

**Comment by antis81** [comment]
Found it! This nasty chain of directories (not files!) actually existed on my system:

```
sudo rm -r /var/lib/flatpak/exports/share/applications/io.freetubeapp.FreeTube.desktop
```

Freetube is not even installed (as flatpak). May be a Flatpak bug, but I couldn't reproduce it…

**Comment by tsujan** [comment]
If those directories were nested `XDG_DATA_DIRS`, the multiplicity may be understandable.
