### ISSUE TITLE
No parameters can be passed to the mixer command

### ISSUE THREAD

**Issue by lherschi** [lxqt/lxqt-panel#1918]
LXQt Version: 1.3.0

No parameters can be passed to the mixer command. This is required, for example, for "pc-mixer -notray" (https://github.com/trueos/pc-mixer). The following commit is responsible for this.

https://github.com/lxqt/lxqt-panel/commit/0b85fcb653c5d311df0dce3868c4bca9c5ca21ef#diff-ad00be5007a526c02451616f63a7ae40bdafd04695cac8eb0cd5af60daaf2a7d

**Comment by stefonarch** [comment]
Confirmed, tested with `pavucontrol-qt -m`

**Comment by lherschi** [comment]
Works great, thanks.

**Comment by stefonarch** [comment]
Confirming, works fine.
