### ISSUE TITLE
Volume Control shows wrong volume when Panel is restarted

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#1928]
It happened when I used PulseAudio, and now it happens with PipeWire. The difference is that, with PulseAudio, the displayed volume was corrected as soon as any app made a sound, but with PipeWire, it isn't corrected automatically; I should change and restore the volume in `pavucontrol-qt` to have a correct value in Volume Control..

Strangely enough, most of the time, when the whole LXQt session is started, the displayed volume is correct, although I've encountered wrong values randomly on logging in too.

For some reason, the wrong value is always 26 here, while I set the volume to 40.

##### Steps to Reproduce (for bugs)

1. Stop and start LXQt Panel in LXQt Session Settings.
2. Check the value of Volume Control.

In my case, it's always wrong, although that was tolerable with PulseAudio for the reason mentioned above.

##### Context

Also, see https://github.com/lxqt/lxqt-panel/issues/1924

##### System Information

* Latest git LXQt on an up-to-date Manjaro Testing

**Comment by isf63** [comment]
Reproducible here on Pipewire: Restarting lxqt-panel changes Volume Control's reported level but pavucontrol-qt remains the same.

**Comment by tsujan** [comment]
After checking the code, I found out that the problem is related to `pulseaudioengine.cpp` → `PulseAudioEngine::addOrUpdateSink` → `pa_cvolume_avg`.

The function `pa_cvolume_avg` has never returned a correct value here — whether with PulseAudio or with PipeWire— and it isn't used in `pavucontrol-qt`. With PulseAudio, the problem of `pa_cvolume_avg` is compensated for as soon as a sound in produced by any app; with PipeWire it isn't.

**Comment by tsujan** [comment]
At last, the following patch fixed this old issue for me:

```diff
diff -ruNp lxqt-panel-orig/plugin-volume/pulseaudioengine.cpp lxqt-panel/plugin-volume/pulseaudioengine.cpp
--- lxqt-panel-orig/plugin-volume/pulseaudioengine.cpp
+++ lxqt-panel/plugin-volume/pulseaudioengine.cpp
@@ -213,7 +213,7 @@ void PulseAudioEngine::addOrUpdateSink(c
 
     pa_volume_t v = pa_cvolume_avg(&(info->volume));
     // convert real volume to percentage
-    dev->setVolumeNoCommit(qRound((static_cast<double>(v) * 100.0) / m_maximumVolume));
+    dev->setVolumeNoCommit(qRound((static_cast<double>(v) * 100.0) / PA_VOLUME_NORM));
 
     if (newSink) {
         //keep the sinks sorted by index()

```

@isf63, since you can also reproduce the issue, could you please try the patch?

@palinek, do you know why `m_maximumVolume` results (or can result) in an incorrect value inside `PulseAudioEngine::addOrUpdateSink`?

Also, I was wrong about `pa_cvolume_avg`; it wasn't the culprit.

**Comment by isf63** [comment]
The patch works and makes lxqt-panel Volume Control's reported level equal to pavucontrol-qt. When not patched: pavucontrol-qt=36% and Volume Control plugin=24%.

**Comment by tsujan** [comment]
@isf63, thanks!

It remains to know why `m_maximumVolume` works in `PulseAudioEngine::commitDeviceVolume` and whether the patch needs to cover more details. I haven't worked with PulseAudio functions before, but the PulseAudio reference looks good.

**Comment by palinek** [comment]
There is a configuration option "Allow volume beyond 100% (0dB)", which allows the plugin to set the volume over 100%. But the plugin always shows values 0 ~ 100. So with the above flag enabled I can see here pavucontrol 100% == plugin-volume 66%.
I considered this as the desired behavior.

**Comment by tsujan** [comment]
> I considered this as the desired behavior.

It may be the desired behavior when that option is set. But this bug is about its default value (`false`). Showing 100% as %60% when that option is *not* set is not only confusing but also inconsistent because it'll be corrected as soon as the volume changes.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lxqt-panel/pull/1929
