### ISSUE TITLE
[Feature request] plugin-volume: Allow mousewheel volume change on top of taskbar icon while plugin window is active

### ISSUE THREAD

**Issue by isf63** [lxqt/lxqt-panel#1939]
Currently there are two ways to use the mousewheel with plugin-volume:
1. Open the plugin window and scroll on top of the QSlider.
2. Scroll on top of the panel icon while the plugin window is not open.

**Describe the solution you'd like**
From a UX perspective, the panel icon should have scrollable volume while the plugin window is open. This provides visual feedback from the QSlider, instead of purely reading numbers from the tooltip.

**Describe eventual alternatives you've considered**
Nothing else in particular. An additional feature request (for when the plugin's window is active) would be to have a bold QLabel with the volume level inside the window, instead of a tooltip.

#### Context
Sometimes I click plugin-volume's icon and scroll the mousewheel, which does nothing.

**Comment by tsujan** [comment]
> the panel icon should have scrollable volume while the plugin window is open

Neither possible (because the window is a popup), nor needed (the wheel works on the slider).
