### ISSUE TITLE
[Feature request] Search also for keywords in mainmenu

### ISSUE THREAD

**Issue by pykereaper** [lxqt/lxqt-panel#1946]
**Is your feature request related to a problem? Please describe.**

According to the [Freedesktop Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys), the `Keywords` field in a `.desktop` file can be used "_to facilitate searching through entries_":

>  A list of strings which may be used in addition to other metadata to describe this entry. This can be useful e.g. to facilitate searching through entries. The values are not meant for display, and should not be redundant with the values of `Name` or `GenericName`.

Currently, the `mainmenu` component of lxqt-panel doesn't search for keywords in `.desktop` files.

You can test it yourself e.g. with the Geany application. Its `.desktop` file contains `Keywords=Text;Editor;`.
However, when you search in the lxqt `mainmenu` for "_editor_", Geany won't show up.

**Describe the solution you'd like**
I think it would be best to follow the Freedesktop suggestion to use the keywords for searching by default and always.

If I'm not mistaken, this would be a really quick addition in [this code block](https://github.com/lxqt/lxqt-panel/blob/56dcefe336ad49c1969c9dc5ed3d7c4f86780d9d/plugin-mainmenu/actionview.cpp#L65C17-L65C17). Something like:

```cpp
QStringList keywords = df.localizedValue(QLatin1String("Keywords")).toString().split(QLatin1Char(';');
for (const QString &keyword : keywords)
{
    if (keyword.contains(filterStr_, filterCaseSensitivity()))
        return true;
}

```

**Describe eventual alternatives you've considered**
Alternatively, an option in the `mainmenu` Widget settings to enable searching for keywords would be a way to provide both old and new behavior.

#### Context

Btw: Using the entries from `Keywords` for application search is the default behavior e.g. in Gnome.

**Comment by tsujan** [comment]
LXQt Runner can be used for that.

**Comment by pykereaper** [comment]
> LXQt Runner can be used for that.

That's not true. I just tested it in LXQT Runner, again with the search term `editor`. No "Geany" is suggested.

---

Here's proof in code: https://github.com/lxqt/lxqt-runner/blob/master/providers.cpp#L274

LXQT Runner only checks if the search string is part of
- executable name
- title (`Title` in `.desktop`) (weird, as `Title` is no part of the Freedesktop specification...)
- comment (`GenericName` in `.desktop`)
- tooltip (`Comment` in `.desktop`)

However, no `Keywords` from `.desktop`.

**Comment by tsujan** [comment]
You're right — for some reason, I thought `Keywords` should have been covered by LXQt Runner, but it isn't.

**Comment by stefonarch** [comment]
Done in fancymenu plugin.

**Comment by pykereaper** [comment]
> Done in fancymenu plugin.

Great! Is there an ETA in which version the new plugin will be included?

**Comment by tsujan** [comment]
> If you're using arch+AUR it's already there

And currently, it's changing fast. So, you may want to wait a little until the main features are implemented and bugs are found and fixed.

**Comment by tsujan** [comment]
@stefonarch 
I think this can be closed now; can't it? We have different plugins with different behaviors.

**Comment by stefonarch** [comment]
I let it open as lxqt-runner is mentioned.
 Made an count, I've 168 files in `/usr/share/applications/` and 56 have keywords.

**Comment by tsujan** [comment]
Then a report against lxqt-runner is needed. I doubt that we should implement this in Main Menu.

**Comment by stefonarch** [comment]
> Then a report against lxqt-runner is needed. I doubt that we should implement this in Main Menu.

I don't miss the keyword search in runner personally.
