### ISSUE TITLE
If "simple menu" is used search doesn't find most settings

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1985]
As items are not included in the menu but only `lxqt-config` the search doesn't find everything. This could be used also in an eventual `lxqt-applications-fancy.menu` to avoid redundant items.

##### Expected Behavior

Search should find everything.
##### Current Behavior

LXQt-Settings and some other aren't found
##### Possible Solution

Include a category for all settings without displaying it in the menu, similar to:
```
<!-- All settings for search, but category not displayed -->
	<Menu>
			<Name>LXQtSettings</Name>
			<Directory>lxqt-settings.directory</Directory>
			<Include>
				<Category>LXQt</Category>
				<Category>Settings</Category>
				<Category>PackageManager</Category>
				<!-- Include some optional components here -->
				<Filename>pcmanfm-qt-desktop-pref.desktop</Filename>
			</Include>
		</Menu>

```
##### Steps to Reproduce (for bugs)

1. Choose "lxqt-applications-simple" menu in mainmenu or fancymenu
2. Try search "energy" or "appearance"
3. Settings are not displayed

##### Context

https://github.com/lxqt/lxqt-panel/pull/1984
##### System Information

* LXQt Version: up from 1.2 probably.

**Comment by stefonarch** [comment]
>Well if I type "appe" I get Appearence settings. And if I type "sess" I get Session settings.

 Do you use the "simple" menu?

**Comment by stefonarch** [comment]
> You want the category to be hidden because FancyMenu altready has settings toolbutton near "Leave" button, rigth?
> If so how do you "hide" a category in the `.menu`?

It's more clean IMO. I don't remember how the whisker menu of XFCE is,  but anyway I like more this aspect:

![screen_area_ven_18:01:01_](https://github.com/lxqt/lxqt-panel/assets/10681413/3757bebe-270b-4e88-bf47-1bde08967d57)

It's in the "layout" section where "DesktopSettings" can be removed without removing them before.

**Comment by stefonarch** [comment]
@gfgit could you test again?

**Comment by gfgit** [comment]
Hello, what exactly should I test? I did not really understand this issue...

**Comment by stefonarch** [comment]
That the search doesn't find session settings and other LXQt settings, as you said it worked for you.

But anyway I was wrong, categories can't be hidden.

**Comment by gfgit** [comment]
> But anyway I was wrong, categories can't be hidden.

This is because of XDG Menu standard or is FanyMenu which does not implement categories hiding?

Currently I am using `lxqt-applications-compact2.menu` but is a dumb copy of original one.

Tested gnome menu, typing "Asp" results in "Aspetto" (Appearance) so it seems to work.
Tested `kf5-applications.menu`, it works but category icons and Favorites, All Applications icons are missing, don't know why...

`lxde-applications.menu` works.
`lxqt-applications-fm.menu` works.
`lxqt-applications-compact.menu` works.

`lxqt-applications-simple.menu` does **NOT** work: typing same query results are empty. "System tools" has very few entries, it lacks "Preferences" category.
Of course preferences can still be accessed with the tool button below but they should always be searchable at least.

`unitycc.menu` not working but maybe not relevant to LXQt
`xfce-settings-manager.menu` not working
`xfce-applications.menu` works fine.

**Comment by stefonarch** [comment]
> > But anyway I was wrong, categories can't be hidden.
> 
> This is because of XDG Menu standard or is FanyMenu which does not implement categories hiding?

As you can see "screensaver" and "lxqt-about" are not visible with `lxqt-applications.menu", I thought the same trick could work for settings, but it's not like that. I think we could also drop simple menu at this point.

**Comment by tsujan** [comment]
> As you can see "screensaver" and "lxqt-about" are not visible with `lxqt-applications.menu" in fancy menu,

While I confirm @stefonarch's observation, lxqt-about is now visible as a button: https://github.com/lxqt/lxqt-panel/commits/master/

**Comment by gfgit** [comment]
Ok, switched back to English locale for clarity.

New test: type "Ab" should result in "(LXQt) About"

gnome-applications.menu works
kf5-applications.menu works but category icons and Favorites, All Applications icons are missing, don't know why...

`lxde-applications.menu` works fine.
`lxqt-applications-fm.menu` **NOT** working.
`lxqt-applications-compact.menu` **NOT** working.

`xfce-applications.menu` works fine.

**Comment by stefonarch** [comment]
`lxqt-applications-fm.men`u is used for pcmanfm-qt "open with..." context menu.
We could add `lxqt-about.desktop` under "System" but as @tsujan mentioned somewhere search for it is not important as it's just displayed in the first screen with all menus (now).
