### ISSUE TITLE
Make Fancy Menu more keyboard friendly

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#1986]
**Is your feature request related to a problem? Please describe.**

Currently, there is no way for changing the selected category only by using keyboard.

**Describe the solution you'd like**

It's good that the keyboard focus is started in the search entry, but I think the following behavior needs to be implemented:
 * If the search entry isn't empty, the current behavior is fine, namely, the up/down keys select the found matches in the app view.
 * If the search entry is empty, the up/down keys should select the categories, and only after that, right/left keys should switch the focus to the app view, such that up/down keys start to work there.
 * Also when the focus is in the app view, the right/left keys should change the focus to the category view.
 * There shouldn't be any difference between right and left keys (you could call this "wrapping around horizontally"; it will also simplify the code for RTL).

Although I use the word "should" above, what I said was only the best suggestion that came to my mind. If you have a better suggestion, please describe it. I think we need to agree on this before changing the code.

**Comment by gfgit** [comment]
I agree. Maybe I can do it inside the eventFilter and keep a bool flag of which view is currently focused. Don't know if can be done with standard Qt functions like key navigation

**Comment by tsujan** [comment]
@gfgit 
Please wait a little more for us to see if there's a better suggestion about how arrow keys should work — IMHO, that isn't as obvious as it may seem.

Also, I have a PR, and another one will come after it's merged.

**Comment by stefonarch** [comment]
I can't think of anything to change or add in this proposal, except maybe (if possible) that in the search results the first item could be highlighted always, atm it takes one up/down arrow and only then enter starts the app.

**Comment by tsujan** [comment]
> n the search results the first item could be highlighted always

I agree, only when the search entry isn't empty.

But, IMO, there's no need to remember the previous selection *without* a search. It would be confusing if the previous selection was always remembered; the current behavior is quite acceptable.
