### ISSUE TITLE
Fancy menu on debian is disfunctional with favorites

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1996]
* Right click menu to add favorites adds another one, 1 or 2 items up, like the offset.
* Right click on favorites does not appear but executes for the last to items and has the same offset
* Starting apps does not work for the last 2 items in any category too

https://github.com/lxqt/lxqt-panel/assets/10681413/ca405715-9599-497a-a5ad-4384e0e125ec

##### Steps to Reproduce (for bugs)

1. Add favorites to fancy menu under debian
2. test

##### System Information

* LXQt Version: git
* Distribution & Version: debian 12 bookworm VM and installed
  Qt:                     5.15.8

**Comment by tsujan** [comment]
Why do you find impossible issues? ;)

**Comment by stefonarch** [comment]
> Why do you find impossible issues? ;)

I'm a simple farmer with a laptop arch and a PC debian, nothing else...

**Comment by tsujan** [comment]
I bet something's wrong with Debian (bookworm?). I didn't find anything in the code but will scan it with my eyes again.

**Comment by tsujan** [comment]
Also, change your WM and compositor to see if it has any relevance.

**Comment by stefonarch** [comment]
As I said, both in x11 and labwc installed and in x11 virtualbox.

This is the horizontal area where right click works, going more to left it behaves as left click:

![screen_area_dom_18:13:12_](https://github.com/lxqt/lxqt-panel/assets/10681413/93aaf659-c26b-4696-a7cd-067ac536b902)

**Comment by stefonarch** [comment]
As I said, both in x11 and labwc installed and in x11 virtualbox, openbox and xfwm4.

This is the horizontal area where right click works, going more to left it behaves as left click:

![screen_area_dom_18:13:12_](https://github.com/lxqt/lxqt-panel/assets/10681413/02e387ce-1cf4-4727-b398-d84fc31e9a7a)


The vertical area goes from top until the 3rd item from bottom.

**Comment by tsujan** [comment]
For now, my guess is that it may be related to the Qt version in Bookworm. Arch's is 5.15.12.

**Comment by stefonarch** [comment]
Looks like in debian testing with Qt 5.15.10 this issue is not present anymore.
