### ISSUE TITLE
Optional support for auto-selection in Fancy Menu

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#2000]
Some users may prefer auto-selection on mouse-over. The default behavior of selecting by clicking is OK, IMO, but auto-selection can be added with time-outs from 50 ms to 1 sec, with 50-ms steps and 0 for disabling (=default);

**Comment by tsujan** [comment]
I started to work on this because, IMO, it has priority.

**Comment by stefonarch** [comment]
Something I like about runner is the first item from the results already selected, this isn't so in both menus, so for keyboard (just hitting enter) it would be fine.

Just tested in the  wing menu,  selection on hover is  the default and it's nice.
 Btw I think https://github.com/elviosak/plugin-wingmenu/issues/31 is related to the issue on debian with right click.

**Comment by tsujan** [comment]
The implementation was easy and finished; I'll make a PR after some tests.

> Just tested in the wing menu, selection on hover is the default and it's nice.

I think the current behavior of Fancy Menu is good as the default — after all, we have Main Menu, which auto-selects like any other menu. But changing the default will be a piece of cake if needed.

> Something I like about runner is the first item from the results already selected

If the filter text isn't empty, yes, we might want to select the first item. But it'll be the job of another PR if agreed about.
