### ISSUE TITLE
Worldclock sometimes displays another timzone after resume from suspend

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#2019]
##### Expected Behavior

Default timezone is always displayed.
##### Current Behavior

Very rarely it displays one of the others configured. Restarting the panel fix this.
##### Steps to Reproduce (for bugs)
1. Add some timezones to worldclock
2. Use suspend and wait, also some months...

Those screenshots are taken within some minutes, after suspend it displayed Asia/Taipeh, then restarted the panel:

![screen_area_mer_22:18:11_](https://github.com/lxqt/lxqt-panel/assets/10681413/862bae1f-68a8-4449-b8ea-ac61019ffe15)

![screen_area_mer_22:25:06_](https://github.com/lxqt/lxqt-panel/assets/10681413/58d6f239-66ab-4ff1-87ab-5dc32ca5c5b5)
                                             

##### System Information

* LXQt Version: All, git
* Distribution & Version: debian, arch

**Comment by tsujan** [comment]
> Very rarely it displays one of the others configured

I think, on those rare occasions, the mouse wheel was turned, or its equivalent touchpad gesture was done, while the cursor was over the clock.

**Comment by stefonarch** [comment]
Could well be, wasn't aware that the mousewheel change displayed zone.

**Comment by tsujan** [comment]
Changing of displayed zone on turning the mouse wheel was so annoying to me that I removed it every time I compiled the panel — until I got tired of that. Adding an option for it?

**Comment by stefonarch** [comment]
I never noticed it until you mentioned it, but using a touchpad it's less frequent to trigger it. An option could be fine, and/or also a notification `Changed isplayed timezone:  ...` ?

**Comment by tsujan** [comment]
I suggest the complete removal of changing the displayed zone on turning the mouse wheel.

It doesn't make much sense to change the zone by the wheel because (1) we already have the option "Set as default", (2) the clock should show the default zone, and (3) we have the middle-click list.

**Comment by tsujan** [comment]
> also a notification `Displayed timezon changed to "timezone"` ?

That would complicate an already complicated situation ;) The zone should be set explicitly, and we have "Set as default" for that.
