### ISSUE TITLE
CMake: warning about minimum version required too old

### ISSUE THREAD

**Issue by redtide** [lxqt/lxqt-panel#2033]
##### Expected Behavior

No warning, bump the minimum version.

##### Current Behavior

When configuring, there is a CMake warning (IIRC from long time now):
"Compatibility with CMake < 3.5 will be removed from a future version of CMake."

##### Possible Solution

the warning itself suggests the solution by adding a `...3.5` to the minimum version line, but I would set a recent version instead for all LXQt projects for consistence, like a 3.18 which is the one used in Debian Bullseye/oldstable.
I might submit a PR for all projects if defined.

##### Steps to Reproduce (for bugs)

See above

##### System Information

Any, Archlinux here.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/lxqt/discussions/2461
