### ISSUE TITLE
frequent freeze / hang that blocks some X11 keyboard/mouse events

### ISSUE THREAD

**Issue by fenugrec** [lxqt/lxqt-panel#2035]
##### Expected Behavior
Normal behaviour

##### Current Behavior
I have lxqt-panel configured to stay at the top of the screen, with `auto-hide` enabled  (not sure if this changes anything). A few times every day, it stops responding, does not display anymore when hovering the mouse over the border, and various combinations of other problems appear :
- keyboard shortcuts stop working, e.g. "alt+caps lock" to toggle keyboard layouts (see also https://github.com/lxqt/lxqt-config/issues/956 ) or even alt+tab in less common cases
- cannot move windows by dragging title bar (less common)

##### Possible Solution
`killall lxqt-panel` causes it to be automatically respawned in a functional state. Sometimes it's necessary to do this from outside X11, in a text TTY.

##### Steps to Reproduce (for bugs)
1. use computer normally for a few hours...

##### Context
I'm not aware if lxqt-panel can be configured to produce logs / debug output ?
Anything to look for if I install a debug build and attach with gdb ?

##### System Information
    Distribution & Version: Arch
    Kernel: 6.7.6
    Qt Version: 5.15.12
    liblxqt Version: 1.4.0
    Package version: lxqt-panel 1.4.0
    openbox 3.6.1

**Comment by stefonarch** [comment]
>cannot move windows by dragging title bar (less common)

This smells like a WM issue? Which one do you use?

**Comment by fenugrec** [comment]
> This smells like a WM issue? Which one do you use?

Forgot to mention - openbox 3.6.1 . Updated post

**Comment by tsujan** [comment]
> Forgot to mention - openbox 3.6.1

Please use another WM and report back.

**Comment by fenugrec** [comment]
> Please use another WM and report back.

... sure, but is openbox "not recommended" ? What about  sddm or lightdm ?

**Comment by tsujan** [comment]
Openbox is definitely not recommended because it's dead.

sddm is OK. Don't know about lightdm (is it being developed?)

**Comment by fenugrec** [comment]
Sorry, I was confusing DM and WM. Neither sddm or lightdm is a WM, what WM do you suggest ?

**Comment by tsujan** [comment]
xfwm4 or kwin.

I use KWin, but most LXQt users prefer to stay away from it because of its many KDE dependencies. I've tried xfwm4 and found it  to be a good WM. There are others too, but since I haven't used them, I can't recommend them.

Don't forget to disable the compositor you use (if any) before using a WM that comes with a compositor of its own (xfwm4 and kwin both do).

**Comment by stefonarch** [comment]
For xfwm you may have a look at the [wiki](https://github.com/lxqt/lxqt/wiki/ConfigWindowManagers#xfwm4).

**Comment by fenugrec** [comment]
I didn't get around to installing + configuring xfwm, but for the past few days on icewm this hasn't happened again, so it definitely points to openbox doing something wrong. Too bad, it'll take some effort to configure either icewm or xfwm to be similar to my openbox setup. Thanks for the support.

**Comment by stefonarch** [comment]
>to be similar to my openbox setup

If things go well a wayland session using labwc  should be really usable after release of LXQt 2.0
