### ISSUE TITLE
[Feature request] Add info line about middleclick in worldclock → timezones

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#2047]
**Is your feature request related to a problem? Please describe.**

Many people ignore that timezones are shown by middleclick
**Describe the solution you'd like**

Add an info line here:

![screen_area_gio_17:10:45_](https://github.com/lxqt/lxqt-panel/assets/10681413/a8cafa9f-9bfd-4b3f-982b-83896f380d46)

**Describe eventual alternatives you've considered**

Or a popup on save timezones.

**Comment by kravich** [comment]
Oh my god, thank you for pointing to this feature! I use lxde/lxqt for ages, but never knew about it, despite it's very useful for my workflow.
Some hint would definitely be helpful

**Comment by tsujan** [comment]
I found it by chance years ago, while looking for something else in the code. And yes, it's very useful. We should tell users about it in the config GUI somehow.
