### ISSUE TITLE
lxqt-panel: symbol lookup error: /usr/lib64/lxqt-panel/libvolume.so: undefined symbol: _ZNK14PluginSettings5groupEv

### ISSUE THREAD

**Issue by slackernetuk** [lxqt/lxqt-panel#2052]
##### Expected Behavior
A default panel should start under X11
##### Current Behavior
```
Cannot load library /usr/lib64/lxqt-panel/libmount.so: (/usr/lib64/lxqt-panel/libmount.so: undefined symbol: _ZN27LXQtPanelPluginConfigDialog16staticMetaObjectE)"
/usr/bin/lxqt-panel: symbol lookup error: /usr/lib64/lxqt-panel/libvolume.so: undefined symbol: _ZNK14PluginSettings5groupEv

```
##### Possible Solution
Rebuild LXQt 2.0 in order, no change.

```
lxqt-build-tools
libqtxdg
lxqt-menu-data
liblxqt
libsysstat
qtxdg-tools
libfm-extra
menu-cache
libfm-qt
lxqt-themes
qjson 
libdbusmenu-lxqt
lxqt-qtplugin
lxqt-about 
lxqt-admin 
lxqt-openssh-askpass 
lxqt-sudo 
lxqt-config
layer-shell-qt6
lxqt-session 
pcmanfm-qt 
libstatgrab 
lxqt-panel 
muParser 
lxqt-runner
xdg-desktop-portal-lxqt
``

##### System Information
* LXQt Version: 2.0
* Distribution & Version: Slackware current
* Qt Version: 6.6.3
* liblxqt Version: 2.0.0

**Comment by tsujan** [comment]
Have you installed `solid` V6? It's among [required packages](https://github.com/lxqt/lxqt-panel?tab=readme-ov-file#installation).

**Comment by slackernetuk** [comment]
> Have you installed `solid` V6? It's among [required packages](https://github.com/lxqt/lxqt-panel?tab=readme-ov-file#installation).

Yes, solid-6.1.0 is installed.

**Comment by stefonarch** [comment]
In your build order `lxqt-globalkeys` is missing, but the panel shouldn't build without it.

**Comment by slackernetuk** [comment]
> In your build order `lxqt-globalkeys` is missing, but the panel shouldn't build without it.

Sorry my order list is a bit messy, here is my complete order:

```
# QT6/KDE6 dependencies
 
polkit-qt-1
polkit-qt6-1
extra-cmake-modules
layer-shell-qt6
plasma-wayland-protocols
kwindowsystem
kwayland
kconfig
solid
kidletime
jq
libkscreen
breeze-icons
kguiaddons

# lxqt core

lxqt-build-tools
libqtxdg
lxqt-menu-data
liblxqt
libsysstat
qtxdg-tools
libfm-extra
menu-cache
libfm-qt
lxqt-themes
qjson
libdbusmenu-lxqt
lxqt-qtplugin
lxqt-about
lxqt-admin
lxqt-openssh-askpass
lxqt-sudo
lxqt-config
lxqt-globalkeys 
lxqt-session
pcmanfm-qt
libstatgrab
lxqt-panel
muParser
lxqt-runner
xdg-desktop-portal-lxqt

# lxqt apps

lximage-qt
lxqt-archiver
lxqt-notificationd
pavucontrol-qt
qps
qtermwidget
qterminal
screengrab
```

I'll rebuild LXQT, because I forgot to build kguiaddons. And hopefully it will work. :-)

**Comment by berolinux** [comment]
The problem is that the plugins don't see the symbols that are defined in the lxqt-panel binary itself.
Chances are the linker is not exporting symbols from the binary because it isn't a library. Adding `-rdynamic` to the linker flags should help.

**Comment by berolinux** [comment]
PR 2053 fixes it.
