### ISSUE TITLE
Show Deskop widget not working

### ISSUE THREAD

**Issue by chris2553** [lxqt/lxqt-panel#2055]
I've built and installed lxqt-2.0.0. I've found that the panel's Show Desktop widget does not minimise the windows. I've removed and re-added the widget, but it made no difference

##### Expected Behavior
Clicking on the Show Desktop widget should minimise all windows and show the desktop.

##### Current Behavior
Clicking on the Show DEsktop widget does not minimise the windows.

##### Possible Solution
No idea, sorry.

##### Steps to Reproduce (for bugs)
1. Click on the Show Desktop widget whilst one or more windows are open.

##### System Information

* LXQt Version: 2.0.0
* Distribution & Version: Home built based on Linux From Scratch but most packages have been updated since I built the system in 2017.  Although very much on the bleeding-edge in terms of installed packages (which I build and manage using rpm), the system is very stable.
* Qt Version: 6.7.0
* liblxqt Version: 2.0.0

**Comment by stefonarch** [comment]
Check also the if the shortcut set in lxqt-globalkeys is working. Most WMs have an own shortcut set too.

**Comment by chris2553** [comment]
The window manager is Openbox (version 3.6.1) and the plaform is X11 (server version 21.1.13 and libX11 version 1.8.9)

Chris

**Comment by chris2553** [comment]
Ctrl-Alt-D is configured Type:Client and Info:/panelshowdesktop/show_hide. That isn't working either.

**Comment by chris2553** [comment]
Thanks for your help on this. I checked for that entry in ~/.config/openbox/rc.xml. It was there but had two strange
characters embedded in the action name. I removed those and all is now as it should be. No idea how those characters got
there.

Thanks again

Chris

**Comment by chris2553** [comment]
Resolved as in the two posts immediately above this one.
