### ISSUE TITLE
Wrong icon sizes in the fancy menu?

### ISSUE THREAD

**Issue by Trinity3e** [lxqt/lxqt-panel#2056]
Using qt 6.7.0, QT_QPA_PLATFORMTHEME=kvantum, Xft.dpi=144, no other mods, have tried to clear the config

The icons appear to be huge, what can I try?

![screen](https://github.com/lxqt/lxqt-panel/assets/123660226/9ef8233a-4d82-4ff2-aabe-596a97aa6052)

**Comment by tsujan** [comment]
Which LXQt theme do you use?

**Comment by tsujan** [comment]
I think you use the System theme.

Check `Kvantum Manager → Configure Active Theme → Sizes & Delays → Large icon`. It's 32 by default. If you've changed it, set it to 32 again and restart the panel.

**Comment by Trinity3e** [comment]
Oh yes, it was exactly from there, i had the large icon value roughly double that.
Great detective work sir!
I had to change the Qt style from Kvantum to notice, changing the theme from System didn't do it but with this occasion i found a prettier one.

**Comment by tsujan** [comment]
Oh, sorry, I closed the report by mistake when I added my last comment! But it can be really closed now ;) 

Fancy Menu uses a Qt style parameter named `PM_LargeIconSize`. Kvantum allows users to set it to a value different from 32.
