### ISSUE TITLE
[Feature request] Move responsibility for device management to pcmanfm-qt (plugin-mount)

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt-panel#2059]
**Is your feature request related to a problem? Please describe.**

Different behaviour between `plugin-mount` and pcmanfm-qt file manager caused by using different device management systems/solutions.

**Describe the solution you'd like**
This acts as a control ticket and discussion point to re-implement `plugin-mount` based on pcmanfm-qt's agnostic device management interface. Ideally it maps directly to a single feature branch (PR TBD).

Planned steps:

1. Replace the direct calls to `Solid` (KIO) by calls to pcmanfm-qt interface
3. Remove the `solid` library dependency from `plugin-mount`

**Describe eventual alternatives you've considered**
Theres no strong point in implementing a new `plugin-mount2`. Having things break rather helps with possible issues in the right place in pcmanfm-qt itself.

#### Context

Related issues:

* #1639
* … more issues?

**Comment by stefonarch** [comment]
>Replace the direct calls to Solid (KIO) by calls to pcmanfm-qt interface

This will make pcmanfm-qt a dependency of lxqt-panel, not desired IMO.

**Comment by tsujan** [comment]
Not acceptable. See https://github.com/lxqt/lxqt-panel/issues/1639#issuecomment-2094782352
