### ISSUE TITLE
[Feature request]Allow lxqt-panel to be built on a system without wayland

### ISSUE THREAD

**Issue by abatyiev** [lxqt/lxqt-panel#2068]
**Is your feature request related to a problem? Please describe.**
I want to build lxqt-panel on a system without wayland. I'm using Gentoo.

**Describe the solution you'd like**
I want to have a CMake option to disable wayland.

#### Context
I have a half-baked patch for the master branch of lxqt-panel, however I've found out that it seems like there is an ongoing refactoring activity, and so my patch would probably be useless. So, should I create a pull request for a master branch or wait until refactoring is completed? I can provide a patch (in essence, it just #ifdef-ing LayerQtShell invocations).

**Comment by Chiitoo** [comment]
If you haven't seen it yet, perhaps take a peek at:

https://github.com/lxqt/lxqt/issues/2579
