### ISSUE TITLE
[Feature request] Fancy Menu : search using command name

### ISSUE THREAD

**Issue by Bluey26** [lxqt/lxqt-panel#2079]
**Is your feature request related to a problem? Please describe.**

Hi, i have been used to the "command query" that the default/Vanilla lxqt menu has. This is just a small detail, there may be reasons why this has not been added.

**Describe the solution you'd like**

i.e finding programs like "Pulseaudio Volume Control" as `pavucontrol-qt` or specific packages that have a different name in the menu and the command name. (writing `vu` shows pulseaudio result, for example).

**Describe eventual alternatives you've considered**

**Comment by stefonarch** [comment]
Just with `pavucontrol` it happened to me too. I think that could be implemented. @gfgit?

**Comment by gfgit** [comment]
Yes. It should be trivial

**Comment by tsujan** [comment]
Indeed, it's about an elemtary change that results in a good thing: https://github.com/lxqt/lxqt-panel/pull/2087

**Comment by Bluey26** [comment]
Thanks for this!

**Comment by tsujan** [comment]
Thanks for reporting it!
