### ISSUE TITLE
An option for setting alignment of each plugin?

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#2083]
Each plugin has a setting that doesn't appear anywhere in config dialogs but exists in the config file, namely, its alignment — or am I missing something? Please note that I'm not talking about the alignment of the panel itself.

Most of the time this setting doesn't make a difference, but rarely it does, depending on how the two plugins at the ends of a panel are used (sorry that I didn't have time to describe such a use case). It can be changed manually in the panel's config file between Left and Right (while the the panel isn't running), and it takes effect.

It may be argued that users who find a difference in their usage of the two extreme plugins are advanced enough to change the setting manually.

**Comment by isf63** [comment]
Expandable plugins (spacer/taskbar) enforce an alignment from the order of plugins, i.e. `plugins=fancymenu, taskbar, worldclock, showdesktop`. Unless I'm missing something `alignment=` has an effect only when there is one or two fixed (non-expandable) plugins added.
