### ISSUE TITLE
All popups in bottom/right panels align to screen border instead to panel border

### ISSUE THREAD

**Issue by Bluey26** [lxqt/lxqt-panel#2084]
Hi, i considered appropriate to open a new issue for the bugs/issues i have found with the new lxqt-panel branch, which as far as i know its the git master+ some patches for the wayland sessions.

##### System Information

* LXQt Version: version is 2.0, most components from official repositories, a few ones are git master(libfm-qt for example).
* Distribution & Version: Archlinux
* Qt Version: 6.7.2
* liblxqt Version: lastest git branch
* WM: LabWC

##### Current Behavior and  ##### Context

I have been using the new panel branch a few days already, and i noticed the following:

The menu button is hidden when i click the icon. I mean, i cannot click the menu button again because it is hidden behind the fancy menu.
This may be considered as a regression, i did not experienced it in the previous branch i have been using some days/weeks ago. (Markus one)
Along with this,the right click action on active windows in the panel bar has the same behavior, a "lack of spacing" between the pop-up dialog and the icon. (shown in a video below).

I also noticed the following: i have been using `amixer sset Master 5%-` and `amixer sset Master 5%+` for volume control (inside `rc.xml`) successfully for a while, but now there seems to be some kind of issue, that makes "Volume control" to only change 1% or even less with those actions(when it should be like 5%). I have configured my volume action as i did before, not sure what is going on in this one. Fortunately, for this, using the mouse wheel over the volume icon seems to help to change the volume easily.

In the other hand, i noticed that the panel window items (the opened windows icons/representations in the bar) does not cover the entire bottom of the panel. This is noticeable with LXQt themes like Kvantum, Leech and a few more. This causes that the window does not get focused if the mouse is on the bottom border of the screen. I "identified" this specific issue also with Markus fork a few days ago, happens in the new branch and it does not happens in X11 sessions. It may be something wayland specific, or qt specific.

Lastly i noticed that sometimes the menu window gets "triggered" when clicking space bar, after clicking only 1 time other window. 
**Steps to reproduce:** You open the menu and close it, then you focus on another active window and press space (i.e. when using mpv), this causes the menu to pop-up again and forces you to click several times the mpv window to solve it.

**IMPORTANT**: this is just a summary of the things i have been finding with the panel. This is just for not polluting the "wayland taskbar support" pull request, and for giving an idea of possible issues with the panel. I usually ask this things to Stef (he helps me a lot in there xD)  in the Labwc matrix room, but i thought it would be better to display them in here so other persons and developers could be aware of them.

Thanks a lot and sorry for the big texts :smiley: 

##### Possible Solution

Not sure about this.

https://github.com/user-attachments/assets/e27457d5-43bd-494a-a358-c4ab4c33464a

**Comment by tsujan** [comment]
Thanks for describing the issues you've found. I assure you that there are more issues. This is a state of transition.

You could always use https://github.com/lxqt/lxqt/discussions for this kind of info. Unfortunately, this report can't be converted to a discussion directly.

**Comment by Bluey26** [comment]
I could open a discussion and close this issue (copying all the same info with the edit function) so it is shown in there instead.

Yes, i imagine there are more things around, this is so far what i have found

**Comment by tsujan** [comment]
> I could open a discussion and close this issue

There's no need to that. I changed the title, so that no mistake will be possible.

**Comment by stefonarch** [comment]
The space button triggering the menu has always been there, afaik also using TAB other things can be triggered too. `amixer` is fine here.

For the menu, calendar and right click menus aligned at bottom screen and covering the panel: this couldn't be seen in the old branch from Marcus (just tested as I've still the package), so this is definitely  a regression that comes from master git, or something has changed in wlroots.

I'd say to change the title here again, or opening a dedicated issue: every popup covers a bottom panel  in all WMs except kwin_wayland in master.

In the patch branch it's different as it can be seen only using labwc.

But as also tooltips and "add to favorites" are badly aligned I'd recommend top panel too atm. 

`amixer` is fine here.

**Comment by Bluey26** [comment]
> The space button triggering the menu has always been there, afaik also using TAB other things can be triggered too. amixer is fine here.

> For the menu, calendar and right click menus aligned at bottom screen and covering the panel
Yes, i remember it was not present in the marcus branch, but for some reason it started to happen with menu and plugins like calendar and else with the new one. The thing that was present in Marcus branch was the "add to favorites" which was at the bottom of the screen.

About the amixer, i am not sure what is going on in here, it behaves strangely for some reason, it may be not related to lxqt at all.

**Comment by stefonarch** [comment]
I compiled LXQt on debian testing, went all fine except one small error in the wiki, will add the steps needed there. 

The idea was to check if the alignment issue with a bottom panel is there with Qt 6.6.2 and it is as well. Though I can't remember that we had that issue with the release 2.0. of the panel.

**Comment by tsujan** [comment]
> The question is why in the packages from wlroots_taskbar (Marcus) this doesn't happen.

Déjà vu? There were "silent" changes to a related function, which I saw and reversed . They ruined popup positions of the bottom and right panels.

**Comment by tsujan** [comment]
See https://github.com/lxqt/lxqt-panel/pull/2086. You could apply it over any patch you use for Wayland, or apply that patch to the master branch after the merge.

I forgot to link the PR to this report. The report could be closed manually after the PR is tested and merged.

**Comment by tsujan** [comment]
Fixed in https://github.com/lxqt/lxqt-panel/pull/2086.

A similar problem persists with some menus, like Main Menu, as well as tooltips, but as I've explained in the last comments of that PR, its cause is in Qt, not in our code.
