### ISSUE TITLE
kwin_wayland taskbar:  last window still marked as active if all are minimized

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#2094]
##### Expected Behavior

 No active window in taskbar when desktop is shown
##### Current Behavior

Last window is marked active when minimized by button, ok when minimized by right click.menu. It then needs 2 clicks to raise again in both cases, the first click removes the "active" mark only if minimized by button.
            
* LXQt Version: git

**Comment by gfgit** [comment]
We should keep in mind that my KWin Wayland backend was developed on actual KDE 6 code.
Since february, when original PR was created a lot has changed in KDE 6 and bugs were fixed.
So my backend code represents now old KDE code.

**Comment by tsujan** [comment]
Already fixed, perhaps in https://github.com/lxqt/lxqt-panel/commit/50e85649d778b61811f4622045a65f7068451722
