### ISSUE TITLE
LXQt Panel (Volume Control) Unusually High CPU Usage

### ISSUE THREAD

**Issue by Chiitoo** [lxqt/lxqt-panel#2109]
##### Expected Behavior

No excessive CPU usage occurs.

##### Current Behavior

In certain circumstances, the 'lxqt-panel' process starts consuming 100% of CPU (1 thread).

##### Possible Solution

Further investigation required (I did not look into the code for these parts at all yet).

##### Steps to Reproduce (for bugs)

1. Have a Sony DualShock 4 gamepad connected via USB.
2. Run/restart 'lxqt-panel' with the Volume Control widget enabled.
3. Un-plug the DS4 gamepad.
4. Observe 'lxqt-panel' CPU usage spike up to 100% (1 thread).

Looking into the issue with `strace`, there will be tons of `fd=23, revents=POLLERR` messages, where the `fd=23` seems to refer to `/dev/snd/controlC3`, which seems like the audio parts of the gamepad, so I imagine this is not specific to the DualShock 4 gamepad, and should be possible to be re-produced using other (any?) audio device as well.

This does not seem to happen if 'lxqt-panel' is already running when the device is plugged in, but in that situation the file descriptor for `/dev/snd/controlC3` does not appear at all (possibly explained by my use of plain ALSA for audio, and perhaps that could also explain the descriptor not getting cleaned away?).

##### Context

CPU usage at 100% (even if only 1 thread) for a relatively idle process is of course unusual, and most likely not intentional.

##### System Information

* LXQt Version: git master (2024-09-0512:00 UTC)
* Distribution & Version: Gentoo Linux git master (2024-09-05 12:00 UTC)
* Qt Version: 6.7.2
* liblxqt Version: git master (2024-09-05 12:00 UTC)

Thank you!

**Comment by tsujan** [comment]
Isn't this the same as https://github.com/lxqt/lxqt-panel/issues/1866 or related to it?

**Comment by Chiitoo** [comment]
D'oh, very much looks like it.

I thought I looked through the existing issues, but maybe I confused things with other things I was figuring out at the time...

Thanks!

**Comment by tsujan** [comment]
Sorry that I can't help with this. I have PipeWire (the default in Arch), and my knowledge of these things is minimal; so I daren't play with the code.

@palinek
Would you please look into it?

**Comment by Chiitoo** [comment]
I will also try to look into it myself as time permits.

It is a lot more minor issue now that I know causes it.  It was being quite mysterious as I really didn't have a clue what started it (I did get the DS4 controller pretty recently, but it took a long time to realise /that/ was what was doing it).

**Comment by palinek** [comment]
@Chiitoo can you, please, check #2136?

**Comment by Chiitoo** [comment]
Looking good here so far.

Many thanks!
