### ISSUE TITLE
Side effects of a workaround for kwin_wayland task buttons

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-panel#2116]
The following workaround for minimizing on clicking in the code of kwin_wayland task-bar has two side effects at least:

https://github.com/lxqt/lxqt-panel/blob/50e85649d778b61811f4622045a65f7068451722/panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp#L622-L632

First, if an active window is moved to an empty desktop, its task button remains active.

Second, it sometimes results in two active task buttons. I've seen this when opening an image with Krita or GIMP.

This report is a reminder for finding a better solution.

**Comment by tsujan** [comment]
There is an interesting difference between kwin_wayland and other compositors that I've tried, regarding clicking into the panel. With kwin_wayland, the active window really becomes inactive, while in Labwc and Wayfire, it remains active as long as its title-bar is concerned, although its contents become unfocused (and a Qt app sees that as inactiveness). That's the main reason why the problem of minimizing on clicking doesn't happen in the wlroots task-bar.

In the end, both cases are problematic. It's obvious why it's so with kwin_wayland. In the case of wlroots compositors, an active title-bar is inconsistent with unfocused contents — as far as I remember, this didn't happen in X11.

**Comment by stefonarch** [comment]
In Hyprland (maybe also in other tiling WM) the "active" border remains but the keyboard focus is removed whenclicking the icon (aka minimize which has no effect). 
And it allows to switch between more floating windows, which is otherwise impossible, the last one stays on top. Should look into sway for that too.

**Comment by tsujan** [comment]
> In Hyprland (maybe also in other tiling WM) the "active" border remains but the keyboard focus is removed

Yes, that's like labwc and wayfire. It seems that only kwin_wayland is different.

**Comment by tsujan** [comment]
Will be fixed in https://github.com/lxqt/lxqt-panel/pull/2153

**Comment by tsujan** [comment]
Fixed in https://github.com/lxqt/lxqt-panel/commit/0d0d14b6c9f187604c155ea484f6f95ea33af934

**Comment by tsujan** [comment]
With the current git and Qt ≥ 6.8, `kwin_wayland` provides the smoothest Wayland experience. Small nuisances that should be tolerated with other compositors don't exist here.
