### ISSUE TITLE
Exclusive zone does not scale on Wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#2118]
Screenshot with 3 panels and global scale factor 2:
![scaling](https://github.com/user-attachments/assets/92df01a9-cb96-47ac-83e9-194bed228aa4)

##### Expected Behavior

Maximized windows go not behind panel
##### Current Behavior

They do with scaling >1
##### Possible Solution

Scale exclusive zone value accordingly.
##### Steps to Reproduce (for bugs)

1. Set a scale value like 1.2 or more
2. Restart session
3. Maximize any window

           

##### System Information

* LXQt Version: 2.0, git

**Comment by tsujan** [comment]
Apparently `LayerShellQt::Window::setExclusiveZone` doesn't follow `QT_SCALE_FACTOR`.

We can wait for a fix in `layer-shell-qt`, or we can add a workaround, but if we add a workaround, it'll cause the inverse problem when the original issue is fixed.

**Comment by stefonarch** [comment]
There are more issues: any applications like `lxqt-leave` or `qterminal -d`  don't scale at all if launched by shortcut, as do most xwayland windows too (element looks ok, gimp not).
Using wdisplays or kanshi for setting the scale factor has no issues at all.

**Comment by tsujan** [comment]
> Using wdisplays or kanshi for setting the scale factor has no issues at all.

That's how it should be done on Wayland. `QT_SCALE_FACTOR` works fine only on X11. I'm not saying that we should disable it in LXQt Session Settings under Wayland, but adding a tooltip may be a good idea (also because of [https://github.com/lxqt/lxqt-session/issues/541 too](https://github.com/lxqt/lxqt-session/issues/541#issuecomment-2351574062)).

**Comment by tsujan** [comment]
As we know now, LXQt global scaling shouldn't be used under Wayland.
