### ISSUE TITLE
Only few terminals work in directorymenu → open in terminal

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#2121]
We call` terminal --workdir directory` and most terminals don't accept that, not even starting.

##### Expected Behavior

Terminal set in its settings opens the folder
##### Current Behavior

Only konsole and qterminal are actually working
##### Possible Solution

Limit the options to terminals which support the argument `--workdir`.
Or support more args, like `--working-directory=DIR` (foot, lxterminal, kitty)

* LXQt Version: any since https://github.com/lxqt/lxqt-panel/pull/703

**Comment by tsujan** [comment]
Self-assigned because I remembered that I didn't like https://github.com/lxqt/lxqt-panel/pull/703 (although I don't remember why).

**Comment by tsujan** [comment]
Oh, now I remember (thanks to @stefonarch): It was only for QTerminal and Konsole. IMO, adding a list of terminals for something like a panel plugin isn't acceptable. The plugin should either have a tooltip to tell users about that or a better code.
