### ISSUE TITLE
[Feature request] show desktop button should be triggered by mouse button down instead of up

### ISSUE THREAD

**Issue by kurokawachan** [lxqt/lxqt-panel#2123]
**Is your feature request related to a problem? Please describe.**

When you click on the show desktop button to show the desktop, the action should be triggered by mouse button down instead of mouse button up. 

**Describe the solution you'd like**

the action should be triggered by mouse button down instead of mouse button up
**Describe eventual alternatives you've considered**

This is the current behavior  of  lxpanel, and it feels very fast. 
    
We should also avoid having it triggered by double click and triple click

**Comment by tsujan** [comment]
> This is the current behavior of lxpanel

I'm afraid that's not relevant.

> and it feels very fast.

An illusion, because a pressed button should be released.

**Comment by kurokawachan** [comment]
Another thing I would like to point out is that
 
When the user in a hurry to show the desktop, the button might be slightly dragged. If the mouse released outside the button, it would not register the release event and not show the desktop. So, if we use the release event to trigger, there might be an issue.  

If we use press event to trigger, it would almost always trigger the showing the desktop. And it would greatly improve the user experience.

**Comment by stefonarch** [comment]
Every button in the pane (and elsewhere in LXQt) l triggers on release, which generally is considered better UX.
It prevents accidentally clicking and is common in many cases, bookmarks, links ecc.

**Comment by kurokawachan** [comment]
Thanks, would it be possible to add an option for the user to decide if trigger by key down?
I would like to code, if it is ok to you.

**Comment by tsujan** [comment]
In this case, @stefonarch explained why an option doesn't make much sense.

But, in general, LXQt is neither like GNOME (no option) nor like KDE (a jungle of options).
