### ISSUE TITLE
[Feature request] Add direction in the way the status notifier icon is inserted    

### ISSUE THREAD

**Issue by kurokawachan** [lxqt/lxqt-panel#2124]
**Is your feature request related to a problem? Please describe.**

When use the status notifier, the icon of the app would be inside the panel. When the user look for the icon the user would see the location, out of some time, it might create a  habit for user to reach for the location. When the user open a new app, the app would be inserted into the right side of all icons, which would shift the existing icons to the left, which would disturb the habit. So the user might have to relearn the location.  
**Describe the solution you'd like**

when a new app is inserted to the status notifier, insert it into the right side of the notifier, or add an option for user to choose left or right, or allow the user to move the app 

**Describe eventual alternatives you've considered**

This is also requested in lxpanel 
https://github.com/lxde/lxpanel/issues/71

#### Context

I don't have to relearn the location of the app.

**Comment by tsujan** [comment]
> ... which would shift the existing icons to the left...

Not necessarily. It depends on the position of the status notifier plugin — especially relative to the task manager. Moreover, this "feature" is so dependent on personal preferences that I don't think it's worth the extra codes needed by it.

I also checked KDE-Plasma's tray and saw that KDE devs didn't feel a need for such an option. Their tray icons are always ordered from right to left with left-to-right layouts — regardless of the position of the tray — which isn't self-consistent.

> This is also requested in lxpanel

As in https://github.com/lxqt/lxqt-panel/issues/2123, please note that LXDE and LXQt have no relation each other, although the latter was started as a Qt port of the former many years ago.

Anyway, a clean PR, which doesn't clutter the code for such a small customization, would be accepted for reviews.

**Comment by kurokawachan** [comment]
Thanks, would you please provide some advice for https://github.com/lxqt/lxqt-panel/pull/2125
