### ISSUE TITLE
lxqt-panel gives error undefined symbol: _ZN4LXQt10GridLayout13setItemsOrderENS0_10ItemsOrderE

### ISSUE THREAD

**Issue by Frtzqe** [lxqt/lxqt-panel#2158]
##### Expected Behavior
Run time error of lxqt-panel after successful build.

##### Current Behavior
Won't start

##### Steps to Reproduce (for bugs)

1.
2.
3.
4.

##### Context

Build the whole suite on Arch Linux. It seems only lxqt-panel has a problem. 

##### System Information

* LXQt Version:
* Distribution & Version:
* Qt Version:
* liblxqt Version:

**Comment by tsujan** [comment]
The report was closed mainly because it contained no info, although it wasn't reproducible either.
