### ISSUE TITLE
Bad desktop file

### ISSUE THREAD

**Issue by rezso** [lxqt/lxqt-panel#2162]
##### Expected Behavior
The "Name" key exists is the desktop file.

##### Current Behavior
desktop-file-validate output:
/usr/share/applications/lxqt-panel.desktop: error: required key "Name" in group "Desktop Entry" is not present

##### Possible Solution
The "Name" entry exists in yaml files, but the Name entries not merged to desktop file.

##### System Information

* LXQt Version: 2.1.0
* Distribution & Version:
* Qt Version: 6.7.3
* liblxqt Version:  2.1.0

This is a regression, caused by https://github.com/lxqt/lxqt-panel/commit/246b33f12cda7ab54054e9a6a1404fe05737431f

**Comment by stefonarch** [comment]
This is a special file needed only for KWin (panel backend),
```
[Desktop Entry]
Type=Application
TryExec=lxqt-panel
NoDisplay=true

# NOTE: KWin wants absolute path here, get it from CMake install path
Exec=/usr/bin/lxqt-panel

# NOTE: adding KDE to make it work under Plasma Wayland session
OnlyShowIn=LXQt;KDE
X-LXQt-Module=true

# Make KWin recognize us as privileged client
X-KDE-Wayland-Interfaces=org_kde_plasma_window_management
```
