### ISSUE TITLE
[Documentation] Could the main README specify which qt version to use? And, optionally, how far the qt6 situation is?

### ISSUE THREAD

**Issue by rubyFeedback** [lxqt/lxqt-panel#2168]
Right now the README does not say which qt-version to use. I assume qt5, as there is an entry in cmake about WIP (work in progress) in regards to qt6. Either way, I think it may be useful to clearly denote which qt version should be used in regards to this software here.

Additionally or aside from this, perhaps one or two sentences could also explain the qt6 situation, e. g. when it may be expected to work. I have all sorts of problems with compiling qt5 from source these days, whereas qt6 compiles without a problem, and I decided to go with the flow and use only qt6 from now on.

**Comment by tsujan** [comment]
→ [lxqt-build-tools' README](https://github.com/lxqt/lxqt-build-tools) → QT_MINIMUM_VERSION (other versions need to be updated there).

Since LXQt 2.0.0, all components need Qt 6.6 at least. LXQt 2.1.0 was released a few days ago.
