### ISSUE TITLE
non-latin keyboard layouts do not work in search query (wayland)

### ISSUE THREAD

**Issue by Bluey26** [lxqt/lxqt-panel#2177]
##### Expected Behavior

Search query in the menu should bring no results when you use another layout(no valid results).

##### Current Behavior

The search query is not possible, for some reason.

##### Possible Solution

Not sure, maybe the search query is set to only support latin characters.

##### Steps to Reproduce (for bugs)

0. Log-in into a wayland session(i used labwc)
1. Change your keyboard layout to one language that has different alphabet than english or romance languages (i.e. russian,greek,chinese,etc.)
2. Try to search for a program using Fancy menu. This search should be done with one of those layouts.
3. The menu goes off (as when you unfocus it) and there is no search, unless you use latin alphabet
4. Try the same in "Application menu (mainmenu)", same behavior

##### Context

By chance i had another keyboard layout activated and was searching in the menu query as usual, and i found that the menu unfocus when you do this.

This may collide with those users who have a different locale rather than english or romance, because they will not be able to search. This is in the supposed case that the person does not speak english (and that its language is set to other).

Happened to me both in wayland(labwc) ~~and i also tried it into a nested X11 session(xephyr). Both cases were tried with both menus(fancymenu and vanilla one).~~

**Update:** I logged-in into a X11 session and this works, so it seems to be a wayland issue.

This is not something that i would use, but it may be a barrier for other users.

##### System Information

* LXQt Version: 2.1
* Distribution & Version: Archlinux
* Qt Version: 6.8.0
* liblxqt Version: 2.1.0

**Comment by tsujan** [comment]
Confirming, under kwin_wayland.

I set the keyboard to Esperanto and typed "ŝ"; Fancy Menu disappeared. Then I came back to English and pasted "ŝ"; Fancy Menu was there and just showed an empty result, as expected.

@Bluey26 
Since you reported it, you have a hard job to do:

 1. Please go to X11 and see if it happens there too; and
 2. Check if it also happens with the Main Menu.

**Comment by tsujan** [comment]
> I logged-in into a X11 session and this works, so it seems to be a wayland issue.

Oh, sorry, I didn't see this.

> Try the same in "Application menu (mainmenu)", same behavior

And this.

So, it's a Wayland problem. Very strange!

**Comment by Bluey26** [comment]
Yes, i was dubious about the nested X11 result to i've logged into X11(openbox). There the query works as expected in both menus.

I can confirm that pasting an special character while in english layout works in X11 and strangely works in Wayland

**Comment by tsujan** [comment]
We ask someone who uses another language that has characters not found in English. @stefonarch, help us, please!

**Comment by Bluey26** [comment]
Yes, i think its some kind of problem with the layout detection, because the language i tried(russian) has several characters that are almost the same as the latin conterparts (о is the "o" in russian, а is the "a",etc.)

Yet for some reason, this works for spanish ñ, which does not trigger the issue (tildes seem to not be supported, but they do not trigger the issue either)

**Comment by tsujan** [comment]
The problem won't be so important if my locale is English but my keyboard layout is something else. It'll be important if, for example, my locale is Russian and Fancy Menu disappears on typing Russian; and we don't know that yet.

However I think about it, I reach one conclusion: it can't be caused by lxqt-panel. But I can't rely on my conclusion because the situation is so funny ;)

**Comment by Bluey26** [comment]
> lxqt-panel.

Yes, i agree about it, i decided to open the issue in here because it happens in fancymenu, but some Qt string(non-utf8?) variable may be the responsible.

>my locale is Russian and Fancy Menu disappears on typing Russian

Indeed, that is the main motivation about the report, native speakers of those countries will not be able to search, unless they switch their layout and use the command-driven query that has been implemented 😆

**Comment by stefonarch** [comment]
I've no issue searching for à (finds _luminosità_) or ü (german, made a custom desktop file containing that character which is found too).

**Comment by Bluey26** [comment]
> I've no issue searching for à (finds _luminosità_) or ü (german, made a custom desktop file containing that character which is found too).

Yes, pasting the words works, the problem is to write them in non-latin alphabet. Even some special characters coming from latin alphabet are not supported, which are not used at all in fancymenu or queries, but other special ones are supported. 

Example: € triggers the issue, but  æ , ſ , or ð do not (testing german layout).

**Comment by stefonarch** [comment]
Confirmed typing in russian with russian language DE (hyprland) the fancy menu closes at the first letter.

**Comment by tsujan** [comment]
Good news: I found where it happens in the code, and I was able to prevent it easily. But, before making a PR, I need to know why it happens under Wayland. Since it's midnight here, I'll do it tomorrow.

Bad news: None.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/lxqt-panel/pull/2178

It's amusing how a simple thing can look like a baffling puzzle :)

**Comment by Bluey26** [comment]
Working as expected in here, thank you very much!

**Comment by tsujan** [comment]
Thanks for reporting and testing!

**Comment by stefonarch** [comment]
> @stefonarch Do we need yet another point release for this? It'll be a record if yes.

I think so, it will be soon the first russian or greek is trying the wayland-session...

**Comment by tsujan** [comment]
> We could wait some day, to wait for the next issue to arise ;)

Exactly. Let's wait for a few days before making the next point release.
