### ISSUE TITLE
[Feature request] simpler looking resource monitor

### ISSUE THREAD

**Issue by fadi123go** [lxqt/lxqt-panel#2183]
The resource monitor in the panel is too complicated . The graphs has many colors  . Whereas the resource monitor in xfce is better and simpler.  It is only one bar for each unit , processor , ram or swab, with one color each. Also if you click on them xfce task manager launches. Can you make it  like xfce , more compact and launches the task manager on clicking. Here a photo showing all three monitors in xfce in a small space.
![aaa](https://github.com/user-attachments/assets/09729467-b540-4e8b-9405-b8d927506bce)

**Comment by tsujan** [comment]
You could use the Custom Command plugin if you want simpler or customized monitors. See https://github.com/lxqt/lxqt/discussions/2179.

> Can you make it like xfce

We have no reason to do that.
