### ISSUE TITLE
taskbar: Show only windows from desktop  `Current` doesn't work for omnipresent windows

### ISSUE THREAD

**Issue by linuxissuper** [lxqt/lxqt-panel#2186]
##### Expected Behavior

I'm using Openbox and there the feature to show a window on all desktops.  
In Version `2.0.1` lxqt-panel did show all windows from current desktop, including the ones shown on all desktops

##### Current Behavior

In Version `2.1.1` lxqt-panel only shows windows that are shown on all desktops, if I uncheck `Show only windows from desktop`

##### Steps to Reproduce (for bugs)

1. Use Openbox and action `ToggleOmnipresent`
2. or the context menu 
![image](https://github.com/user-attachments/assets/dc2bd026-418a-4349-987f-57057f4085e3)

3. set this: 
![image](https://github.com/user-attachments/assets/774c8861-837a-481c-8a34-d4326f746f98)

4. don't see the window in taskbar

##### System Information

* LXQt Version: 2.1.0
* Distribution & Version: NixOS 24.11
* Qt Version: 6.8.0
* liblxqt Version: 2.1.0

**Comment by stefonarch** [comment]
Confirming, thanks for reporting.

**Comment by tsujan** [comment]
It should be a small problem in the new X11 backend.

**Comment by tsujan** [comment]
Actually, this wasn't just a regression on X11, but caused two problems on kwin_wayland too, one of which was the same as on X11. The fix is here: https://github.com/lxqt/lxqt-panel/pull/2187
