### ISSUE TITLE
On Wayfire, unable to create a panel on Desktop 2

### ISSUE THREAD

**Issue by nobake2048** [lxqt/lxqt-panel#2190]
##### Expected Behavior

Configuring a panel to appear on {top|bottom|right} of desktop 2 should place the panel at the appropriate position.

##### Current Behavior

Using the Wayfire compositor, the panel will remain on desktop 1.

##### Steps to Reproduce (for bugs)

1. Create a new panel, or use the default panel
2. Open Configure Panel dialog for the panel
3. Change Position to anything on desktop 2

##### Context

I wish to have identical panels appear on both of my monitors.

##### System Information

* LXQt Version: 2.1.0
* Distribution & Version: Arch Linux
* Qt Version: 6.8.0
* liblxqt Version: 2.1.0
* lxqt-panel Version: 2.1.1

**Comment by tsujan** [comment]
Already fixed. The fix is in lxqt-panel 2.1.3.

But thanks for caring and reporting.

**Comment by stefonarch** [comment]
If you can't update your panel you need to restart the panel module in "Session Settings".

**Comment by nobake2048** [comment]
I didn't see it in my update list yesterday, my mistake. I got updated and it is working now.
Thanks!
