### ISSUE TITLE
With auto-hide on, task manager icons shift to the right when hidden

### ISSUE THREAD

**Issue by BowDown097** [lxqt/lxqt-panel#2191]
##### Expected Behavior
Task manager icons maintain their position when being hidden and revealed.

##### Current Behavior
Task manager icons shift to the right when hidden, and the shift persists when the icons are revealed again. Can only be fixed (without closing the panel or removing the widget) by opening another window or closing a currently open window. Does not happen if the "Visible thin margin for hidden panel" option is checked.

![Screenshot_20241213_002414](https://github.com/user-attachments/assets/9497e2ba-478c-45e1-bfae-f1f98438c002)
![Screenshot_20241213_002614](https://github.com/user-attachments/assets/3d688a46-a53e-4bd0-a3eb-dfd0580e9455)

##### Steps to Reproduce (for bugs)

1. Enable auto-hide option in panel configuration, make sure "Visible thin margin for hidden panel" is off.
2. Let the panel hide itself, and reveal it again.
3. Task manager in panel will have its icons shifted to the right.

##### Context
Just a visual issue that isn't very hard to "fix" on the user's end, but would be nice if it were fixed.

##### System Information

* LXQt Version: 2.1.3, under Wayfire
* Distribution & Version: Artix Linux
* Qt Version: 6.8.1
* liblxqt Version: 2.1.0

**Comment by stefonarch** [comment]
Confirmed, happens on every compositor (just tested also Hyprland).

**Comment by tsujan** [comment]
The important question: Does it happen under X11 too?

**Comment by isf63** [comment]
I can't reproduce it in X11.

**Comment by tsujan** [comment]
And I can't reproduce it under kwin_wayland.

Some info is missing.

**Comment by stefonarch** [comment]
Actually if we could preserve this it would be perfect for a dock like taskbar...

**Comment by tsujan** [comment]
> make sure "Visible thin margin for hidden panel" is off.

I always uncheck it.

As I said, a piece of info should be missing.

**Comment by tsujan** [comment]
OK, it magically started to happen here. Maybe there's a random factor to it. Will investigate it.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/lxqt-panel/pull/2192

The bug always existed in the code, but it did nothing until we hid the panel on Wayland (on X11, we just set its opacity to zero).

@BowDown097, thanks a lot for reporting! Without the report, I might not see the problem soon, because I use a second auto-hiding panel with only a quick launcher, like a dock.

Please also check if another plugin has a similar issue, although that's hardly likely.

BTW, there was no random factor in the code — only by chance, I opened a window the first time I tested.

**Comment by BowDown097** [comment]
Big ups for the quick fix 😃 There doesn't appear to be an issue with any other built-in widgets on default settings at least.
