### ISSUE TITLE
[Feature request] the bottom line of the panel is not clickable 

### ISSUE THREAD

**Issue by kurokawachan** [lxqt/lxqt-panel#2202]
**Is your feature request related to a problem? Please describe.**

When you are trying to open the menu in a hurry, you simply just move the mouse the left bottom corner. 
However, you would have to move the mouse up one pixel to be able to click. 
I'm always frustrated when I have to adjust the mouse a little bit. 
It's the same when you trying to click on the task bar. The bottom line are all not clickable

When you use Microsoft windows, the right bottom corner is where you minimize all the windows, you don't really aim for the button. You just move it.  

**Describe the solution you'd like**

Make the bottom line all clickable like lxpanel

**Describe eventual alternatives you've considered**

**Comment by tsujan** [comment]
Not a panel issue.

If you use a wlroots-based Wayland compositor, see https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4683.

Otherwise, use/make a panel theme whose menu button doesn't have a margin.

**Comment by kurokawachan** [comment]
Hello @tsujan 

I am using X11

**Comment by tsujan** [comment]
> I am using X11,

Then please be more specific. Which window manager and which LXQt theme do you use? Does it happen with another WM/LXQt theme?

> if I were to use Wayland, what theme do I make?

It makes no difference. wlroots has that problem with all Qt apps.

**Comment by tsujan** [comment]
I checked all LXQt themes. None of them set `padding` or `margin` to a nonzero value for `Plugin`. I also tested a few themes with Openbox, kwin_x11 and xfwm4; the main menu of the bottom panel responded to clicking when the mouse cursor was at the bottom of the screen.

**Comment by kurokawachan** [comment]
Hello @tsujan 

I am using openbox, I am using default debian install, I am not sure what theme? Where do I look? Do you have a screenshot to tell me how to check, the theme is very confusing, I looked and it look like icon theme and LXQt theme all different

**Comment by tsujan** [comment]
> I am using default debian install

Which version of LXQt? The latest version of LXQt is 2.1.0.

> Where do I look?

Configuration Center → Appearance → LXQt Theme

**Comment by kurokawachan** [comment]
Hello @tsujan 

> Configuration Center → Appearance → LXQt Theme

The name is Debian 

I just found that it only happens when I set 

QT_SCALE_FACTOR=2

https://doc.qt.io/qt-5/highdpi.html

**Comment by stefonarch** [comment]
Confirming here. 
It doesn't happen with factor 1.5 and also not with a top panel with factor 2.0. The theme doesn't matter afaik.

**Comment by tsujan** [comment]
That's quite a different thing. Will check the X11 code to see whether there's a miscalculation…

**Comment by kurokawachan** [comment]
Thank you very much @tsujan 

So, it is the same issue as you mentioned here ? https://github.com/lxqt/lxqt-panel/issues/2202#issuecomment-2558340336

I am not sure what is a one-pixel issue" of Qt ?  Do we have a link to some discussions or merge requests for Qt, this [link](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4683) does not seems to lead to Qt website.

**Comment by tsujan** [comment]
> So, it is the same issue as you mentioned here ?

Not exactly, but they're about the same kind of miscalculation.

> I am not sure what is a one-pixel issue" of Qt 

On pixel at the right and the bottom of the screen may not be taken into account in [`QMouseEvent`](https://doc.qt.io/qt-6/qmouseevent.html), under certain circumstances.

I don't know of any Qt bug report, but this is the second time I encounter it — the first case has been confirmed by others too, as the link shows.

Also, see this report (by me): https://github.com/labwc/labwc/issues/2379

**Comment by kurokawachan** [comment]
Thank you @tsujan

**Comment by tsujan** [comment]
As a workaround, you might want to put your panel at the top — I have a feeling that this may be one of those Qt bugs that persist for a long time, even if reported.

**Comment by kurokawachan** [comment]
Hello @tsujan 

Thank you very much and merry Christmas
