### ISSUE TITLE
Wayland: adding "kbindicator" widget does nothing.

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#2203]
Not sure how to handle that. If it's already present it won't be shown and that's fine.
But it can't be added under Wayland, so no harm too, but there is no info and users will have no clue.

##### Expected Behavior

Best: it works under Wayland, but this is not to happen anytime soon probably.
Second best: change the text, or show a message.
##### Current Behavior

Nothing happens at all.
##### Possible Solution

Change its text?
```
Desktop Entry/Name: "Keyboard State Indicator"
Desktop Entry/Comment: "Keyboard state indicator and switcher plugin (X11 only)"
```
                                         
* LXQt Version: 2.*

**Comment by tsujan** [comment]
I think adding that "(X11 only)" will be enough.
