### ISSUE TITLE
Please make the LXQt panel work like the Microsoft Windows 7 Taskbar (or DockbarX / DockX etc.) and please improve vertical panel mode

### ISSUE THREAD

**Issue by wp9015362** [lxqt/lxqt-panel#33]
Hello,

please make the LXQt panel work like the Microsoft Windows 7 Taskbar:

http://windows.microsoft.com/en-us/windows7/help/better-stronger-faster-the-windows-7-taskbar
http://msdn.microsoft.com/en-us/library/windows/desktop/aa511446.aspx
http://msdn.microsoft.com/en-us/library/windows/desktop/dd378460%28v=vs.85%29.aspx

or DockbarX / DockX:

http://www.webupd8.org/2012/10/dockbarx-sees-new-release-now-available.html
http://www.youtube.com/watch?v=GPslUYIwgag

or the Cinnamon Window List with App Grouping panel applet:

http://cinnamon-spices.linuxmint.com/applets/view/16

for example.

Or, with other words:

Please make the task buttons so that they function as application launchers and please add application grouping, window lists, window previews, jump lists, overlay icons, thumbnail toolbars and so on.

And please improve the vertical mode of the LXQt panel.

Currently the vertical panel is much too wide and so on.

The vertical panel mode is extremely important IMHO, because, IMHO, on widescreen displays, it makes much more sense to use a vertical panel instead of a horizontal panel.

It would be much appreciated.

Regards

**Comment by dirifiz** [comment]
Please, upgrade LXQT panel to year 2023. It's a joke that it has not been implemented yet. For me it's neglect.
