### ISSUE TITLE
Add favourites to Application Menu 

### ISSUE THREAD

**Issue by ianp5a** [lxqt/lxqt-panel#882]
Requirement: add the capability for users to pin favourite applications to the Application Main menu. Between 2 and 20 applications may be needed. 

Reason: Mouse users need a way to start their favourite applications quickly. Without searching or navigating first. 
Currently, using LXQT is slower to use than other desktops with favourite or pinned applications. 

Mouse users? Users who use a mouse to control the desktop. Who's hands are not on the keyboard. Typically users of graphical applications. Often people who work and think visually. Where doing a text search does not come naturally.

Add and Remove favourite: other desktops, such as KDE, Mate, Windows, do this using the Right Click on the app icon found in the menu. A Context Menu has an "Add to Favourites" option. Likewise they can be removed with a "Remove Favourite" context menu item. 
Drag and drop, as with adding to the quicklauncher, would also be OK.

Location: These apps should be directly accessible when the menu appears. So they can be immediately clicked. This means they can either be placed in the root position of the menu hierarchy, or in a Category called favourites. But this category must be able to be open by default. And not collapsed, requiring an extra click. 

I'm using Lubuntu 18.10.

---------------------------------------------
The Quick launcher is not a substitute for this requirement, as it permanently takes up space. Reducing the task bar space. Secondly only the icon is visible there. So it becomes unclear, when lots of favourites are present which is which.

Workaround is to use the Alacarte Menu Editor. But this requires more steps and knowledge. And most users will not discover it.

**Comment by agaida** [comment]
use panel quickstarters - we will not change the current menu, maybe we will add a second layout with more caps. Patches welcome.

**Comment by agaida** [comment]
Btw - there are a lot of applications in the wild that do exactly what you want: plank, wbar and other quick start docks - so no need to re-invent the wheel. Second thing - add a second panel someware and place a quickstarter in. Put the needed thing into and be done with.

**Comment by tsujan** [comment]
> add a second panel someware and place a quickstarter in. Put the needed thing into and be done with.

And auto-hide it, like a dock.

Yes, there are several possibilities and LXQt isn't a duplicate of KDE, Mate or Windows (Windows isn't a DE but an OS).

**Comment by ianp5a** [comment]
This is a requirement to integrate this function, rather than hope users discover some plugins. And to avoid people having to perform a series of extra operations. There are good usability reasons why other desktop environments do this.

**Comment by agaida** [comment]
no - this is not a requierement. and never will be.

**Comment by ianp5a** [comment]
"there are a lot of applications in the wild that do exactly what you want: plank, wbar and other quick start docks" 
These actually don't do what is required, which is to improve the usability of the Main Menu. I suspect there is a misunderstanding of the requirement. I'd be happy to discuss this in an appropriate place.

**Comment by tsujan** [comment]
The user might want to launch/use some apps more often than others. It isn't important which name is given to those apps ("Favorites", for example) or where they are accessible. The important thing is that they are easily accessible.

As mentioned above, there are already different ways to have this feature. An auto-hiding panel is one of them:

![auto-hiding](https://user-images.githubusercontent.com/981076/50585648-44431200-0e8b-11e9-82d8-56a8d48f6eec.png)

An auto-hiding panel takes no extra space and is accessible more than the main menu is (no click).

We usually don't add duplicate functionalities, even though they may have well-known names in some other DEs.

**Comment by tsujan** [comment]
Now we have Fancy Menu (in git), which supports Favorites.
