### ISSUE TITLE
With window grouping on Mouse click on taskbar button raises window

### ISSUE THREAD

**Issue by toeserve** [lxqt/lxqt-panel#908]
When window grouping is enabled for the taskbar, a mouse click on a taskbar button both displays a window pop-up menu and also raises one of the windows on the menu randomly. The raising of the Window is very annoying since in window grouping mode, one may want to select the window that one wants to raise from the pop up menu before the window is raised. On the old lxde thats how things worked, you clicked on a taskbar button, it displayed a pop up menu of windows, and you clicked on the window you wanted to be raised. Please at least add an option for this so that no window is raised until a window is selected on the pop up menu.

**Comment by agaida** [comment]
will even not process this - a hint: God damn, if filing a bug, fill out the fine issue form - no filled out form, no processing
