### ISSUE TITLE
[feature request] preview of window in task manager when mouse cursor is hovered

### ISSUE THREAD

**Issue by librewish** [lxqt/lxqt-panel#910]
when using kwin as window manager 
the more desirable function of window preview on mouse hover is not included in lxqt.so please consider adding it

**Comment by tsujan** [comment]
My guess: kwin should add it. Compiz-reloaded has a similar functionality that works with LXQt.

@palinek Is it possible in a WM agnostic way?

**Comment by tsujan** [comment]
OK, this should be provided by the compositor -- we don't want explicit X11 codes. KWin doesn't support it without Plasma. In contrast, Compiz-reloaded can it everywhere:

![compiz](https://user-images.githubusercontent.com/981076/51210597-75f6b700-1928-11e9-83d8-bd1fe67b4fbc.png)

Closing.
