### ISSUE TITLE
[feature request] a real network monitor widget which shows current download/upload speed

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt-panel#911]
the network monitor widget in lxqt panel only shows downloaded and uploaded data quantity.no information about speed

**Comment by tsujan** [comment]
IMO, System Statistics will be enough with a better tooltip:

![ss](https://user-images.githubusercontent.com/981076/51085989-0335e200-1756-11e9-8bc3-5d5fe1e9d1c2.png)

**Comment by tsujan** [comment]
Related: https://github.com/lxqt/lxqt/issues/1615

Network Monitor may even be a duplicate when System Statistics works with network.

**Comment by rubyFeedback** [comment]
I think it is not completely the same, e. g. tooltip may require a mouse hover event? Or perhaps you meant this as permanent showing and updating this every now and then.

It reminds me a bit of what you can do via conky.

**Comment by tsujan** [comment]
I meant something like a tooltip but, probably, persistent and continuously updated as long as the cursor is over the widget. Numbers take extra space -- especially two of them (download + upload) -- and are a mess on (thin) vertical panels.

> It reminds me a bit of what you can do via conky.

I do lots of such things with conky and leave the panel for graphs, icons and clock. Conky can have audio/visual alarms when, just as one example, hard temp is too high for a long time, and it provides so many other possibilities...

**Comment by 3xploiton3** [comment]
still waiting this feature

**Comment by tsujan** [comment]
> still waiting this feature

PRs will be accepted for review. None has been made so far.

**Comment by librewish** [comment]
if any one wants
there is a sidebar 
coreaction
which has download/upload speed indicator.
and its in qt.

https://gitlab.com/cubocore/coreaction

if you are using arch linux/or based 
you can install from aur.

https://aur.archlinux.org/packages/coreaction-git/

**Comment by agaida** [comment]
@librewish - you are so cool - but it doesn't really solve the problem that this feature is not implemented in LXQt - and imho should not implemented, because it says nothing.
