### ISSUE TITLE
small gap between window and screen edge when autohide is used

### ISSUE THREAD

**Issue by librewish** [lxqt/lxqt-panel#929]
its particularly annoying to have a gap when panel is set to autohide.
this gap is between screen edge and window.
if its possible can there be an dodge active window instead/alongside of autohide??

**Comment by tsujan** [comment]
There's no gap (make the panel's length smaller to see that). What you may see is a 4-px panel border for the cursor to show it again.

**Comment by tsujan** [comment]
Also see https://github.com/lxqt/lxqt-panel/issues/930
