### ISSUE TITLE
World clock applet settings miss font and size settings

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt-panel#967]
I cannot find the font and size settings for the World Clock in the GUI. It would be nice to be able to change this easily to match the users panel settings.

![where do i set the font and size of the clock](https://user-images.githubusercontent.com/33556631/32677837-570cc22e-c660-11e7-8dd3-244402346364.png)

##### Expected Behavior
Font and size settings somewhere in the Settings for the world clock.

##### Current Behavior
No such GUI options.

##### Steps to Reproduce (for bugs)
Right click panel to open settings.
Select World Clock applet
Press the settings button.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:   0.12.0-1
* Package version:  0.12.0-1

**Comment by tsujan** [comment]
Why is this still open?!

**Comment by 99991** [comment]
# Change World Clock Font Size

1. Right-click on clock
2. Left-click on `Configure "World Clock"`
3. Check `Advanced manual format`

![settings](https://github.com/lxqt/lxqt-panel/assets/18725165/08c7b96c-f754-4889-b6e5-abebb6528ec5)


5. Click on `Customise ...` (this will open a window titled "World Clock Manual Format Configuration")

![fontsize](https://github.com/lxqt/lxqt-panel/assets/18725165/11b8b487-86e7-435f-94c9-7c7cf54887e1)

7. Enter your desired format into the opened window. You can specify the font size as HTML. I am using the following format:

```html
'<font size="10">'hh:mm:ss, MMM d'</font>'
```

8. Click `OK`
